'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import Image from 'next/image'
import {ArrowLeft,ArrowRight,Trophy,Zap} from 'lucide-react'
import {MISSIONS,COMPETENCIES,PRACTICE_XP} from '@/lib/math-missions/catalog'
import styles from './missions.module.css'
export type MissionHistory={id:string;mission:string;code:keyof typeof COMPETENCIES;mode:string;status:string;completed_at:string|null;review_note?:string|null}
export type MissionAssignment={id:string;mission:string;code:keyof typeof COMPETENCIES;title:string;due_at:string|null;completed_at:string|null;user_id:string}
export type Leader={mission:string;name:string;score:number;rank:number;period:string;isMe:boolean}
export function MissionAssignments({compact=false}:{compact?:boolean}){
 const [data,setData]=useState<{history:MissionHistory[];assignments:MissionAssignment[]}|null>(null),[error,setError]=useState('');
 useEffect(()=>{let live=true;fetch('/api/math-missions').then(async r=>{if(!r.ok)throw Error('Could not load math missions.');return r.json()}).then(d=>{if(live)setData(d)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[]);
 const pending=data?.assignments.filter(a=>!a.completed_at)||[];
 const due=(data?.history||[]).filter(s=>s.status==='completed'&&s.mode==='practice'&&s.completed_at&&Date.now()-Date.parse(s.completed_at)>=86400000).filter((s,i,all)=>all.findIndex(x=>x.code===s.code)===i).filter(s=>!(data?.history||[]).some(r=>r.code===s.code&&r.mode==='retention'&&r.status==='completed'&&r.completed_at!>s.completed_at!));
 return <section className={compact?'':styles.shell} style={{minHeight:"auto",padding:24,borderRadius:20,marginBottom:24}}><h2 className={styles.sectionTitle}>Math missions</h2><p>Build a strategy, practice with support, and check what you remember.</p>{error&&<p role="alert">{error}</p>}<div className={styles.assignmentList}>{pending.map(a=><Link key={a.id} href={`/arcade/missions/${a.mission}?skill=${a.code}&assignment=${a.id}`}><span><strong>{a.title}</strong><small>{a.due_at?`Due ${new Date(a.due_at).toLocaleDateString()}`:'Assigned practice'}</small></span><ArrowRight size={18}/></Link>)}{due.map(s=><Link key={s.code} href={`/arcade/missions/${s.mission}?skill=${s.code}&mode=retention`}><span><strong>Ready for a delayed check · {s.code}</strong><small>Try new problems without the recent example.</small></span><ArrowRight size={18}/></Link>)}</div>{data?.history.filter(s=>s.review_note).slice(0,3).map(s=><div className={styles.reviewCard} key={s.id}><strong>Teacher feedback · {s.code}</strong><p>{s.review_note}</p></div>)}<Link className={styles.primary} href="/arcade/missions">Explore all seven missions <ArrowRight size={17}/></Link></section>
}
export default function MissionHub({embedded=false,query=""}:{embedded?:boolean;query?:string}){
 const [leaders,setLeaders]=useState<Leader[]>([]),[history,setHistory]=useState<MissionHistory[]>([]),[assignments,setAssignments]=useState<MissionAssignment[]>([]),[cap,setCap]=useState(10),[error,setError]=useState(''),[filter,setFilter]=useState('all'),[reload,setReload]=useState(0),[loaded,setLoaded]=useState(false);
 useEffect(()=>{const controller=new AbortController();fetch('/api/math-missions',{signal:controller.signal}).then(async r=>{if(!r.ok)throw Error('Saved missions and leaderboards could not load.');return r.json()}).then(d=>{setLeaders(d.leaders);setHistory(d.history);setAssignments(d.assignments);setCap(d.dailyCap);setLoaded(true);setError('')}).catch(e=>{if(!controller.signal.aborted)setError(e.message)});return()=>controller.abort()},[reload]);
 return <section className={styles.shell} style={embedded?{padding:"24px",borderRadius:"22px",minHeight:"auto"}:undefined}>{!embedded&&<><nav className={styles.topbar}><Link href="/arcade"><ArrowLeft size={17}/>The arcade</Link><span>MATH MISSIONS</span><Link href="/dashboard/math-spine">My learning</Link></nav><header className={styles.hero}><span className={styles.eyebrow}>SEVEN WORLDS. THIRTEEN SKILLS.</span><h1>Make your next<br/>move make sense.</h1><p className={styles.tagline}>A little help. A new way to think.</p><p>Build fluency through missions that let you see, move and test the mathematics. Practice at your pace, then take on a daily challenge.</p></header></>}
 {embedded&&<header style={{marginBottom:24}}><span className={styles.eyebrow}>BUILD FLUENCY</span><h2>Math missions</h2><p>Seven interactive worlds. Guided practice, saved progress, and daily challenges.</p></header>}
 {error&&<div role="alert" className={styles.error}>{error}<button className={styles.secondary} onClick={()=>setReload(n=>n+1)}>Retry</button></div>}
 <div className={styles.assignmentList}>{assignments.filter(a=>!a.completed_at).map(a=><Link href={`/arcade/missions/${a.mission}?skill=${a.code}&assignment=${a.id}`} key={a.id}><span><strong>{a.title}</strong><small>Assigned to you{a.due_at?` · due ${new Date(a.due_at).toLocaleDateString()}`:''}</small></span><ArrowRight size={18}/></Link>)}</div>
 {!embedded&&<nav className={styles.filterBar} aria-label="Math mission skills">{[['all','All missions'],['NS','Number sense'],['PR','Proportions'],['QE','Quantities'],['SM','Equations'],['GV','Graphs & vectors']].map(([id,label])=><button key={id} className={filter===id?styles.selected:styles.secondary} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{label}</button>)}</nav>}
 <div className={styles.grid}>{MISSIONS.filter(m=>(filter==='all'||m.codes.some(c=>c.startsWith(filter)))&&(!query||[m.name,m.description,...m.codes].join(' ').toLowerCase().includes(query.toLowerCase()))).map(m=>{const weekly=leaders.filter(l=>l.mission===m.slug&&l.period==='weekly'),record=leaders.find(l=>l.mission===m.slug&&l.period==='all-time'&&l.rank===1),me=leaders.find(l=>l.mission===m.slug&&l.period==='weekly'&&l.isMe),active=history.find(s=>s.mission===m.slug&&s.status==='active');return <article className={styles.card} key={m.slug} style={{'--mission-color':m.color} as React.CSSProperties}><Link href={`/arcade/missions/${m.slug}`} className={styles.cardArt} style={{display:'block'}}><Image src={`/arcade/previews/mission-${m.slug}.webp`} alt={`${m.name} game board`} fill sizes="(max-width:760px) 100vw,(max-width:1050px) 50vw,33vw"/></Link><div className={styles.cardBody}><span className={styles.eyebrow}>{m.codes.join(' + ')} / 5–8 MIN</span><h2>{m.name}</h2><p>{m.description}</p><div className={styles.reward}><Zap size={20}/><strong>Up to {PRACTICE_XP} XP</strong><span>per complete session · shared {cap} XP/day cap</span></div><div className={styles.leader}><strong><Trophy size={15}/> CHALLENGE LEADERBOARD</strong><div><span>This week</span><b>{!loaded?'Loading…':weekly[0]?`${weekly[0].name} · ${weekly[0].score}`:'Set the first score'}</b></div><div><span>All-time best</span><b>{record?`${record.name} · ${record.score}`:'—'}</b></div><div><span>Your weekly rank</span><b>{me?`#${me.rank} · ${me.score}`:'—'}</b></div></div><div className={styles.cardActions}><Link className={styles.primary} href={`/arcade/missions/${m.slug}${active?`?session=${active.id}`:''}`}>{active?'Resume':'Build fluency'}</Link><Link className={styles.secondary} href={`/arcade/missions/${m.slug}?mode=challenge`}>Challenge</Link></div><p className={styles.fine}>Help is welcome. Your learning evidence stays private.</p></div></article>})}</div></section>
}
