'use client'
import {useEffect,useRef,useState} from 'react'
import Link from 'next/link'
import {useSearchParams} from 'next/navigation'
import {ArrowLeft,ArrowRight,Check,Lightbulb,Pause,Play,RotateCcw,Trophy,Zap} from 'lucide-react'
import {COMPETENCIES,MISSIONS,PRACTICE_XP,SESSION_STEPS,missionBySlug,type CompetencyCode,type MissionMode} from '@/lib/math-missions/catalog'
import type {Answer,SessionView} from '@/lib/math-missions/types'
import MissionBoard from './MissionBoard'
import styles from './missions.module.css'
export default function MissionPlayer({slug}:{slug:string}){
 const mission=missionBySlug(slug)!,params=useSearchParams();const initialSkill=params.get('skill');
 const [code,setCode]=useState<CompetencyCode>((mission.codes as readonly string[]).includes(initialSkill||'')?initialSkill as CompetencyCode:mission.codes[0]);
 const [mode,setMode]=useState<MissionMode>(params.get('mode')==='retention'?'retention':params.get('mode')==='challenge'?'challenge':'practice');
 const [session,setSession]=useState<SessionView|null>(null),[answer,setAnswer]=useState<Answer>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[cap,setCap]=useState(10);
 const [resumeId,setResumeId]=useState<string|null>(params.get('session'));
 const requestId=useRef<string|null>(null),working=useRef(false),heading=useRef<HTMLHeadingElement>(null);
 const returnTo=params.get('returnTo');const safeReturn=returnTo&&/^\/(lessons|dashboard|arcade)(\/|\?|$)/.test(returnTo)&&!returnTo.includes('\\')?returnTo:'/arcade/missions';
 useEffect(()=>{let live=true;fetch('/api/math-missions').then(async r=>{if(!r.ok)throw Error('Sign in to load saved missions.');return r.json()}).then(d=>{if(!live)return;setCap(d.dailyCap);const active=d.history?.find((s:{mission:string;code:string;mode:string;status:string})=>s.mission===slug&&s.code===code&&s.mode===mode&&s.status==='active');setResumeId(params.get('session')||active?.id||null)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[slug,code,mode,params]);
 useEffect(()=>{if(!session)return;try{localStorage.setItem('mission-draft:'+session.id,JSON.stringify({revision:session.revision,answer}))}catch{/* Server progress is still saved. */}},[answer,session]);
 const apply=(s:SessionView)=>{setSession(s);setAnswer(s.state.draft);setError('');};
 async function start(resume=false){
  if(working.current)return;working.current=true;setBusy(true);setError('');
  try{requestId.current??=crypto.randomUUID();const response=resume&&resumeId?await fetch('/api/math-missions?id='+resumeId):await fetch('/api/math-missions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'start',id:requestId.current,mission:slug,code,mode,assignmentId:params.get('assignment')||undefined})});const d=await response.json();if(!response.ok)throw Error(d.error||'Could not start mission.');apply(d.session);try{const cached=JSON.parse(localStorage.getItem('mission-draft:'+d.session.id)||'null');if(cached?.revision===d.session.revision&&cached.answer&&typeof cached.answer==='object'&&!Array.isArray(cached.answer)&&Object.values(cached.answer).every(v=>typeof v==='string'))setAnswer(cached.answer)}catch{/* Ignore invalid cached drafts. */}}
  catch(e){setError(e instanceof Error?e.message:'Could not start mission.')}finally{working.current=false;setBusy(false)}
 }
 async function act(action:string){if(!session||working.current)return;working.current=true;setBusy(true);setError('');try{const r=await fetch('/api/math-missions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id:session.id,revision:session.revision,answer})});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not save progress.');apply(d.session);if(action==='next')heading.current?.focus();}catch(e){setError(e instanceof Error?e.message:'Could not save progress.')}finally{working.current=false;setBusy(false)}}
 const reset=()=>{setSession(null);setAnswer({});requestId.current=null;setResumeId(null)};
 const task=session?.task,s=session?.state,completed=session?.status==='completed',canNext=!!s?.checked&&(s.feedback?.correct||s.revealed||session?.mode==='challenge');
 return <main className={styles.shell} style={{'--mission-color':mission.color} as React.CSSProperties}>
  <nav className={styles.topbar} aria-label="Mission navigation"><Link href={safeReturn}><ArrowLeft size={17}/> {safeReturn==='/arcade/missions'?'Math missions':'Return to learning'}</Link><span>{mission.icon} {mission.name}</span><Link href="/dashboard/math-spine">My learning</Link></nav>
  {!session?<>
   <header className={styles.hero}><span className={styles.eyebrow}>MATH MISSIONS / {mission.codes.join(' + ')}</span><h1>{mission.name}</h1><p className={styles.tagline}>{mission.verb}</p><p>{mission.description}</p></header>
   <div className={styles.launchGrid}><section className={styles.launchPanel}><h2>Choose your mission</h2><label className={styles.field}>Skill<select value={code} onChange={e=>{setCode(e.target.value as CompetencyCode);requestId.current=null}}>{mission.codes.map(c=><option key={c} value={c}>{c} · {COMPETENCIES[c]}</option>)}</select></label><div className={styles.modeChoice}>{(['practice','challenge','retention'] as MissionMode[]).map(m=><button key={m} aria-pressed={mode===m} className={mode===m?styles.selected:styles.secondary} onClick={()=>{setMode(m);requestId.current=null}}>{m==='practice'?'Build fluency':m==='challenge'?'Daily challenge':'Delayed check'}</button>)}</div><p>{mode==='practice'?'Six short tasks: find your starting point, build a strategy, and try independently. Take all the time you need.':mode==='challenge'?'The same six tasks for everyone today. Your first run can rank; repeats are practice. No speed bonus. Asking for help makes the run unranked.':'Return at least 24 hours after practice. New tasks check what you remember. Help is still available and recorded.'}</p><div className={styles.reward}><Zap size={22}/><strong>Up to {PRACTICE_XP} XP</strong><span>for completing a session · shared {cap} XP daily allowance</span></div><p className={styles.fine}>Hints never reduce your completion reward. Staff previews earn no XP.</p>{resumeId&&<button className={styles.primary} disabled={busy} onClick={()=>start(true)}><Play size={18}/>Resume saved mission</button>}<button className={resumeId?styles.secondary:styles.primary} disabled={busy} onClick={()=>start()}>{busy?'Opening mission…':resumeId?'Open selected mission':'Launch mission'}<ArrowRight size={18}/></button></section>
   <aside className={styles.launchPanel}><span className={styles.eyebrow}>YOUR FLIGHT PLAN</span><ol className={styles.flightPlan}><li><b>01</b><span><strong>Show your thinking</strong>Use the game board and explain your choices.</span></li><li><b>02</b><span><strong>Find a useful strategy</strong>Get a hint or study a worked example.</span></li><li><b>03</b><span><strong>Try a fresh situation</strong>Check what you can do independently.</span></li></ol><p className={styles.fine}>Practice evidence helps your teacher plan support. It does not automatically change your mastery rating.</p><Link className={styles.textLink} href="/arcade/missions">Explore all {MISSIONS.length} missions →</Link></aside></div>
  </>:completed?<section className={styles.completion}><span className={styles.completeIcon}><Check size={36}/></span><span className={styles.eyebrow}>MISSION COMPLETE</span><h1>Good thinking travels.</h1><p>Your work and the support you used are saved.</p><div className={styles.summaryStats}><div><strong>{session.xp} XP</strong><span>banked{session.xp<PRACTICE_XP?' · allowance or preview limit':''}</span></div><div><strong>{s!.evidence.filter(e=>e.firstCorrect&&!e.firstAssisted&&!e.review).length} / {s!.evidence.filter(e=>!e.firstAssisted&&!e.review).length}</strong><span>independent first checks</span></div><div><strong>{s!.evidence.filter(e=>e.assisted).length}</strong><span>tasks with support</span></div></div>{session.mode==='challenge'&&<p><Trophy size={18}/> {session.ranked?`Ranked score: ${session.score} / ${session.maxScore}`:'Practice challenge · not ranked'}</p>}{s!.evidence.some(e=>e.review)&&<p>Estimation reasoning is awaiting teacher review.</p>}<div className={styles.evidenceList}>{s!.evidence.map((e,i)=><div key={e.taskId}><strong>{i+1}. {e.code}</strong><span>{e.review?'Teacher review':e.assisted?'With support':e.firstCorrect?'Independent success':'Keep practicing'}</span></div>)}</div><p>Come back tomorrow for a delayed check with new problems.</p><div className={styles.operations}><button className={styles.primary} onClick={reset}><RotateCcw size={17}/>Choose another session</button><Link className={styles.secondary} href={safeReturn}>Return to learning</Link></div></section>:task&&s?<>
   <header className={styles.sessionHeader}><div><span className={styles.eyebrow}>{task.code} / {session.phase}</span><h1 ref={heading} tabIndex={-1}>{task.title}</h1><p>{COMPETENCIES[task.code]}</p></div><div className={styles.sessionTools}><span>{session.index+1} / {SESSION_STEPS}</span><button className={styles.secondary} disabled={busy} onClick={()=>act(s.paused?'resume':'pause')}><Pause size={16}/>{s.paused?'Resume':'Save & pause'}</button></div></header>
   <div className={styles.progress} aria-label={`Task ${session.index+1} of ${SESSION_STEPS}`}>{Array.from({length:SESSION_STEPS},(_,i)=><span key={i} data-done={i<session.index} data-current={i===session.index}/>)}</div>
   {s.paused?<section className={styles.launchPanel}><h2>Mission paused and saved</h2><p>Your answers are retained. Resume whenever you’re ready.</p><button className={styles.primary} disabled={busy} onClick={()=>act('resume')}><Play size={18}/>Resume mission</button><Link href={safeReturn} className={styles.secondary}>Leave mission</Link></section>:<div className={styles.playGrid}>
    <div><MissionBoard key={task.id} task={task} answer={answer} onChange={setAnswer} disabled={busy||canNext} supported={session.phase==='Build the strategy'||!!session.hint}/><section className={styles.support}><h2><Lightbulb size={19}/>Strategy desk</h2><p>{session.hint||'Need a way in? Hints and worked examples are here whenever you need them.'}</p><div className={styles.operations}><button className={styles.secondary} disabled={busy||canNext} onClick={()=>act('hint')}>Show a hint</button><button className={styles.secondary} disabled={busy||canNext} onClick={()=>act('worked')}>Worked example</button></div>{session.strategy&&<details open={session.phase==='Build the strategy'}><summary>Understand the idea</summary><p>{session.strategy.idea}</p><dl>{session.strategy.words.map(w=><div key={w.term}><dt><strong>{w.term}</strong></dt><dd>{w.meaning}</dd></div>)}</dl></details>}{session.worked.length>0&&<ol>{session.worked.map((step,i)=><li key={i}>{step}</li>)}</ol>}{session.mode==='challenge'&&<p className={styles.fine}>{session.ranked?'Help turns this into an unranked practice run.':'This is an unranked practice run.'}</p>}</section></div>
    <section className={styles.taskPanel}><span className={styles.eyebrow}>YOUR MISSION</span><p className={styles.prompt}>{task.prompt}</p><form onSubmit={e=>{e.preventDefault();act('answer')}}><fieldset disabled={busy||canNext}>{task.fields.map(f=><label className={styles.field} key={f.id}>{f.label}{f.unit&&<span className={styles.unit}>{f.unit}</span>}{f.kind==='select'?<select aria-label={f.label} value={answer[f.id]||''} onChange={e=>setAnswer({...answer,[f.id]:e.target.value})}><option value="">Choose…</option>{f.options?.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.id==='reason'?<textarea aria-label={f.label} rows={4} value={answer[f.id]||''} onChange={e=>setAnswer({...answer,[f.id]:e.target.value})}/>:<input aria-label={f.label} autoComplete="off" inputMode={f.kind==='number'?'decimal':'text'} value={answer[f.id]||''} onChange={e=>setAnswer({...answer,[f.id]:e.target.value})}/>}</label>)}</fieldset>{!canNext&&<button className={styles.primary} disabled={busy||s.answers.length>=5} type="submit">{busy?'Saving…':s.checked?'Check again':'Check my work'}<Check size={18}/></button>}</form>
    {s.feedback&&<div role="status" className={s.feedback.correct?styles.feedbackGood:styles.feedback}><strong>{s.feedback.review?'Reasoning check':s.feedback.correct?'That works.':'Let’s work through it.'}</strong><p>{s.feedback.message}</p>{s.answers.length>=5&&!canNext&&<p>Open the worked example, then continue to a fresh task.</p>}</div>}{canNext&&<button className={styles.primary} disabled={busy} onClick={()=>act('next')}>{busy?'Saving…':session.index===5?'Finish & bank XP':'Continue'}<ArrowRight size={18}/></button>}<p className={styles.fine}>Saved after each check. Completion earns up to {PRACTICE_XP} XP within your daily allowance.</p></section>
   </div>}
  </>:null}
  {error&&<div role="alert" className={styles.error}>{error}<button className={styles.secondary} onClick={()=>setError('')}>Dismiss</button></div>}
 </main>;
}
