'use client'
import {useId,useState} from 'react'
import type {Answer,PublicTask} from '@/lib/math-missions/types'
import styles from './missions.module.css'
import InstrumentPanel from './InstrumentPanel'
const n=(a:Answer,k:string,fallback=0)=>Number.isFinite(Number(a[k]))&&a[k]!==''?Number(a[k]):fallback
const fmt=(v:number)=>Number.isFinite(v)?Number(v.toFixed(2)).toString():'—'
export default function MissionBoard({task,answer,onChange,disabled=false,supported=false}:{task:PublicTask;answer:Answer;onChange:(a:Answer)=>void;disabled?:boolean;supported?:boolean}){
 const markerId=useId().replaceAll(':','');
 const d=task.data, [operations,setOperations]=useState<string[]>([]),[run,setRun]=useState(false);
 const set=(key:string,value:string)=>onChange({...answer,[key]:value});
 const slider=(key:string,label:string,min:number,max:number,step:number)=> <label className={styles.slider}>{label}<input aria-label={label} type="range" disabled={disabled} min={min} max={max} step={step} value={n(answer,key,min)} onChange={e=>set(key,e.target.value)}/><output>{answer[key]||'Choose a value'}</output></label>;
 if(task.board==='numberline'){
  const min=Number(d.min),max=Number(d.max),position=n(answer,'position',min),x=55+(position-min)/(max-min)*490;
  return <InstrumentPanel kind={task.board}><div className={styles.boardLabel}>NAVIGATION DECK <span>Value is position</span></div><svg viewBox="0 0 600 280" role="img" aria-label={`Number line from ${min} to ${max}; rover at ${position}.`}>
   <rect x="30" y="116" width="540" height="119" rx="16" fill="#071321" stroke="#496178"/>
   <path d="M55 155H545" stroke="#8ecbff" strokeWidth="28" opacity=".06"/>
   <path d="M55 155H545" stroke="#8da4ba" strokeWidth="2"/>
   {Array.from({length:51},(_,i)=><path key={i} d={`M${55+i*9.8} 155v${i%5===0?25:10}`} stroke="#90a6bc" opacity={i%5===0?1:.4}/>)}
   {Array.from({length:11},(_,i)=><text key={i} x={55+i*49} y="207" textAnchor="middle" className={styles.scaleLabel}>{fmt(min+(max-min)*i/10)}</text>)}
   {supported&&Array.from({length:101},(_,i)=><path key={i} d={`M${55+i*4.9} 155v6`} stroke="#bdd3e5" opacity=".5"/>)}
   <g style={{transform:`translate(${Math.min(545,Math.max(55,x))}px,155px)`}} className={styles.cursor}>
    <circle r="25" fill="var(--mission-color)" opacity=".08"/><path d="M-20 -8h40l-5 -12h-26z" fill="var(--mission-color)"/><rect x="-23" y="-8" width="46" height="14" rx="5" fill="#17384a" stroke="var(--mission-color)" strokeWidth="2"/><circle cx="-14" cy="9" r="7" fill="#091726" stroke="#bddbea" strokeWidth="2"/><circle cx="14" cy="9" r="7" fill="#091726" stroke="#bddbea" strokeWidth="2"/><path d="M-8 -17h16" stroke="#082332" strokeWidth="3"/>
    <path d="M0 -22v-9" stroke="var(--mission-color)" strokeWidth="2"/>
    <rect x="-35" y="-60" width="70" height="28" rx="7" fill="var(--mission-color)"/>
    <text y="-41" textAnchor="middle" style={{fill:'#08202c',fontWeight:700}}>{fmt(position)}</text>
   </g>
   <text x="300" y="43" textAnchor="middle" className={styles.svgHeadline}>{d.numerator?`${d.numerator}/${d.denominator}`:String(d.target)}</text><text x="300" y="69" textAnchor="middle">TARGET LANDING</text>
  </svg>{slider('position','Pilot the rover',min,max,task.code==='NS2'?.005:.01)}<p className={styles.boardNote}>Use the slider, arrow keys, or enter the exact position below.</p></InstrumentPanel>;
 }
 if(task.board==='reactor'){
  const ratio=task.code==='PR1',input=n(answer,ratio?'input':'output'),factor=ratio?Number(d.target)/Number(d.b):Number(d.factor),capacity=ratio?Math.max(Number(d.target),Number(d.a)*factor*2):Math.max(16,factor**Number(d.power)*2),fill=(value:number)=>Math.max(0,Math.min(100,value/capacity*100));
  return <InstrumentPanel kind={task.board}><div className={styles.boardLabel}>REACTOR CONTROL <span>{ratio?'Maintain the mix':String(d.relation)}</span></div><div className={styles.reactor}>
   <div><span>{ratio?'Parts A':'Input factor'}</span><div className={styles.chamber}><i style={{transform:`scaleY(${fill(ratio?input:factor)/100})`}}/><strong>{ratio?fmt(input):fmt(factor)}</strong></div></div>
   <div className={styles.reactorLink}><span>{ratio?`${d.a} : ${d.b}`:String(d.relation)}</span><b key={String(input)} className={styles.reactionPulse}>⇄</b><small>preserve the model</small></div>
   <div><span>{ratio?'Parts B':'Predicted output'}</span><div className={styles.chamber}><i style={{transform:`scaleY(${fill(ratio?Number(d.target):input)/100})`}}/><strong>{ratio?String(d.target):fmt(input)}</strong></div></div>
  </div><p className={styles.scaleCaption}>Shared column scale: 0–{fmt(capacity)} {ratio?'parts':'×'}</p>{slider(ratio?'input':'output',ratio?'Tune parts A':'Tune the output factor',0,ratio?Number(d.a)*factor*2:Math.max(16,factor**Number(d.power)*2),ratio?1:.001)}<button className={styles.secondary} disabled={disabled} onClick={()=>setRun(v=>!v)}>{run?'Reset reactor':'Run prediction'}</button>{run&&<p role="status">Your prediction is set to {fmt(input)}. Check the mission to test the mathematics.</p>}</InstrumentPanel>;
 }
 if(task.board==='courier')return <InstrumentPanel kind={task.board}><div className={styles.boardLabel}>CONVERSION DEPOT <span>Same quantity. New label.</span></div><div className={styles.courierRoute}><div className={styles.parcel}><span>INCOMING</span><strong>{d.scientific?`${d.a} × 10^${d.e}`:`${d.value} ${d.from}`}</strong></div><span className={styles.deliveryArrow}>→</span><div className={styles.parcel} key={`delivery-${answer.result}-${answer.mantissa}-${answer.exponent}`}><span>YOUR DELIVERY</span><strong>{d.scientific?`${answer.mantissa||'?'} × 10^${answer.exponent||'?'}`:`${answer.result||'?'} ${d.to}`}</strong></div></div>{d.scientific?slider('exponent','Move the power of ten',-12,12,1):<div className={styles.bridges}>{task.fields.filter(f=>f.kind==='select').map(f=><fieldset key={f.id}><legend>{f.label}</legend>{f.options?.map(o=><button key={o.value} disabled={disabled} className={answer[f.id]===o.value?styles.selected:styles.secondary} onClick={()=>set(f.id,o.value)}>{o.label}</button>)}</fieldset>)}</div>}<p className={styles.boardNote}>{d.scientific?'A shift in the coefficient needs an equal and opposite shift in the power.':'Build the route from left to right. A unit cancels only when it appears once above and once below.'}</p></InstrumentPanel>;
 if(task.board==='precision'){
  if(d.estimation){const estimate=n(answer,'space')>0?n(answer,'area')/n(answer,'space'):0;return <InstrumentPanel kind={task.board}><div className={styles.boardLabel}>OBSERVATION PLAN <span>Assumptions matter</span></div><svg viewBox="0 0 600 250" role="img" aria-label={`Hall floor plan ${d.length} metres by ${d.width} metres.`}><rect x="120" y="35" width="360" height="150" rx="8" fill="var(--mission-color)" opacity=".14" stroke="currentColor"/>{Array.from({length:36},(_,i)=><circle key={i} cx={145+i%9*39} cy={60+Math.floor(i/9)*34} r="6" fill="currentColor" opacity=".5"/>)}<text x="300" y="221" textAnchor="middle">{d.length} m</text><text x="68" y="112" textAnchor="middle">{d.width} m</text></svg>{supported&&<p className={styles.boardReadout}>Your assumptions imply approximately {fmt(estimate)} people.</p>}<p className={styles.boardNote}>Explain obstructions, personal space and uncertainty. The teacher reviews your reasoning.</p></InstrumentPanel>}
  const v=Number(d.measurement),min=Number(d.min),max=Number(d.max);return <InstrumentPanel kind={task.board}><div className={styles.boardLabel}>MEASUREMENT BENCH <span>Resolution: 0.1 cm</span></div><svg viewBox="0 0 600 260" role="img" aria-label={`Instrument reading ${v.toFixed(1)} centimetres, resolution one tenth centimetre.`}><rect x="45" y="116" width="510" height="70" rx="6" fill="var(--mission-color)" opacity=".2"/>{Array.from({length:Math.round((max-min)*10)+1},(_,i)=>{const x=45+i/(10*(max-min))*510;return <g key={i}><path d={`M${x} 116v${i%10?17:32}`} stroke="currentColor"/>{i%10===0&&<text x={x} y="170" textAnchor="middle">{min+i/10}</text>}</g>})}<path d={`M${45+(v-min)/(max-min)*510} 55v55l-8 -12m8 12l8 -12`} stroke="var(--mission-color)" strokeWidth="4" fill="none" className={styles.measurePointer}/><text x="300" y="220" textAnchor="middle">centimetres</text></svg><p className={styles.boardNote}>Read the instrument first. Round the calculated result only at the end.</p></InstrumentPanel>;
 }
 if(task.board==='balance'){
  if(d.substitution)return <InstrumentPanel kind={task.board}><div className={styles.boardLabel}>MACHINE TEST <span>v = u + at</span></div><div className={styles.equation}>({d.u}) + ({d.a}) × ({d.t})</div><div className={styles.machineSlots} key={answer.expression}><span>u<br/><strong>{d.u} m/s</strong></span><span>a<br/><strong>{d.a} m/s²</strong></span><span>t<br/><strong>{d.t} s</strong></span></div><button className={styles.secondary} disabled={disabled} onClick={()=>set('expression',`(${d.u})+(${d.a})*(${d.t})`)}>Place the values in the expression</button><p className={styles.boardNote}>Keep the parentheses when a value is negative.</p></InstrumentPanel>;
  const sub=operations.includes('subtract'),div=operations.includes('divide');const left=sub?div?`(${d.c} − ${d.b}) / ${d.a}`:`${d.c} − ${d.b}`:div?`${d.c}/${d.a}`:String(d.c);const right=sub?div?String(d.x):`${d.a}·${d.x}`:div?`${d.b}/${d.a} + ${d.x}`:`${d.b} + ${d.a}·${d.x}`;
  return <InstrumentPanel kind={task.board}><div className={styles.boardLabel}>EQUALITY WORKBENCH <span>Isolate {d.x}</span></div><div className={styles.balance} key={operations.join("-")}><div>{left}</div><b>=</b><div>{right}</div></div><div className={styles.balanceBeam}/><div className={styles.operations}><button disabled={disabled||sub} onClick={()=>{setOperations([...operations,'subtract']);if(div)set('formula',`(${d.c}-${d.b})/${d.a}`)}}>Subtract {div?`${d.b}/${d.a}`:d.b} from both sides</button><button disabled={disabled||div} onClick={()=>{setOperations([...operations,'divide']);if(sub)set('formula',`(${d.c}-${d.b})/${d.a}`)}}>Divide both sides by {d.a}</button><button className={styles.secondary} disabled={disabled||!operations.length} onClick={()=>{setOperations(operations.slice(0,-1));set('formula','')}}>Undo</button></div><p className={styles.boardNote}>Equivalent routes are accepted. You can also type the final expression below.</p></InstrumentPanel>;
 }
 if(task.board==='motion'){
  if(d.slopeTask){const start=Number(d.start),end=Number(d.end),duration=Number(d.duration),lo=Math.min(0,start,end)-2,hi=Math.max(0,start,end)+2,y=(v:number)=>230-(v-lo)/(hi-lo)*190;return <InstrumentPanel kind={task.board}><div className={styles.boardLabel}>POSITION SENSOR <span>Read the rate of change</span></div><svg viewBox="0 0 600 300" role="img" aria-label={`Position-time graph from (0 s, ${start} m) to (${duration} s, ${end} m).`}><path d="M70 30V240H535" stroke="currentColor" fill="none"/><path d={`M70 ${y(start)}L520 ${y(end)}`} stroke="var(--mission-color)" strokeWidth="4" fill="none" pathLength="1" className={styles.drawTrace}/>{[start,end].map((v,i)=><g key={i}><circle cx={i?520:70} cy={y(v)} r="6" fill="var(--mission-color)"/><text x={i?510:85} y={y(v)-12} textAnchor={i?'end':'start'}>{v} m</text></g>)}<text x="70" y="265">0</text><text x="520" y="265">{duration}</text><text x="270" y="290">time (s)</text><text x="5" y="20">position (m)</text></svg>{supported&&<p className={styles.boardReadout}>Change in position: {end-start} m · change in time: {duration} s</p>}</InstrumentPanel>;}
  if(d.fit){const xs=d.xs as number[],ys=d.ys as number[],axis=answer.axis||'x',transformed=xs.map(x=>axis==='x²'?x*x:axis==='1/x'?1/x:x),maxX=Math.max(...transformed),maxY=Math.max(...ys)*1.15;
   return <InstrumentPanel kind={task.board}><div className={styles.boardLabel}>SENSOR ANALYSIS <span>Choose axes. Find the rate.</span></div><svg viewBox="0 0 600 290" role="img" aria-label={`Scatter plot of y against ${axis}. Data table is below.`}><path d="M65 25V235H550" fill="none" stroke="currentColor"/>{transformed.map((x,i)=><circle key={i} cx={65+x/maxX*450} cy={235-ys[i]/maxY*190} r="7" fill="var(--mission-color)" className={styles.sensorPoint} style={{animationDelay:`${i*60}ms`}}/>)}{answer.slope&&answer.intercept&&<line x1="65" y1={235-n(answer,'intercept')/maxY*190} x2="515" y2={235-(n(answer,'slope')*maxX+n(answer,'intercept'))/maxY*190} stroke="var(--mission-color)" strokeWidth="2"/>}<text x="300" y="275" textAnchor="middle">{axis} ({axis==='x²'?'s²':axis==='1/x'?'1/s':'s'})</text><text x="8" y="24">y (m)</text>{[0,.5,1].map(f=><g key={f}><text x={65+f*450} y="253" textAnchor="middle">{fmt(maxX*f)}</text><text x="55" y={239-f*190} textAnchor="end">{fmt(maxY*f)}</text></g>)}</svg><table className={styles.dataTable}><caption>Sensor readings</caption><thead><tr><th>x (s)</th>{xs.map((x,i)=><th key={i}>{x}</th>)}</tr></thead><tbody><tr><th>y (m)</th>{ys.map((y,i)=><td key={i}>{y}</td>)}</tr></tbody></table><button className={styles.secondary} disabled={disabled} onClick={()=>{const meanX=transformed.reduce((a,b)=>a+b,0)/transformed.length,meanY=ys.reduce((a,b)=>a+b,0)/ys.length,m=transformed.reduce((sum,x,i)=>sum+(x-meanX)*(ys[i]-meanY),0)/transformed.reduce((sum,x)=>sum+(x-meanX)**2,0);onChange({...answer,slope:m.toFixed(4),intercept:(meanY-m*meanX).toFixed(4)})}}>Fit selected axes</button><div className={styles.operations}>{['x','x²','1/x'].map(x=><button className={axis===x?styles.selected:styles.secondary} disabled={disabled} key={x} onClick={()=>set('axis',x)}>{x}</button>)}</div></InstrumentPanel>;
  }
  const v=Number(d.v),duration=Number(d.duration),t=Number(d.returnTime),rv=n(answer,'returnVelocity'),velocityScale=110/Math.max(15,Math.abs(v)),y=(a:number)=>150-a*velocityScale,split=65+duration/(duration+t)*450,end=duration*v+rv*t;
  return <InstrumentPanel kind={task.board}><div className={styles.boardLabel}>MOTION CONTROL <span>Velocity → signed area</span></div><svg viewBox="0 0 600 320" role="img" aria-label={`Velocity-time graph: ${v} metres per second for ${duration} seconds, then ${rv} for ${t} seconds. Predicted displacement ${fmt(end)} metres.`}><path d="M65 20V275M65 150H535" stroke="currentColor" fill="none"/><rect x="65" y={Math.min(150,y(v))} width={split-65} height={Math.abs(v)*velocityScale} fill="var(--mission-color)" opacity=".25"/><rect x={split} y={Math.min(150,y(rv))} width={515-split} height={Math.abs(rv)*velocityScale} fill="#f9adba" opacity=".3"/><path d={`M65 ${y(v)}H${split}V${y(rv)}H515`} stroke="var(--mission-color)" strokeWidth="3" fill="none" pathLength="1" className={styles.drawTrace} key={rv}/><text x="10" y="18">v (m/s)</text><text x="300" y="305">time (s)</text>{[0,duration,duration+t].map((a,i)=><text key={i} x={65+a/(duration+t)*450} y="171" textAnchor="middle">{a}</text>)}{[-10,-5,0,5,10].map(a=><text key={a} x="55" y={y(a)+4} textAnchor="end">{a}</text>)}</svg>{slider('returnVelocity','Set the return velocity',-15,15,.01)}{supported&&<p className={styles.boardReadout}>Predicted displacement: {fmt(end)} m</p>}</InstrumentPanel>;
 }
 const vx=n(answer,'x'),vy=n(answer,'y'),wind=Number(d.wind),rx=vx+wind,extent=Math.ceil(Math.max(25,Math.abs(rx),Math.abs(vx),Math.abs(vy))/10)*10,scale=125/extent;
 return <InstrumentPanel kind={task.board}><div className={styles.boardLabel}>RESCUE FLIGHT PLAN <span>Thrust + wind = resultant</span></div><svg viewBox="0 0 600 350" role="img" aria-label={`Coordinate plane. Your thrust is (${vx}, ${vy}), wind is (${wind}, 0), predicted resultant (${rx}, ${vy}) metres per second.`}><defs><marker id={markerId} viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 0L10 5L0 10z" fill="context-stroke"/></marker></defs>{[-extent,-extent/2,0,extent/2,extent].map(a=><g key={a}><path d={`M${300+a*scale} 30V315M150 ${175-a*scale}H450`} stroke="currentColor" opacity=".12"/><text x={300+a*scale} y="333" textAnchor="middle">{a}</text><text x="130" y={180-a*scale}>{a}</text></g>)}<path d="M145 175H465M300 315V25" stroke="currentColor" opacity=".7"/><path d={`M300 175L${300+vx*scale} ${175-vy*scale}`} stroke="var(--mission-color)" strokeWidth="4" markerEnd={`url(#${markerId})`}/><path d={`M${300+vx*scale} ${175-vy*scale}h${wind*scale}`} stroke="#ffcb80" strokeWidth="3" markerEnd={`url(#${markerId})`}/><path d={`M300 175L${300+rx*scale} ${175-vy*scale}`} stroke="#fff" strokeWidth="2" strokeDasharray="5 5" className={styles.vectorFlow} key={`${rx}-${vy}`}/><text x="480" y="180">+x</text><text x="310" y="25">+y</text></svg><div className={styles.liveReadout}><span>RESULTANT VELOCITY</span><strong>({fmt(rx)}, {fmt(vy)}) <small>m/s</small></strong></div><div className={styles.vectorLegend}><span>● Thrust</span><span>● Wind</span><span>┄ Resultant</span></div><div className={styles.machineSlots}><span>Thrust<strong>{d.speed} m/s</strong></span><span>Angle<strong>{d.angle}° from {d.reference}</strong></span><span>Wind<strong>{wind} m/s in x</strong></span></div>{slider('x','Aim the thrust x component',-25,25,.01)}{slider('y','Aim the thrust y component',-25,25,.01)}</InstrumentPanel>;
}
