'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {COMPETENCIES,MISSIONS,missionForCode} from '@/lib/math-missions/catalog'
import type {Session} from '@/lib/math-missions/types'
import type {MissionAssignment} from './MissionHub'
import styles from './missions.module.css'
type ReviewedSession=Session&{review_note:string|null;reviewed_at:string|null}
export default function TeacherMissions(){
 const [students,setStudents]=useState<{id:string;name:string}[]>([]),[student,setStudent]=useState(''),[code,setCode]=useState('NS1'),[due,setDue]=useState(''),[sessions,setSessions]=useState<ReviewedSession[]>([]),[assignments,setAssignments]=useState<MissionAssignment[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reload,setReload]=useState(0),[notes,setNotes]=useState<Record<string,string>>({}),[notice,setNotice]=useState('');
 useEffect(()=>{let live=true;fetch('/api/mastery/roster').then(async r=>{if(!r.ok)throw Error('Could not load roster.');return r.json()}).then(d=>{if(live)setStudents((d.students||[]).map((s:{id?:string;userId?:string;name?:string;studentId?:string})=>({id:s.id||s.userId||s.studentId||'',name:s.name||'Student'})))}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[]);
 useEffect(()=>{let live=true;fetch('/api/math-missions/teacher'+(student?'?user_id='+student:'')).then(async r=>{if(!r.ok)throw Error('Could not load mission evidence.');return r.json()}).then(d=>{if(live){setSessions(d.sessions);setAssignments(d.assignments);setError('')}}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[student,reload]);
 async function send(body:Record<string,unknown>){setBusy(true);setNotice('');try{const r=await fetch('/api/math-missions/teacher',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error);setNotice(body.action==='assign'?'Mission assigned.':body.action==='review'?'Feedback saved.':'Assignment cancelled.');setReload(n=>n+1)}catch(e){setError(e instanceof Error?e.message:'Could not save.')}finally{setBusy(false)}}
 const name=(id:string)=>students.find(s=>s.id===id)?.name||'Student';
 return <main className={styles.shell}><nav className={styles.topbar}><Link href="/admin/math-spine">← Math teaching</Link><Link href="/arcade/missions">Preview missions</Link></nav><header className={styles.hero}><span className={styles.eyebrow}>TEACHER WORKSPACE</span><h1>See the thinking.<br/>Choose the next step.</h1><p>Assign a skill, inspect independent and assisted work, and leave formative feedback. These records do not automatically change competency ratings.</p></header><section className={styles.launchPanel}><h2>Assign a math mission</h2><div className={styles.teacherTools}><label className={styles.field}>Student<select aria-label="Student" value={student} onChange={e=>setStudent(e.target.value)}><option value="">All students · choose one to assign</option>{students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className={styles.field}>Skill<select aria-label="Skill" value={code} onChange={e=>setCode(e.target.value)}>{Object.entries(COMPETENCIES).map(([c,label])=><option key={c} value={c}>{c} · {label}</option>)}</select></label><label className={styles.field}>Due date (optional)<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label></div><p>{missionForCode(code)?.name} · six guided tasks · up to 3 XP within the daily allowance</p><button className={styles.primary} disabled={busy||!student} onClick={()=>send({action:'assign',userId:student,code,mission:missionForCode(code)!.slug,dueAt:due?new Date(due+'T23:59:00').toISOString():null})}>Assign mission</button></section>
 {notice&&<p role="status">{notice}</p>}{error&&<p role="alert" className={styles.error}>{error}<button onClick={()=>setReload(n=>n+1)}>Retry</button></p>}
 <h2 className={styles.sectionTitle}>Assignments</h2>{assignments.length===0&&<p>No assignments in this view yet.</p>}{assignments.map(a=><div className={styles.reviewCard} key={a.id}><strong>{name(a.user_id)} · {a.title}</strong><p>{a.completed_at?'Completed':a.due_at?'Due '+new Date(a.due_at).toLocaleDateString():'Ready to practice'}</p>{!a.completed_at&&<button className={styles.secondary} disabled={busy} onClick={()=>send({action:'cancel',id:a.id})}>Cancel assignment</button>}</div>)}
 <h2 className={styles.sectionTitle}>Learning evidence</h2><p>Showing the latest {sessions.length} completed sessions{sessions.length===200?' (200-session limit; choose a student to narrow the view)':''}.</p>{sessions.map(s=>{const evidence=s.state.evidence,independent=evidence.filter(e=>!e.firstAssisted&&!e.review),errors=[...new Set(evidence.flatMap(e=>e.errorCodes))];return <details className={styles.reviewCard} key={s.id}><summary>{name(s.user_id)} · {MISSIONS.find(m=>m.slug===s.mission)?.name} · {s.mode==='retention'?'Delayed check':s.mode==='challenge'?'Challenge':'Guided practice'}<br/>{independent.filter(e=>e.firstCorrect).length}/{independent.length} independent first checks · {evidence.filter(e=>e.assisted).length} with support</summary><p>{s.completed_at&&new Date(s.completed_at).toLocaleString()} · {s.xp} XP · {evidence.filter(e=>e.review).length} responses need reasoning review</p>{errors.length>0&&<p>Observed error patterns (not diagnoses): {errors.join(', ')}</p>}{evidence.map((e,i)=><section key={e.taskId} className={styles.reviewCard}><h3>Task {i+1} · {e.code} · {e.phase}</h3><p>{e.prompt}</p><p>{e.review?'Review the assumptions, model, range, and arithmetic.':e.assisted?'Assisted work':e.firstCorrect?'Independent first-attempt success':'Independent first attempt needs attention'} · {e.hints} help requests</p>{e.answers.map((a,j)=><details key={j} open={j===0}><summary>Attempt {j+1}</summary><dl>{Object.entries(a).map(([key,value])=><div key={key} style={{display:'contents'}}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></details>)}</section>)}<label className={styles.field}>Formative feedback<textarea value={notes[s.id]??s.review_note??''} onChange={e=>setNotes({...notes,[s.id]:e.target.value})}/></label><button className={styles.primary} disabled={busy||!(notes[s.id]??s.review_note??'').trim()} onClick={()=>send({action:'review',id:s.id,note:notes[s.id]??s.review_note})}>Save feedback</button>{s.reviewed_at&&<p>Reviewed {new Date(s.reviewed_at).toLocaleDateString()}</p>}</details>})}</main>;
}
