'use client'
import { useEffect,useState } from 'react'
import Link from 'next/link'
import { LanguageProfileProvider,useLanguageProfile } from '@/components/lessons/LanguageProfileProvider'
import VocabTaskCards from '@/components/vocabulary/VocabTaskCards'
import { languageCode } from '@/lib/vocab-language'
import type { VocabTask,VocabResult } from '@/lib/vocab-learning'
interface Item {id:string;termId:string;prompt:string;icon?:string;definitionEs?:string;translations?:Record<string,{definition?:string}>;options:{id:string;label:string}[]}
const field='min-h-11 rounded-lg border border-border bg-background p-3'
async function api(body:unknown){const r=await fetch('/api/vocab/checks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error??'Unable to save');return d}
function Work(){
 const [id,setId]=useState(''),[task,setTask]=useState<VocabTask|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const [check,setCheck]=useState(''),[items,setItems]=useState<Item[]>([]),[responses,setResponses]=useState<Record<string,string>>({}),[supports,setSupports]=useState<Record<string,string[]>>({}),[results,setResults]=useState<VocabResult[]|null>(null),[language,setLanguage]=useState('')
 const {profile}=useLanguageProfile()
 useEffect(()=>{const taskId=new URLSearchParams(location.search).get('task_id')??'';setId(taskId);if(!taskId)return;fetch(`/api/vocab/checks?task_id=${taskId}`).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);return d}).then(d=>setTask(d.task)).catch(e=>setError(e.message))},[])
 useEffect(()=>{if(profile?.homeLang)setLanguage(languageCode(profile.homeLang))},[profile])
 const run=async(f:()=>Promise<void>)=>{setBusy(true);setError('');try{await f()}catch(e){setError(e instanceof Error?e.message:'Unable to save')}finally{setBusy(false)}}
 const mark=(item:string,s:string)=>setSupports(p=>({...p,[item]:[...new Set([...(p[item]??[]),s])]}))
 const start=()=>run(async()=>{const d=await api({task_id:id});setCheck(d.check_id);setItems(d.items);setResponses({});setSupports({});setResults(null)})
 const submit=()=>run(async()=>{const d=await api({task_id:id,check_id:check,responses:items.map(i=>({id:i.id,response:responses[i.id]??'',supports:supports[i.id]??[]}))});setResults(d.result)})
 const languages=[...new Set(['es',...(task?.words??[]).flatMap(w=>Object.keys(w.translations??{}))])]
 return <div className="mx-auto max-w-3xl p-4 md:p-6 space-y-5"><Link href="/home" className="underline">Home</Link><h1 className="text-2xl font-bold">{task?.title??'Vocabulary assignments'}</h1>{error&&<p role="alert" className="text-destructive">{error}</p>}{!id?<VocabTaskCards/>:!task?<p>Loading assignment…</p>:<>
 <p>{task.note}</p><p className="text-sm text-muted-foreground">{task.term_ids.length} words · {task.min_checks} checks per word · {task.threshold}% recent accuracy{task.due_on?` · due ${task.due_on}`:''}. These checks show word learning. Your teacher rates your physics understanding separately.</p>
 <label>Translation language <select className={field} value={language} onChange={e=>setLanguage(e.target.value)}><option value="">Choose language</option>{languages.map(l=><option key={l} value={l}>{({es:'Spanish',pt:'Portuguese',ht:'Haitian Creole',fr:'French',ar:'Arabic',zh:'Chinese',vi:'Vietnamese'} as Record<string,string>)[l]??l}</option>)}</select></label>
 {!check&&<><div className="grid gap-3 md:grid-cols-2">{task.words.map(w=><article className="rounded-xl border border-border p-4" key={w.id}><h2 className="font-bold">{w.icon} {w.term}</h2><p>{w.definition}</p>{language&&<p className="text-muted-foreground text-sm">{w.translations?.[language]?.definition||(language==='es'?w.definition_es:'')}</p>}{w.example&&<p className="italic text-sm mt-2">{w.example}</p>}<p className="text-xs text-muted-foreground mt-2">{w.tier===1?'Everyday word':w.tier===2?'Academic word':w.tier===3?'Physics word':''}</p></article>)}</div><div className="flex flex-wrap gap-2">{['matching','quiz-bowl','word-shoot','hangman','crossword'].map(g=><Link className={field} key={g} href={`/vocabulary/${g}?task_id=${task.id}`}>Practice · {g.replaceAll('-',' ')}</Link>)}</div><button className={`${field} bg-primary text-primary-foreground`} disabled={busy||!task.active} onClick={start}>Start untimed {task.check_mode==='recognition'?'recognition':'recall / spelling'} check</button></>}
 {check&&!results&&<><p className="text-sm">Answer every word, then submit once. Picture, translated clue, and spoken English clue are available whenever you need them.</p>{items.map((i,index)=>{const translation=i.translations?.[language]?.definition||(language==='es'?i.definitionEs:'');return <section className="rounded-xl border border-border p-4 space-y-3" key={i.id}><h2 className="font-semibold">{index+1}. {i.prompt}</h2><div className="flex gap-2 flex-wrap">{i.icon&&<button className={field} onClick={()=>mark(i.id,'picture')}>Picture {supports[i.id]?.includes('picture')?i.icon:''}</button>}{translation&&<button className={field} onClick={()=>mark(i.id,'translation')}>Translated clue</button>}<button className={field} onClick={()=>{if('speechSynthesis' in window){mark(i.id,'audio');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(i.prompt);u.lang='en-US';u.rate=.85;speechSynthesis.speak(u)}}}>Hear clue</button></div>{translation&&supports[i.id]?.includes('translation')&&<p>{translation}</p>}{i.options.length?<fieldset><legend className="sr-only">Choose the word for question {index+1}</legend><div className="grid gap-2 sm:grid-cols-2">{i.options.map(o=><label key={o.id} className={`${field} flex items-center gap-2 cursor-pointer`}><input type="radio" name={i.id} checked={responses[i.id]===o.id} onChange={()=>setResponses(p=>({...p,[i.id]:o.id}))}/>{o.label}</label>)}</div></fieldset>:<input aria-label={`Word for question ${index+1}`} className={`${field} w-full`} maxLength={300} value={responses[i.id]??''} onChange={e=>setResponses(p=>({...p,[i.id]:e.target.value}))} autoComplete="off"/>}</section>})}<button className={`${field} bg-primary text-primary-foreground`} disabled={busy||items.some(i=>!responses[i.id]?.trim())} onClick={submit}>{busy?'Saving answers…':'Submit check'}</button><p className="text-sm text-muted-foreground">If saving fails, keep this page open and retry. Your answers stay here.</p></>}
 {results&&<section className="rounded-xl border border-border p-4 space-y-3"><h2 className="text-lg font-bold">Check saved · {results.filter(r=>r.correct).length}/{results.length} correct</h2>{results.map(r=><p key={r.term_id}>{r.correct?'✓':'Review'} · <strong>{task.words.find(w=>w.id===r.term_id)?.term}</strong> — {task.words.find(w=>w.id===r.term_id)?.definition}</p>)}<p className="text-sm">Practice missed words, then try another check. Come back on another day to see what you remember.</p><button className={field} onClick={()=>{setCheck('');setResults(null)}}>Review the words</button><Link className={`${field} inline-block ml-2`} href="/home">See assignment progress</Link></section>}
 </>}</div>
}
export default function VocabWorkPage(){return <LanguageProfileProvider><Work/></LanguageProfileProvider>}
