'use client'
import { useEffect, useRef, useState } from 'react'
import Link from 'next/link'
import { QUIZ_FORMATS } from '@/lib/vocab-quiz'
import type { VocabTask,VocabResult } from '@/lib/vocab-learning'
interface Item {id:string;prompt:string;options:{id:string;label:string}[]}
const field='min-h-11 rounded-lg border border-border bg-background p-3'
export default function VocabQuizWork({task}:{task:VocabTask}){
 const [items,setItems]=useState<Item[]>([]),[check,setCheck]=useState(''),[responses,setResponses]=useState<Record<string,string>>({}),[result,setResult]=useState<VocabResult[]|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[round,setRound]=useState(0)
 const saving=useRef(false),format=QUIZ_FORMATS.find(f=>f.id===task.quiz_format),game=task.quiz_format==='quiz_game',manual=task.quiz_format==='definition'||task.quiz_format==='sentence'
 useEffect(()=>{if(check&&!result){try{sessionStorage.setItem('vocab-quiz:'+check,JSON.stringify(responses))}catch{/* Answers stay in memory if storage unavailable. */}}},[check,responses,result])
 const request=async(body:unknown)=>{const r=await fetch('/api/vocab/checks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error??'Could not save quiz');return d}
 const run=async(action:()=>Promise<void>)=>{if(saving.current)return;saving.current=true;setBusy(true);setError('');try{await action()}catch(e){setError(e instanceof Error?e.message:'Unable to save')}finally{setBusy(false);saving.current=false}}
 const start=()=>run(async()=>{const d=await request({task_id:task.id});setCheck(d.check_id);if(d.completed){setResult(d.result);return}setItems(d.items);try{const saved=JSON.parse(sessionStorage.getItem('vocab-quiz:'+d.check_id)??'{}');setResponses(saved&&typeof saved==='object'&&!Array.isArray(saved)?saved:{})}catch{setResponses({})}})
 const submit=()=>run(async()=>{const d=await request({task_id:task.id,check_id:check,responses:items.map(i=>({id:i.id,response:responses[i.id]??'',supports:[]}))});setResult(d.result);try{sessionStorage.removeItem('vocab-quiz:'+check)}catch{}})
 const shown=game?items.slice(round,round+1):items
 return <section className="space-y-4"><p className="font-semibold">Vocabulary quiz · {format?.label}</p><p>{task.note}</p><p>{format?.description}</p><p className="text-sm text-muted-foreground">{task.term_ids.length} questions · One submitted attempt · {task.threshold}% score goal{task.due_on?` · Due ${task.due_on}`:''}. Untimed. {manual?'Your teacher reviews the meaning of your answer.':'Each correct answer earns one point; speed does not affect your score.'} You can review and change answers before final submission.</p>{error&&<p role="alert" className="text-destructive">{error}</p>}
 {!check&&<button className={`${field} bg-primary text-primary-foreground`} disabled={busy||!task.active} onClick={start}>Start / resume quiz</button>}
 {check&&!result&&<>{game&&<div className="rounded-xl bg-muted p-4"><strong>Round {round+1} of {items.length}</strong><progress className="mt-2 block w-full" value={items.filter(i=>responses[i.id]?.trim()).length} max={items.length} aria-label="Quiz questions answered"/><p className="text-sm">Choose an answer, then move to the next round. Results are revealed after you submit the whole quiz.</p></div>}
 {task.quiz_format==='matching'&&<p>Match every definition to a word. Use each word exactly once.</p>}
 {shown.map((i,offset)=>{const n=game?round+1:offset+1;return <section key={i.id} className="rounded-xl border border-border p-4 space-y-3"><h2 className="font-semibold">{n}. {i.prompt}</h2>{task.quiz_format==='matching'?<select className={`${field} w-full`} aria-label={`Match for question ${n}`} value={responses[i.id]??''} onChange={e=>setResponses(p=>({...p,[i.id]:e.target.value}))}><option value="">Choose a word</option>{i.options.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select>:i.options.length?<fieldset><legend className="sr-only">Answer question {n}</legend><div className="grid gap-2 sm:grid-cols-2">{i.options.map(o=><label className={`${field} flex gap-2 items-center`} key={o.id}><input type="radio" name={i.id} checked={responses[i.id]===o.id} onChange={()=>setResponses(p=>({...p,[i.id]:o.id}))}/>{o.label}</label>)}</div></fieldset>:manual?<><p className="text-sm text-muted-foreground">{task.quiz_format==='definition'?'Explain the essential meaning; a copied word or circular definition is not enough.':'Use the assigned word in context so a reader can tell what it means. A sentence that merely says you learned the word is not enough.'}</p><textarea className={`${field} w-full`} rows={3} aria-label={`Answer for question ${n}`} maxLength={2000} value={responses[i.id]??''} onChange={e=>setResponses(p=>({...p,[i.id]:e.target.value}))}/></>:<input className={`${field} w-full`} aria-label={`Word for question ${n}`} maxLength={300} autoComplete="off" value={responses[i.id]??''} onChange={e=>setResponses(p=>({...p,[i.id]:e.target.value}))}/>}</section>})}
 {game&&<div className="flex gap-3"><button className={field} disabled={round===0} onClick={()=>setRound(r=>r-1)}>Previous round</button><button className={field} disabled={round===items.length-1||!responses[items[round]?.id]?.trim()} onClick={()=>setRound(r=>r+1)}>Next round</button></div>}
 <button className={`${field} bg-primary text-primary-foreground`} disabled={busy||items.some(i=>!responses[i.id]?.trim())} onClick={submit}>{busy?'Saving…':'Submit final quiz'}</button><p className="text-sm text-muted-foreground">Answers are final after submission. If saving fails, retry; this cannot create a second attempt.</p></>}
 {result&&<div className="rounded-xl border border-border p-4 space-y-3"><h2 className="text-lg font-semibold">{result.some(r=>r.correct===null)?'Quiz submitted · awaiting teacher review':`Quiz scored · ${result.filter(r=>r.correct).length}/${result.length} correct`}</h2>{!result.some(r=>r.correct===null)&&result.map(r=><div key={r.term_id}><strong>{r.term}: {r.correct?'Correct':'Review'}</strong><p>{r.definition}</p>{r.feedback&&<p>Teacher feedback: {r.feedback}</p>}</div>)}<p>Your submitted attempt is saved. A low score does not create an extra attempt.</p><Link className="inline-flex min-h-11 items-center underline" href="/home">Back to assignments</Link></div>}
 </section>
}
