'use client'
import { useState } from 'react'
import { WORD_TIERS, type vocabDiagnostics } from '@/lib/vocab-diagnostics'
interface StudentEvidence {studentId:string;name:string;diagnostics?:ReturnType<typeof vocabDiagnostics>}
export default function VocabTierReport({students,onReview}:{students:StudentEvidence[];onReview:(studentId:string,termIds:string[])=>void}){
 const [tier,setTier]=useState('all'),[student,setStudent]=useState('all')
 const visible=students.filter(s=>student==='all'||s.studentId===student)
 const tiers=WORD_TIERS.filter(t=>tier==='all'||String(t.id)===tier)
 return <section className="space-y-4" aria-label="Language tier proficiency"><h3 className="text-lg font-semibold">Language tiers and learning needs</h3><p className="text-sm text-muted-foreground">Tiers describe the words, not a student’s English-language level. Accuracy uses each word’s five most recent checks. “Not checked” is missing evidence, not a failed word.</p>
 <div className="flex flex-wrap gap-3"><label>Word tier <select aria-label="Report word tier" className="min-h-11 rounded-lg border bg-background px-3" value={tier} onChange={e=>setTier(e.target.value)}><option value="all">All tiers</option>{WORD_TIERS.map(t=><option key={t.id} value={t.id}>{t.label}</option>)}</select></label><label>Student <select aria-label="Tier report student" className="min-h-11 rounded-lg border bg-background px-3" value={student} onChange={e=>setStudent(e.target.value)}><option value="all">All assigned students</option>{students.map(s=><option key={s.studentId} value={s.studentId}>{s.name}</option>)}</select></label></div>
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{tiers.map(t=>{const rows=visible.flatMap(s=>s.diagnostics?.tiers.filter(x=>x.id===t.id)??[]);const attempts=rows.reduce((n,r)=>n+r.attempts,0),correct=rows.reduce((n,r)=>n+r.correct,0),total=rows.reduce((n,r)=>n+r.total,0);return <div key={t.id} className="rounded-xl border border-border p-4"><h4 className="font-semibold">{t.label}</h4><p className="mt-2 text-2xl font-semibold">{attempts?`${Math.round(correct*100/attempts)}%`:'No checks'}</p><p className="text-sm">{rows.reduce((n,r)=>n+r.ready,0)}/{total} student-word goals met</p><p className="text-sm text-muted-foreground">{attempts} recent responses · {rows.reduce((n,r)=>n+r.needsHelp,0)} words need attention</p></div>})}</div>
 <div className="overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Student proficiency by vocabulary tier</caption><thead><tr><th className="p-3" scope="col">Student</th>{tiers.map(t=><th className="p-3" scope="col" key={t.id}>{t.label}</th>)}</tr></thead><tbody>{visible.map(s=><tr className="border-t border-border" key={s.studentId}><th className="p-3" scope="row">{s.name}</th>{tiers.map(t=>{const r=s.diagnostics?.tiers.find(x=>x.id===t.id);return <td className="p-3" key={t.id}>{!r?.total?'No words assigned':<><strong>{r.accuracy===null?(r.pending?'Awaiting review':'Not checked'):`${r.accuracy}%`}</strong><p>{r.ready}/{r.total} words ready · {r.checked} checked</p><p className="text-muted-foreground">{r.attempts} responses</p></>}</td>})}</tr>)}</tbody></table></div>
 <h4 className="font-semibold">What needs attention?</h4>{visible.map(s=>{const issues=(s.diagnostics?.issues??[]).filter(w=>tier==='all'||String(w.tier)===tier);return <details key={s.studentId} className="rounded-lg border border-border p-3"><summary className="min-h-11 cursor-pointer font-medium">{s.name} · {issues.length} words to check or review</summary>{!issues.length?<p className="text-sm">No current flags in this selection.</p>:<><div className="grid gap-3 md:grid-cols-2">{issues.map(w=><article key={w.id} className="rounded-lg bg-muted p-3 text-sm"><strong>{w.term}</strong> · {w.issue}<p>{w.attempts?`${w.misses} incorrect of ${w.attempts} recent responses.`:w.pending?'Submitted; awaiting teacher review.':'No saved response yet.'}{w.confusedWith?` Most recently chose “${w.confusedWith}”.`:''}</p><p className="mt-1">{w.next}</p></article>)}</div><button className="mt-3 min-h-11 rounded-lg border border-border px-3" onClick={()=>onReview(s.studentId,issues.map(w=>w.id))}>Prepare practice for these words</button></>}</details>})}
 </section>
}
