'use client'
import {useState} from 'react'
import type {LearningWord} from '@/lib/vocab-learning'
export default function VocabWordSupportEditor({word,onSaved}:{word:LearningWord;onSaved:(w:LearningWord)=>void}){
 const [draft,setDraft]=useState(word),[lang,setLang]=useState('es'),[busy,setBusy]=useState(false),[status,setStatus]=useState('')
 const field='block w-full min-h-11 border border-border rounded-md p-2 bg-background text-sm'
 const languages=[['es','Spanish'],['pt','Portuguese'],['ht','Haitian Creole'],['fr','French'],['ar','Arabic'],['zh','Chinese'],['vi','Vietnamese']]
 const save=async()=>{setBusy(true);setStatus('');try{const r=await fetch('/api/vocab/terms',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:word.id,icon:draft.icon??'',example:draft.example??'',definition_es:draft.definition_es??'',translations:draft.translations??{},tier:draft.tier})});if(!r.ok){const d=await r.json();throw new Error(d.error)}onSaved(draft);setStatus('Saved for future assignments. Existing assignments keep their original word supports.')}catch(e){setStatus(e instanceof Error?e.message:'Could not save')}finally{setBusy(false)}}
 return <details className="mt-2"><summary className="min-h-11 py-2 text-sm underline cursor-pointer">Edit word supports</summary><div className="space-y-2"><label className="block text-xs">Word type<select className={field} value={draft.tier??''} onChange={e=>setDraft({...draft,tier:e.target.value?Number(e.target.value):null})}><option value="">Unclassified</option><option value="1">Everyday</option><option value="2">Academic</option><option value="3">Physics</option></select></label><label className="block text-xs">Picture / emoji<input className={field} value={draft.icon??''} onChange={e=>setDraft({...draft,icon:e.target.value})}/></label><label className="block text-xs">Example / sentence frame<textarea className={field} value={draft.example??''} onChange={e=>setDraft({...draft,example:e.target.value})}/></label><label className="block text-xs">Language<select className={field} value={lang} onChange={e=>setLang(e.target.value)}>{languages.map(([code,name])=><option key={code} value={code}>{name}</option>)}</select></label><label className="block text-xs">Translated word<input className={field} value={draft.translations?.[lang]?.term??''} onChange={e=>setDraft({...draft,translations:{...draft.translations,[lang]:{...draft.translations?.[lang],term:e.target.value}}})}/></label><label className="block text-xs">Translated definition<textarea className={field} value={draft.translations?.[lang]?.definition??(lang==='es'?draft.definition_es??'':'')} onChange={e=>setDraft({...draft,translations:{...draft.translations,[lang]:{...draft.translations?.[lang],definition:e.target.value}}})}/></label><button className="min-h-11 rounded-lg border border-border px-3 text-sm" disabled={busy} onClick={save}>{busy?'Saving…':'Save supports'}</button><p className="text-xs" role="status">{status}</p></div></details>
}
