'use client'
import { useCallback,useEffect,useState } from 'react'
import Link from 'next/link'
import VocabWordSupportEditor from './VocabWordSupportEditor'
import { summarizeWords,type VocabTask,type LearningWord } from '@/lib/vocab-learning'
interface Catalog {courses:{id:string;name:string;section:string|null}[];sets:{id:string;name:string;lesson_id:string|null}[];words:LearningWord[];targets:{id:string;slug:string;statement:string;lesson_id:string|null}[];links:{target_id:string;term_id:string}[];enrollments:{course_id:string;student_id:string;students:{id:string;name:string}|null}[]}
type Progress=ReturnType<typeof summarizeWords>&{studentId:string;name:string;physicsRating:number|null}
type Task=VocabTask&{progress:Progress[]}
const field='min-h-11 rounded-lg border border-border bg-background px-3 py-2 text-sm'
const button='min-h-11 rounded-lg border border-border px-3 py-2 text-sm hover:bg-muted disabled:opacity-50'
async function api(url:string,init?:RequestInit){const r=await fetch(url,init);const d=await r.json();if(!r.ok)throw new Error(d.error??'Could not save');return d}
export default function VocabLearningBoard(){
 const [catalog,setCatalog]=useState<Catalog|null>(null),[tasks,setTasks]=useState<Task[]>([])
 const [target,setTarget]=useState(''),[setId,setSetId]=useState(''),[search,setSearch]=useState(''),[tier,setTier]=useState('all')
 const [terms,setTerms]=useState<string[]>([]),[classes,setClasses]=useState<string[]>([]),[students,setStudents]=useState<string[]>([])
 const [title,setTitle]=useState(''),[due,setDue]=useState(''),[note,setNote]=useState(''),[threshold,setThreshold]=useState(80),[minimum,setMinimum]=useState(2),[mode,setMode]=useState('recognition')
 const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState(''),[filter,setFilter]=useState('')
 const refresh=useCallback(async()=>{const d=await api('/api/vocab/tasks');setTasks(d.tasks)},[])
 useEffect(()=>{Promise.all([api('/api/vocab/catalog'),api('/api/vocab/tasks')]).then(([c,t])=>{setCatalog(c);setTasks(t.tasks);const sp=new URLSearchParams(location.search);const tid=sp.get('target_id')??'';setTarget(tid);setSetId(sp.get('set_id')??'');if(tid){setTerms(c.links.filter((l:{target_id:string})=>l.target_id===tid).map((l:{term_id:string})=>l.term_id));setTitle(c.targets.find((t:{id:string})=>t.id===tid)?.statement??'')}else if(sp.get('set_id'))setTerms(c.words.filter((w:LearningWord)=>w.vocabulary_set_id===sp.get('set_id')).map((w:LearningWord)=>w.id))}).catch(e=>setError(e.message))},[])
 const run=async(action:()=>Promise<void>)=>{setBusy(true);setError('');setMessage('');try{await action()}catch(e){setError(e instanceof Error?e.message:'Could not save')}finally{setBusy(false)}}
 if(!catalog)return <div className="p-6" role="status">{error||'Loading vocabulary…'}</div>
 const toggle=(id:string,values:string[],save:(v:string[])=>void)=>save(values.includes(id)?values.filter(v=>v!==id):[...values,id])
 const words=catalog.words.filter(w=>(!setId||w.vocabulary_set_id===setId)&&(tier==='all'||w.tier===Number(tier))&&`${w.term} ${w.definition}`.toLowerCase().includes(search.toLowerCase()))
 const roster=[...new Map(catalog.enrollments.filter(e=>classes.includes(e.course_id)).map(e=>[e.student_id,e])).values()]
 const current=tasks.find(t=>t.id===selected)
 const assign=()=>run(async()=>{const d=await api('/api/vocab/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({course_ids:classes,student_ids:students,term_ids:terms,target_id:target,title:title||'Vocabulary practice',due_on:due,note,threshold,min_checks:minimum,check_mode:mode})});await refresh();setMessage(`Assigned to ${d.created} class${d.created===1?'':'es'}. Students can open it from Home.`)})
 return <div className="container mx-auto space-y-6 px-4 py-6">
  <div><Link href="/admin/vocabulary" className="text-sm underline">Vocabulary</Link><h1 className="text-2xl font-bold mt-2">Assign words · see learning</h1><p className="text-muted-foreground">Everyday, academic, and physics words supporting the same learning target. Language support never lowers the physics rating.</p></div>
  {error&&<p role="alert" className="text-destructive">{error}</p>}{message&&<p role="status" className="text-success">{message}</p>}
  <div className="grid gap-6 xl:grid-cols-2">
   <section className="rounded-xl border border-border p-4 space-y-4">
    <h2 className="font-bold text-lg">1. Choose the words</h2>
    <label className="block">Learning target<select aria-label="Learning target" className={`${field} w-full`} value={target} onChange={e=>{const id=e.target.value;setTarget(id);setTerms(catalog.links.filter(l=>l.target_id===id).map(l=>l.term_id));setTitle(catalog.targets.find(t=>t.id===id)?.statement??'');setSetId('')}}><option value="">Vocabulary only</option>{catalog.targets.map(t=><option key={t.id} value={t.id}>{t.slug} · {t.statement}</option>)}</select></label>
    <div className="flex flex-wrap gap-2"><input aria-label="Search words" placeholder="Search words or definitions" value={search} onChange={e=>setSearch(e.target.value)} className={`${field} flex-1`}/><select aria-label="Word tier" value={tier} onChange={e=>setTier(e.target.value)} className={field}><option value="all">All word types</option><option value="1">Everyday</option><option value="2">Academic</option><option value="3">Physics</option></select></div>
    <select aria-label="Vocabulary set" className={`${field} w-full`} value={setId} onChange={e=>setSetId(e.target.value)}><option value="">All published sets</option>{catalog.sets.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>
    <div className="flex flex-wrap items-center gap-2"><b>{terms.length} selected</b><button className={button} onClick={()=>setTerms([...new Set([...terms,...words.map(w=>w.id)])])}>Add visible words</button><button className={button} onClick={()=>setTerms([])}>Clear selection</button>{target&&<button className={button} disabled={busy} onClick={()=>run(async()=>{await api('/api/vocab/catalog',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({target_id:target,term_ids:terms})});setCatalog({...catalog,links:[...catalog.links.filter(l=>l.target_id!==target),...terms.map(term_id=>({target_id:target,term_id}))]});setMessage('Default words saved for this target. Individual assignments can use a different selection.')})}>Save as target defaults</button>}</div>
    <div className="max-h-96 overflow-auto space-y-2">{words.map(w=><div key={w.id} className="flex gap-3 rounded-lg border border-border p-3"><input aria-label={`Assign ${w.term}`} className="mt-1 h-5 w-5" type="checkbox" checked={terms.includes(w.id)} onChange={()=>toggle(w.id,terms,setTerms)}/><span><strong>{w.icon} {w.term}</strong> <small className="text-muted-foreground">{w.tier===1?'Everyday':w.tier===2?'Academic':w.tier===3?'Physics':'Unclassified'}</small><span className="block text-sm">{w.definition}</span>{w.definition_es&&<span className="block text-sm text-muted-foreground">Spanish: {w.definition_es}</span>}{Object.entries(w.translations??{}).map(([lang,t])=><span key={lang} className="block text-sm text-muted-foreground">{lang}: {t.definition||t.term}</span>)}{w.example&&<span className="block text-sm italic">{w.example}</span>}<VocabWordSupportEditor word={w} onSaved={updated=>setCatalog({...catalog,words:catalog.words.map(x=>x.id===updated.id?updated:x)})}/></span></div>)}{!words.length&&<p>No matching words. Publish a vocabulary set to make it assignable.</p>}</div>
    {terms.length>0&&<details><summary className="cursor-pointer min-h-11">Review all selected words</summary><p>{catalog.words.filter(w=>terms.includes(w.id)).map(w=>w.term).join(' · ')}</p></details>}
   </section>
   <section className="rounded-xl border border-border p-4 space-y-4">
    <h2 className="font-bold text-lg">2. Choose students and requirements</h2>
    <p className="text-sm text-muted-foreground">Select students for a group or individual assignment. Leave student selection empty to assign to everyone in the selected classes.</p>
    <fieldset><legend className="font-medium">Classes</legend>{catalog.courses.map(c=><label key={c.id} className="flex gap-2 items-center min-h-11"><input type="checkbox" checked={classes.includes(c.id)} onChange={()=>{toggle(c.id,classes,setClasses);setStudents([])}}/>{c.name} {c.section}</label>)}</fieldset>
    <details><summary className="cursor-pointer min-h-11">Specific students ({students.length||'all'})</summary><div className="max-h-48 overflow-auto">{roster.map(e=><label key={e.student_id} className="flex gap-2 items-center min-h-11"><input type="checkbox" checked={students.includes(e.student_id)} onChange={()=>toggle(e.student_id,students,setStudents)}/>{e.students?.name??'Student'}</label>)}</div></details>
    <label className="block">Assignment title<input className={`${field} w-full`} maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></label>
    <div className="flex flex-wrap gap-3"><label>Due date<input type="date" className={`${field} block`} value={due} onChange={e=>setDue(e.target.value)}/></label><label>Check skill<select className={`${field} block`} value={mode} onChange={e=>setMode(e.target.value)}><option value="recognition">Recognize the word</option><option value="recall">Recall and spell the word</option></select></label></div>
    <div className="flex flex-wrap gap-3"><label>Recent accuracy required (%)<input type="number" min={50} max={100} className={`${field} block w-24`} value={threshold} onChange={e=>setThreshold(Number(e.target.value))}/></label><label>Checks per word<select className={`${field} block`} value={minimum} onChange={e=>setMinimum(Number(e.target.value))}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label></div>
    <p className="text-sm text-muted-foreground">Every assigned word must meet the requirement, using up to its five most recent checks. A later successful check on another day provides retention evidence. Physics application is assessed in class work.</p>
    <label className="block">Directions / sentence frame<textarea rows={3} className={`${field} w-full`} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)} placeholder="For example: Describe how the object's position changes. Use ‘The position changes because…’"/></label>
    <button className={`${button} bg-primary text-primary-foreground w-full`} disabled={busy||!terms.length||!classes.length} onClick={assign}>{busy?'Saving…':'Assign vocabulary'}</button>
   </section>
  </div>
  <section className="rounded-xl border border-border p-4 space-y-4"><h2 className="font-bold text-lg">Learning by assignment and target</h2><div className="flex gap-2 flex-wrap"><input aria-label="Filter assignments" className={field} placeholder="Search assignments" value={filter} onChange={e=>setFilter(e.target.value)}/><button className={button} onClick={()=>run(refresh)}>Refresh results</button></div>
   <select aria-label="Assignment report" className={`${field} w-full`} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select an assignment</option>{tasks.filter(t=>t.title.toLowerCase().includes(filter.toLowerCase())).map(t=><option key={t.id} value={t.id}>{t.active?'':'Archived · '}{t.title} · {catalog.courses.find(c=>c.id===t.course_id)?.name} · {t.created_at.slice(0,10)}</option>)}</select>
   {current&&<><p>{catalog.targets.find(t=>t.id===current.target_id)?.statement??'Vocabulary only'} · {current.check_mode==='recognition'?'Recognition':'Recall / spelling'}</p><div className="flex flex-wrap items-center gap-2"><label>Due date <input aria-label="Edit assignment due date" type="date" className={field} value={current.due_on??''} disabled={busy} onChange={e=>run(async()=>{await api('/api/vocab/tasks',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:current.id,due_on:e.target.value||null})});await refresh()})}/></label><button className={button} disabled={busy} onClick={()=>run(async()=>{await api('/api/vocab/tasks',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:current.id,active:!current.active})});await refresh()})}>{current.active?'Archive assignment':'Reactivate'}</button></div>
   <p className="text-sm text-muted-foreground">Accuracy is shown with word coverage. Missing checks are not errors. Pictures, audio, and translations do not reduce the physics rating.</p>
   <div className="overflow-auto"><table className="w-full text-sm text-left"><thead><tr>{['Student','Words checked','Words ready','Recent accuracy','Retention','Physics rating','Review'].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{current.progress.map(p=><tr key={p.studentId} className="border-t border-border"><td className="p-2">{p.name}</td><td className="p-2">{p.covered}/{p.total}</td><td className="p-2">{p.ready}/{p.total}</td><td className="p-2">{p.accuracy===null?'Not checked':`${p.accuracy}%`}</td><td className="p-2">{p.reviewDue?'Review due':p.retained?'Later success recorded':'Later check needed'}</td><td className="p-2">{p.physicsRating??'Not rated'}</td><td><button className={button} onClick={()=>{setTarget(current.target_id??'');setTerms(p.words.filter(w=>!w.ready||w.reviewDue).map(w=>w.id));setClasses([current.course_id]);setStudents([p.studentId]);setTitle(`${current.title} · review`);window.scrollTo({top:0,behavior:'instant'})}}>Assign review</button></td></tr>)}</tbody></table></div>
   {current.progress.map(p=><details key={p.studentId} className="border-t border-border pt-2"><summary className="min-h-11 cursor-pointer">{p.name} · word evidence</summary><div className="grid gap-2 md:grid-cols-2">{p.words.map(w=><div key={w.id} className="rounded-lg bg-muted p-3 text-sm"><strong>{current.words.find(t=>t.id===w.id)?.term}</strong> · {w.accuracy===null?'Not checked':`${w.accuracy}% · ${w.attempts} recent checks`}{w.previousAccuracy!==null&&` · earlier ${w.previousAccuracy}%`}<p>{w.supports.length?`Supports used: ${w.supports.join(', ')}`:'No additional supports recorded'}</p><p>{w.lastAt?`Last checked ${w.lastAt.slice(0,10)}`:'Needs a first check'}</p></div>)}</div></details>)}</>}
  </section>
  <Link className="underline text-sm" href="/admin/vocabulary/assign?view=legacy">Historical game practice grid</Link>
 </div>
}
