'use client'
import { useRef,useState } from 'react'
import type { VocabTask } from '@/lib/vocab-learning'
import type { quizSummary } from '@/lib/vocab-quiz'
type Student={studentId:string;name:string;quiz?:ReturnType<typeof quizSummary>}
function Review({task,student,onSaved}:{task:VocabTask;student:Student;onSaved:()=>Promise<unknown>}){
 const q=student.quiz!,results=q.responses??[]
 const [grades,setGrades]=useState<Record<string,{correct:boolean|null;feedback:string}>>(()=>Object.fromEntries(results.map(r=>[r.term_id,{correct:r.correct,feedback:r.feedback??''}])))
 const [error,setError]=useState(''),[busy,setBusy]=useState(false);const saving=useRef(false)
 const save=async()=>{if(saving.current)return;saving.current=true;setBusy(true);setError('');try{const r=await fetch('/api/vocab/checks',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({task_id:task.id,check_id:q.checkId,review_version:q.reviewVersion,grades:results.map(r=>({term_id:r.term_id,...grades[r.term_id]}))})});const d=await r.json();if(!r.ok)throw new Error(d.error??'Could not save review');await onSaved()}catch(e){setError(e instanceof Error?e.message:'Could not save review')}finally{saving.current=false;setBusy(false)}}
 return <details className="rounded-lg border border-border p-3"><summary className="min-h-11 cursor-pointer font-semibold">{student.name} · {q.needsReview?'Awaiting review':`${q.score}%`}</summary><p className="text-sm mb-3">{task.quiz_format==='sentence'?'Mark correct when the sentence uses the word appropriately and demonstrates its meaning.':'Mark correct when the explanation captures the essential meaning in the student’s own words.'} Do not require the exact reference wording.</p>{results.map(r=><fieldset key={r.term_id} className="rounded-lg bg-muted p-3 mb-3 space-y-2"><legend className="font-semibold">{r.term??task.words.find(w=>w.id===r.term_id)?.term}</legend><p className="text-sm">Reference meaning: {r.definition??task.words.find(w=>w.id===r.term_id)?.definition}</p><p className="whitespace-pre-wrap">Student answer: {r.response}</p><label>Score <select className="min-h-11 rounded border bg-background px-3" value={grades[r.term_id].correct===null?'':String(grades[r.term_id].correct)} onChange={e=>setGrades(g=>({...g,[r.term_id]:{...g[r.term_id],correct:e.target.value===''?null:e.target.value==='true'}}))}><option value="">Choose score</option><option value="true">Correct</option><option value="false">Needs correction</option></select></label><label className="block">Feedback (optional)<textarea className="block w-full rounded border bg-background p-2" maxLength={2000} value={grades[r.term_id].feedback} onChange={e=>setGrades(g=>({...g,[r.term_id]:{...g[r.term_id],feedback:e.target.value}}))}/></label></fieldset>)}{error&&<p role="alert" className="text-destructive">{error}</p>}<button className="min-h-11 rounded-lg border px-4" disabled={busy||results.some(r=>grades[r.term_id].correct===null)} onClick={save}>{busy?'Saving…':'Save quiz review'}</button></details>
}
export default function VocabQuizReview({task,onSaved}:{task:VocabTask&{progress:Student[]};onSaved:()=>Promise<unknown>}){return <section aria-label="Quiz results" className="space-y-3"><h3 className="text-lg font-bold">Quiz results</h3><p className="text-sm">One submission per student. Score goal: {task.threshold}%. Submitted work awaiting review is not counted as incorrect.</p>{task.progress.map(s=>s.quiz?.submitted&&['definition','sentence'].includes(task.quiz_format??'')?<Review key={`${s.studentId}:${s.quiz.reviewVersion}`} task={task} student={s} onSaved={onSaved}/>:<p key={s.studentId}>{s.name} · {s.quiz?.submitted?`${s.quiz.score}% · ${(s.quiz.score??0)>=task.threshold?'Goal met':'Needs review'}`:'Not submitted'}</p>)}</section>}
