#!/usr/bin/env python3
"""Generate supabase/migrations/seed_trades_lessons_u1_u2.sql from the MVP ETF
Planning docx files (lesson plans + student packets). One lesson per SESSION.

  python3 scripts/gen-trades-lessons.py "<MVP ETF Planning folder>" supabase/migrations/seed_trades_lessons_u1_u2.sql
"""
import zipfile, re, html, json, sys
ROOT = sys.argv[1]
OUT = sys.argv[2]

def docx_lines(path):
    z = zipfile.ZipFile(path); xml = z.read('word/document.xml').decode('utf8')
    xml = re.sub(r'</w:p>', '\n', xml); xml = re.sub(r'<w:tab/>', '\t', xml)
    t = html.unescape(re.sub(r'<[^>]+>', '', xml))
    return [l.strip() for l in t.split('\n') if l.strip()]

UNITS = {
  'trades-1': dict(name='Unit 1: Length & Tolerance — The Fieldhouse Wall', plans='Unit 1/Unit1_Lesson_Plans.docx', packet='Unit 1/Unit1_Student_Packet.docx',
                   mastery='tr.u1.mastery-as-built', core_shorts=set(),
                   sa={1:['tr.u1.read-rule','tr.u1.check-inst','tr.u1.choose-inst','tr.u1.repeat','tr.u1.sketch'],
                       2:['tr.u1.nominal','tr.u1.vocab','tr.u1.fits','tr.u1.gauge','tr.u1.dimension','tr.u1.scale'],
                       3:['tr.u1.datum','tr.u1.cumul','tr.u1.sixteen','tr.u1.tolerance','tr.u1.views','tr.u1.asbuilt','tr.u1.the-walk']}),
  'trades-2': dict(name='Unit 2: Plumb, Level, Square, Slope', plans='Unit 2/Unit2_Lesson_Plans.docx', packet='Unit 2/Unit2_Student_Packet.docx',
                   mastery='tr.u2.mastery-route-the-fall', core_shorts={'2.4'},
                   sa={1:['tr.u2.plumb-level','tr.u2.gravity-ref','tr.u2.bubble','tr.u2.level-check','tr.u2.square-check','tr.u2.345'],
                       2:['tr.u2.slope-set','tr.u2.rise-run','tr.u2.slope-why','tr.u2.fall-total','tr.u2.plan-slope','tr.u2.stair-sect'],
                       3:['tr.u2.stair-why','tr.u2.racking','tr.u2.bay-conflict']}),
}

def parse_plans(lines):
    out = {}; cur = None
    for i, l in enumerate(lines):
        m = re.match(r'^SESSION (\d\.\d)\s+·\s+(.*)$', l)
        if m:
            cur = m.group(1); out[cur] = dict(title=m.group(2).strip(), long=None, target='', flow=[]); continue
        if cur is None: continue
        s = out[cur]
        if s['long'] is None and re.match(r'^(LONG SESSION|SHORT)', l): s['long'] = l.startswith('LONG')
        if not s['target'] and l.startswith('I can'): s['target'] = l
        if re.match(r'^\d+–\d+$', l) and i+1 < len(lines): s['flow'].append((l, lines[i+1]))
    return out

def parse_packet(lines):
    out = {}; cur = None; buf = []
    def flush():
        if cur and buf: out.setdefault(cur, []).extend(buf)
    for l in lines:
        m = re.match(r'^(\d\.\d)\s{2,}([A-Z0-9].*)$', l)
        if m:
            flush(); buf = []
            cur_all = re.findall(r'(\d\.\d)', l)
            cur = tuple(cur_all) if len(cur_all) > 1 else m.group(1)
            buf.append('## ' + re.sub(r'^\d\.\d\s+', '', l).title()); continue
        if re.match(r'^Cycle \d — rate yourself', l):
            flush(); buf = []; cur = None; continue
        if l.upper() == 'THE WALK':
            flush(); buf = ['**The Walk — before you price it, look at it**']; cur = '3.5'; continue
        if cur is None: continue
        if l in ('○', '☐', '#', 'TARGET', 'HELP?') or re.fullmatch(r'[○☐ ]+', l) or re.fullmatch(r'\d', l): continue
        if re.match(r'^\d+\.\s', l): buf.append(l)
        elif len(l) <= 42 and l.upper() == l and re.search(r'[A-Z]', l): buf.append('**' + l.title() + '**')
        else: buf.append(l)
    flush()
    final = {}
    for k, v in out.items():
        for c in (k if isinstance(k, tuple) else (k,)): final.setdefault(c, []).extend(v)
    return {k: '\n\n'.join(v) for k, v in final.items()}

def q(s): return "'" + s.replace("'", "''") + "'"

sql = ["-- Trades Physics — Units 1 & 2 sessions as lessons. Generated by scripts/gen-trades-lessons.py from the",
       "-- MVP ETF Planning lesson plans + student packets (docx). Idempotent: upsert by slug.",
       "-- One lesson = one SESSION (one school day). LONG = B+C double (~110 min), SHORT = one block (~55 min).",
       "-- transfer_core follows the units' own cut rule: 'drop a short, never a long' (+ Unit 2: never 2.4).", ""]
for uid, U in UNITS.items():
    plans = parse_plans(docx_lines(f"{ROOT}/{U['plans']}"))
    packet = parse_packet(docx_lines(f"{ROOT}/{U['packet']}"))
    n = 0
    for cyc in (1,2,3):
        for k in (1,2,3,4,5):
            code = f"{cyc}.{k}"; n += 1
            P = plans[code]; is_long = bool(P['long']); is_mastery = (code == '3.5')
            slug = f"{uid.replace('trades-','tu')}-s{n:02d}"
            title = f"{code} · {P['title']}"
            blocks = [{'id':'b1','type':'target','statement': P['target']},
                      {'id':'b2','type':'callout','variant':'note','title': ('Long session · ~110 min · B and C' if is_long else 'Short session · ~55 min · one block'),
                       'markdown': ('**Measure it. Draw it. Hand it over.** Your packet page for this session is on paper — do the work there. This page is the plan and the target.' if is_long else 'One movement. Your packet page for this session is on paper — do the work there.')}]
            if P['flow']:
                rows = '\n'.join(f"| {t} | {w} |" for t, w in P['flow'])
                blocks.append({'id':'b3','type':'prose','markdown': "### What happens today\n\n| Time | What happens |\n|---|---|\n" + rows})
            if code in packet: blocks.append({'id':'b4','type':'prose','markdown': "### From the packet\n\n" + packet[code]})
            if k == 5: blocks.append({'id':'b5','type':'self_assessment','capture':True,'targetIds': U['sa'][cyc]})
            if is_mastery: blocks.append({'id':'b6','type':'transfer_prompt','masteryTaskSlug': U['mastery']})
            doc = {'schemaVersion':1,'dayType': ('TRANSFER' if is_mastery else 'ANCHOR' if code=='1.1' else 'LAB' if is_long else 'STANDARD'),'blocks':blocks}
            core = is_long or code in U['core_shorts']
            desc = f"Cycle {cyc}, session {k} of 5 — {'long' if is_long else 'short'}."
            sql.append("insert into public.lessons (slug, title, unit, unit_id, lesson_number, lesson_type, published, estimated_time, planned_days, transfer_core, objectives, description, content_blocks, content) values (" +
                       ", ".join([q(slug), q(title), q(U['name']), q(uid), str(n), q('markdown'), 'true', str(110 if is_long else 55), '1', 'true' if core else 'false',
                                  "array[" + q(P['target']) + "]::text[]", q(desc), q(json.dumps(doc, ensure_ascii=False)) + "::jsonb", q('')]) +
                       ") on conflict (slug) do update set title = excluded.title, unit = excluded.unit, unit_id = excluded.unit_id, lesson_number = excluded.lesson_number, published = excluded.published, estimated_time = excluded.estimated_time, planned_days = excluded.planned_days, transfer_core = excluded.transfer_core, objectives = excluded.objectives, description = excluded.description, content_blocks = excluded.content_blocks, updated_at = now();")
    sql.append("")
sql.append("-- Unit windows: 15 sessions = 3 academic weeks. Trades cohort's first academic week is Sep 7, 2026 (opposite MVP CPA).")
sql.append("update public.units set allotted_days = 15, default_start_date = '2026-09-07' where id = 'trades-1';")
sql.append("update public.units set allotted_days = 15, default_start_date = '2026-10-19' where id = 'trades-2';")
open(OUT, 'w').write('\n'.join(sql) + '\n')
print("wrote", OUT)
