// Reproducible art review, using the production composer and versioned catalog.
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),esbuild=require('esbuild'),React=require('react'),{renderToStaticMarkup}=require('react-dom/server'),sharp=require('sharp');
process.env.NODE_PATH=path.join(process.cwd(),'node_modules');require('node:module').Module._initPaths();
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'avatar-render-'));const output=process.argv[2]||'docs/avatar-verification';fs.mkdirSync(output,{recursive:true});
esbuild.buildSync({entryPoints:['src/components/avatar/Avatar.tsx'],bundle:true,platform:'node',format:'cjs',outfile:path.join(tmp,'avatar.cjs'),jsx:'automatic',external:['react','react/jsx-runtime']});
esbuild.buildSync({entryPoints:['src/lib/avatar/types.ts'],bundle:true,platform:'node',format:'cjs',outfile:path.join(tmp,'types.cjs')});
const Avatar=require(path.join(tmp,'avatar.cjs')).default;const {TRAIT_OPTIONS}=require(path.join(tmp,'types.cjs'));const items=JSON.parse(fs.readFileSync('src/data/avatar-catalog.json'));
const cases=[];for(const hair of ['short','afro','spiky','twists','braids','hijab'])for(const face of TRAIT_OPTIONS.face)cases.push({label:`${hair} / ${face}`,traits:{hair_style:hair,face}});
for(const skin of TRAIT_OPTIONS.skin)cases.push({label:`${skin} / black hair`,traits:{skin,hair_color:'black'}});
for(const shirt_style of TRAIT_OPTIONS.shirt_style)cases.push({label:`Free ${shirt_style}`,traits:{shirt_style,shirt_color:'teal'}});
for(const item of items)cases.push({label:item.name,traits:{},equipped:{[item.slot]:item.slug}});
for(const slug of ['football-helmet','space-helmet','spiderman-mask','viking-helmet'])for(const hair of ['afro','spiky'])cases.push({label:`${slug} / ${hair}`,traits:{hair_style:hair,face:'heart'},equipped:{head:slug}});
let renderId=0;const render=(c,size=125,crop='full')=>renderToStaticMarkup(React.createElement(Avatar,{...c,items,size,crop}),{identifierPrefix:'avatar-review-'+renderId++});
(async()=>{let clips=[];let count=0;for(const hair_style of TRAIT_OPTIONS.hair_style)for(const face of TRAIT_OPTIONS.face)for(const crop of ['full','medium','head']){const svg=render({traits:{hair_style,face}},160,crop);const {data,info}=await sharp(Buffer.from(svg)).raw().toBuffer({resolveWithObject:true});count++;if(crop==='full'){let top=0;for(let x=0;x<info.width;x++)top+=data[x*4+3]>0;if(top)clips.push(`${hair_style}/${face}`);}}for(const item of items.filter(i=>i.slot==='head'))for(const face of TRAIT_OPTIONS.face)for(const hair_style of TRAIT_OPTIONS.hair_style){const svg=render({traits:{face,hair_style},equipped:{head:item.slug}},160,'full');const {data,info}=await sharp(Buffer.from(svg)).raw().toBuffer({resolveWithObject:true});count++;let top=0;for(let x=0;x<info.width;x++)top+=data[x*4+3]>0;if(top)clips.push(`${item.slug}/${hair_style}/${face}`);}if(clips.length)throw Error('Full portrait top clips: '+clips.join(', '));
const cols=6,w=240,h=250;const layers=[];let html='<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Avatar art verification</title><style>body{font:14px system-ui;background:#f5f3f8}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:12px}.card{background:white;border-radius:12px;padding:12px;text-align:center}.circle{display:inline-flex;border-radius:50%;overflow:hidden;background:#ddd}</style><h1>Avatar artwork verification</h1><p>Production composer; synthetic traits; full and circular 40px previews.</p><div class="grid">';
for(let i=0;i<cases.length;i++){const c=cases[i],x=i%cols*w,y=Math.floor(i/cols)*h;const sv=render(c),icon=render(c,40,'head');const label=c.label.replaceAll('&','&amp;');const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="240" height="250"><rect width="240" height="250" fill="#f5f3f8"/><rect x="5" y="5" width="230" height="240" rx="12" fill="white"/><g transform="translate(28 14)">${sv}</g><g transform="translate(183 50)">${icon}</g><text x="12" y="220" font-family="Arial" font-size="11">${label}</text></svg>`;layers.push({input:await sharp(Buffer.from(svg)).png().toBuffer(),left:x,top:y});html+=`<div class="card">${sv}<span class="circle">${icon}</span><p>${label}</p></div>`;}
await sharp({create:{width:cols*w,height:Math.ceil(cases.length/cols)*h,channels:4,background:'#ddd'}}).composite(layers).png().toFile(path.join(output,'contact-sheet.png'));fs.writeFileSync(path.join(output,'index.html'),html+'</div>');console.log(`Rendered ${count} face/hair/crop and headwear combinations; no full portrait top clipping. Contact sheet: ${cases.length} cases.`);
})().catch(e=>{console.error(e);process.exitCode=1});
