# Reading map — CPA light / Honors full — Conceptual Physics (PH high-school edition).
# Each day: cpa = (sections, focus) or None; honors = list of (sections, thinkAndSolve, focus).
# Section ids resolve titles/pages/Concept Checks from src/data/textbook-sections.ts.
# Rule of thumb: CPA reads ONE section on concept-introduction days only; honors reads
# every section the day touches plus 2–3 Think and Solve problems chosen for the day's skill.

def H(secs, ts=None, focus=None): return {"secs": secs, "ts": ts or [], "focus": focus}
def Cp(secs, focus=None): return {"secs": secs, "focus": focus}

MAP = {
 "unit-1": {
  1:  {"cpa": Cp(["4.1"], "How can you tell something is moving at all?"), "honors": [H(["4.1","4.2"], [], "What does 'relative' buy us when we describe 2026-XJ?")]},
  2:  {"cpa": Cp(["4.2"], "Speed is distance per time — find the definition and one example."), "honors": [H(["4.2","4.3"], [], "Where exactly does velocity stop being 'just speed'?")]},
  3:  {"cpa": Cp(["4.3"], "One sentence: how is velocity different from speed?"), "honors": [H(["4.3","4.7"], [], "Read the graphs in 4.7 before we draw ours tomorrow.")]},
  4:  {"cpa": Cp(["5.1"], "Which quantities need a direction? List three."), "honors": [H(["5.1","5.2","5.3"], [39], "Components: how does one arrow become two?")]},
  5:  {"cpa": Cp(["4.9"], "Which equation would you use to predict where something ends up?"), "honors": [H(["4.9"], [51], "Match each equation in 4.9 to the question it answers.")]},
  6:  {"cpa": None, "honors": [H(["5.3"], [38, 39], "Redo the do-the-math boxes before you look at the answers."), H(["2.5"], [], "Same idea, different chapter: vectors on a supported object.")]},
  7:  {"cpa": Cp(["4.4"], "Acceleration is a change in velocity per time — find the units."), "honors": [H(["4.4","4.5","4.6"], [51, 52], "Free fall is acceleration with a fixed number. What is it, and why doesn't mass matter?")]},
  8:  {"cpa": None, "honors": [H(["4.5","4.6"], [53, 54, 56], "Problem-solving night: GIVEN / EQUATION / WORK / ANSWER on each.")]},
  9:  {"cpa": Cp(["3.4"], "State Newton's first law in your own words."), "honors": [H(["3.1","3.2","3.3","3.4","3.5","3.6"], [52, 53], "Short chapter — read all of it. Why did it take 2000 years to get past Aristotle?")]},
  10: {"cpa": Cp(["6.1"], "What does a net force DO to an object?"), "honors": [H(["6.1","6.2"], [], "Force causes acceleration; mass resists it. Find the sentence that says both.")]},
  11: {"cpa": Cp(["6.3"], "Write F = ma and say what each letter means."), "honors": [H(["6.3"], [56, 59], "Pay attention to the do-the-math boxes — we vary mass tomorrow.")]},
  12: {"cpa": None, "honors": [H(["6.3"], [57, 60, 61], "Practice night: three F = ma problems, full work shown.")]},
  13: {"cpa": None, "honors": [H(["6.6","6.7"], [55, 62], "Free fall explained by F = ma — then what air resistance changes.")]},
  14: {"cpa": Cp(["7.2"], "Find the sentence that defines action and reaction."), "honors": [H(["7.1","7.2","7.3","7.4"], [53, 56], "Why don't action and reaction cancel? (7.4 answers it.)")]},
  15: {"cpa": Cp(["2.1"], "What is a force, and how does the book draw one?"), "honors": [H(["2.1","2.2","2.3"], [42, 43], "The book draws the arrows; you will turn them into free body diagrams. No FBD section exists in this edition — lean on class notes.")]},
  16: {"cpa": None, "honors": [H(["2.4"], [44, 48], "Equilibrium for MOVING objects — constant velocity counts."), H(["7.5","7.6"], [], "Defining the system decides which forces are internal.")]},
  17: {"cpa": Cp(["6.4"], "Which way does friction act, and what does it depend on?"), "honors": [H(["6.4","6.5"], [58, 65], "Friction, then pressure — both are force over something.")]},
  18: {"cpa": Cp(["2.2"], "Equilibrium means net force zero — find the equilibrium rule."), "honors": [H(["2.2","2.3","2.4"], [], "Re-read with tomorrow's problems in mind: what is ΣF when nothing accelerates?"), H(["3.4"], [], "Newton's first law IS the equilibrium rule.")]},
  22: {"cpa": None, "honors": [H(["13.1","13.2"], [], "Preview for Unit 2: why the moon is falling.")]},
 },
 "unit-2": {
  1:  {"cpa": None, "honors": [H(["13.1","13.2"], [], "The apple and the moon are the same problem.")]},
  2:  {"cpa": Cp(["4.5"], "How fast is a falling object going after 1 s, 2 s, 3 s?"), "honors": [H(["4.5","4.6"], [52, 53, 56], "How fast vs. how far — keep the two tables separate."), H(["6.6"], [], "Why does everything fall at the same g? Newton's second law explains it.")]},
  3:  {"cpa": Cp(["3.5"], "Mass and weight are not the same — find the difference."), "honors": [H(["3.5"], [51, 53], "Mass is inertia; weight is a force. Compute both for yourself."), H(["13.8"], [], "What would 'weightless' actually mean?")]},
  4:  {"cpa": Cp(["13.4"], "Write the law of universal gravitation and name each symbol."), "honors": [H(["13.1","13.2","13.3","13.4"], [57, 60], "Newton's reasoning, then the equation it produced.")]},
  5:  {"cpa": Cp(["13.5"], "Double the distance — what happens to the force?"), "honors": [H(["13.5"], [58, 59, 61, 62], "Inverse-square practice: predict the factor BEFORE computing.")]},
  6:  {"cpa": Cp(["13.6"], "What is a gravitational field? One sentence."), "honors": [H(["13.6","13.7"], [53, 55], "Problem 53 derives g from G — do that one carefully.")]},
  7:  {"cpa": None, "honors": [H(["13.8"], [56, 63, 64], "Weight changes with altitude; problem 64 kills the 'above gravity' myth."), H(["14.1"], [], "Preview: what turns falling into orbiting?")]},
  9:  {"cpa": Cp(["5.4"], "Two motions at once — which one does gravity change?"), "honors": [H(["5.4","5.5"], [40, 46], "Independence of horizontal and vertical motion — find the figure that proves it.")]},
  10: {"cpa": Cp(["5.5"], "For a horizontal launch, what stays constant and what changes?"), "honors": [H(["5.5"], [42, 47, 48], "Three horizontal-launch problems: the fall time comes first, always.")]},
  11: {"cpa": Cp(["5.6"], "At what angle does a projectile go farthest?"), "honors": [H(["5.6"], [44, 45, 49], "Angled launches: components in, components out.")]},
  12: {"cpa": Cp(["10.3"], "What is centripetal force — and what supplies it for a car on a curve?"), "honors": [H(["10.1","10.2","10.3","10.4"], [49, 53, 54], "Centrifugal 'force' is the one that isn't there. Be ready to explain why.")]},
  13: {"cpa": Cp(["14.1"], "Why does a satellite keep missing Earth?"), "honors": [H(["14.1","14.2"], [41, 42], "Newton's cannon → circular orbit speed. Problem 42 is the moon.")]},
  14: {"cpa": Cp(["14.5"], "State Kepler's three laws — one phrase each."), "honors": [H(["14.3","14.4","14.5"], [47, 48], "Elliptical orbits and energy conservation are the same story told twice.")]},
  15: {"cpa": None, "honors": [H(["14.4","14.6"], [40, 50], "Escape speed and orbital period — the two numbers that date 2026-XJ's arrival.")]},
 },
 "unit-3": {
  1:  {"cpa": None, "honors": [H(["8.1"], [], "Momentum is inertia in motion — what two things does it depend on?")]},
  2:  {"cpa": Cp(["8.1"], "Write p = mv and give the units."), "honors": [H(["8.1"], [54], "Problem 54: show kg·m/s and N·s are the same unit.")]},
  3:  {"cpa": Cp(["8.2"], "How does a force applied for a TIME change momentum?"), "honors": [H(["8.2","8.3"], [56, 60, 61], "Impulse = change in momentum. Bouncing doubles it — why?")]},
  4:  {"cpa": Cp(["8.3"], "Why does a longer stopping time mean a smaller force?"), "honors": [H(["8.3"], [60, 62], "Airbags, egg on a sheet, follow-through — same equation, three stories.")]},
  5:  {"cpa": Cp(["8.4"], "When is momentum conserved? Finish the sentence: 'when no ___ force acts.'"), "honors": [H(["8.4"], [51, 64], "Problem 64 is a superhero hurling an asteroid. Yes, really.")]},
  6:  {"cpa": Cp(["8.5"], "Name the three kinds of collision."), "honors": [H(["8.5"], [57, 58, 65], "Elastic vs. inelastic: which conserves KE? Momentum is conserved in both.")]},
  8:  {"cpa": None, "honors": [H(["8.5"], [63, 65, 57], "Stick-together problems: one final velocity for the combined mass.")]},
  9:  {"cpa": None, "honors": [H(["8.5"], [59], "Bounce-apart: momentum in equals momentum out, but now two unknowns.")]},
  10: {"cpa": Cp(["8.6"], "Momentum is a vector — what does that change for a glancing collision?"), "honors": [H(["8.6"], [], "Momentum vectors add tip-to-tail like every other vector you've met.")]},
  11: {"cpa": None, "honors": [H(["8.4"], [64], "DART was an impulse delivered to an asteroid. Re-read conservation with that in mind.")]},
  12: {"cpa": None, "honors": [H(["8.2"], [55, 56], "Impact damage is impulse over a very short time.")]},
 },
 "unit-4": {
  1:  {"cpa": None, "honors": [H(["9.1"], [], "Work needs a force AND a distance in its direction.")]},
  2:  {"cpa": Cp(["9.1"], "When is NO work done, even though you push?"), "honors": [H(["9.1","9.2"], [], "Work, then power — the second is just the first divided by time.")]},
  3:  {"cpa": None, "honors": [H(["9.1"], [], "Re-read with angles in mind: only the component along the motion counts."), H(["5.3"], [], "Components again — the tool for work at an angle.")]},
  4:  {"cpa": Cp(["9.5"], "Write the kinetic energy equation. Double the speed — what happens to KE?"), "honors": [H(["9.3","9.4","9.5"], [46, 52], "Two kinds of mechanical energy; problem 46 asks whose frame of reference.")]},
  5:  {"cpa": Cp(["9.6"], "State the work-energy theorem in one line."), "honors": [H(["9.6"], [50, 54], "Problem 54 (skid distance) is the work-energy theorem in disguise.")]},
  7:  {"cpa": Cp(["9.4"], "Name three examples of potential energy."), "honors": [H(["9.4"], [47, 51], "PE = mgh — but h relative to WHAT? Problem 51 makes you choose.")]},
  8:  {"cpa": None, "honors": [H(["13.5"], [], "If g falls off with 1/r², mgh can't be the whole story."), H(["14.4"], [], "Energy conservation for satellites — the fix for mgh at altitude.")]},
  9:  {"cpa": None, "honors": [H(["14.4"], [43], "Problem 43: PE and KE trade places along an elliptical orbit.")]},
  10: {"cpa": Cp(["9.7"], "Find the law of conservation of energy and copy it word for word."), "honors": [H(["9.7"], [50, 51, 52], "Three conservation problems: pick your zero for PE and stick with it.")]},
  11: {"cpa": None, "honors": [H(["12.3"], [], "Rolling vs. sliding: some energy goes into rotation.")]},
  12: {"cpa": Cp(["9.7"], "Re-read: where is PE largest on a roller coaster? Where is KE largest?"), "honors": [H(["25.1"], [], "The pendulum is a conservation problem AND a timekeeper."), H(["9.7"], [52, 54], "Coaster + pendulum: height in, speed out.")]},
  14: {"cpa": Cp(["18.3"], "What does Hooke's law say about a spring?"), "honors": [H(["18.3"], [], "Elasticity, elastic limit, Hooke's law — find all three.")]},
  15: {"cpa": None, "honors": [H(["18.3"], [], "Re-read with ½kx² in mind: why is spring PE proportional to x squared?")]},
  16: {"cpa": Cp(["9.2"], "Power is work per time — find the unit named after James Watt."), "honors": [H(["9.2","9.8","9.9"], [48, 53], "Power, machines, efficiency: nothing is 100%. Where does the rest go?")]},
  17: {"cpa": None, "honors": [H(["8.5"], [59], "Re-read collisions with ENERGY in mind: which kind keeps KE?")]},
  18: {"cpa": Cp(["21.2"], "Heat is energy that moves — from what to what?"), "honors": [H(["21.1","21.2","21.4"], [], "Temperature vs. heat vs. internal energy — three different things.")]},
  19: {"cpa": None, "honors": [H(["9.5"], [52], "KE scales with v² — problem 52 shows what that does to impact energy.")]},
  20: {"cpa": Cp(["14.6"], "What is escape speed, and what is Earth's?"), "honors": [H(["14.6"], [40, 41], "Escape speed comes straight from energy conservation. Derive it before class.")]},
 },
 "unit-5": {
  1:  {"cpa": Cp(["21.1"], "What does a thermometer actually measure?"), "honors": [H(["21.1","21.2","21.3","21.4"], [], "Temperature, heat, thermal equilibrium, internal energy — four ideas, keep them apart.")]},
  2:  {"cpa": Cp(["21.6"], "What does specific heat capacity tell you about a material?"), "honors": [H(["21.5","21.6","21.7"], [54, 57, 61], "Q = mcΔT practice; problem 61 mixes iron and water.")]},
  3:  {"cpa": Cp(["22.1"], "Conduction: which materials do it well, and why?"), "honors": [H(["22.1","22.2","22.3","22.4","22.5"], [40, 43], "Three modes of transfer, then what makes a good emitter and absorber.")]},
  4:  {"cpa": Cp(["23.8"], "Why does temperature stop changing during a phase change?"), "honors": [H(["23.1","23.2","23.3","23.4","23.8"], [57, 58, 61], "Problem 61 is the full ice → steam staircase. Do it last.")]},
  6:  {"cpa": Cp(["21.1"], "Re-read: temperature is average molecular kinetic energy — find that sentence."), "honors": [H(["21.1"], [62, 63], "Kinetic theory: what is temperature a measure OF?"), H(["24.1"], [], "Absolute zero — what stops there?")]},
  7:  {"cpa": Cp(["24.2"], "State the first law of thermodynamics."), "honors": [H(["24.1","24.2","24.3"], [50], "First law is energy conservation with heat included. Adiabatic = no heat in or out.")]},
  8:  {"cpa": Cp(["24.4"], "Which way does heat flow on its own?"), "honors": [H(["24.4","24.6","24.7"], [43, 44], "Second law, disorder, entropy — why 'thermal pollution' is a relative term.")]},
  9:  {"cpa": Cp(["24.5"], "What limits how efficient a heat engine can be?"), "honors": [H(["24.5"], [51, 55, 57], "Ideal efficiency from the temperatures alone — problem 55 checks a real engine.")]},
  10: {"cpa": None, "honors": [H(["22.4","22.5"], [44], "Atmospheric entry: a meteor is a radiator. What decides how bright?")]},
  11: {"cpa": None, "honors": [H(["22.6","22.7"], [], "Newton's law of cooling and the greenhouse effect — both about radiation out.")]},
 },
 "unit-6": {
  1:  {"cpa": Cp(["25.3"], "What moves along a wave — the medium, or the energy?"), "honors": [H(["25.1","25.2","25.3"], [], "Vibration → wave. Find the definition of period and of frequency.")]},
  2:  {"cpa": Cp(["25.2"], "Define wavelength, amplitude, frequency, period."), "honors": [H(["25.2","25.5","25.6"], [61, 62], "Transverse vs. longitudinal — which way does the medium move in each?")]},
  3:  {"cpa": Cp(["25.4"], "Write the wave-speed equation and give the units of each term."), "honors": [H(["25.4"], [63, 64, 67], "v = fλ three ways; problem 67 is a radio wave.")]},
  4:  {"cpa": Cp(["29.2"], "State the law of reflection."), "honors": [H(["29.1","29.2","29.3","29.4"], [49, 50], "Problem 50 is a radar echo off an asteroid — our Day 15 in miniature.")]},
  5:  {"cpa": Cp(["29.6"], "Why does a wave bend when it enters a new medium?"), "honors": [H(["29.6","29.7","29.8","29.9"], [52], "Refraction of sound AND light — same cause, speed change.")]},
  6:  {"cpa": Cp(["31.2"], "When does diffraction matter most — big or small openings?"), "honors": [H(["31.1","31.2"], [], "Huygens' principle first; diffraction follows from it.")]},
  7:  {"cpa": Cp(["25.7"], "What happens when two waves meet crest-to-crest? Crest-to-trough?"), "honors": [H(["25.7","25.8"], [], "Interference, then standing waves as interference with itself."), H(["31.3","31.4"], [], "Young's experiment: the proof that light is a wave.")]},
  8:  {"cpa": Cp(["26.2"], "What is actually vibrating when sound travels through air?"), "honors": [H(["26.1","26.2","26.3"], [44, 49], "Sound is longitudinal. Problem 49 is middle C.")]},
  9:  {"cpa": Cp(["26.4"], "What is the speed of sound in air, and what changes it?"), "honors": [H(["26.4","26.6","26.7","26.8"], [45, 47, 48], "Echo problems, then natural frequency and resonance.")]},
  11: {"cpa": Cp(["25.9"], "Describe the Doppler effect for a passing siren."), "honors": [H(["25.9","25.10","25.11"], [], "Doppler → bow waves → shock waves: the same idea at three speeds."), H(["26.5","26.10"], [51, 52], "Loudness and beats.")]},
  12: {"cpa": Cp(["27.3"], "Light is an electromagnetic wave — what is waving?"), "honors": [H(["27.1","27.2","27.3","27.4"], [57, 58, 59], "Speed of light, then c = fλ practice.")]},
  13: {"cpa": Cp(["29.3"], "Where is the image in a plane mirror, and is it real?"), "honors": [H(["29.3"], [49, 51], "Virtual images — problem 51 (spider in the mirror) is the classic.")]},
  14: {"cpa": Cp(["30.1"], "Converging vs. diverging — what does each do to parallel rays?"), "honors": [H(["30.1","30.2","30.3","30.4"], [], "Ray diagrams: three rays locate every image.")]},
  15: {"cpa": None, "honors": [H(["29.5"], [50], "Reflection of sound is radar's grandfather."), H(["27.2"], [64], "Problem 64: a laser pulse to the moon and back — the radar timing calculation.")]},
  16: {"cpa": None, "honors": [H(["27.3"], [], "Color is frequency."), H(["22.4"], [], "Hotter emitters peak at higher frequency — Wien's law in words.")]},
  17: {"cpa": None, "honors": [H(["25.5","25.6"], [55], "Earthquakes send both wave types; problem 55 uses the lag between them.")]},
 },
 "unit-7": {
  1:  {"cpa": Cp(["32.1"], "Like charges ___, unlike charges ___."), "honors": [H(["32.1","32.2","32.4"], [], "Charge is conserved; conductors vs. insulators.")]},
  2:  {"cpa": Cp(["32.3"], "Write Coulomb's law. What does it look like?"), "honors": [H(["32.3"], [47, 48], "Inverse-square, again. Compare to gravitation as you read.")]},
  3:  {"cpa": Cp(["33.1"], "What is an electric field, and how do you draw one?"), "honors": [H(["33.1","33.2","33.3"], [36, 38], "Field = force per charge. Shielding follows.")]},
  4:  {"cpa": Cp(["33.5"], "Voltage is energy per ___."), "honors": [H(["33.4","33.5","33.6"], [35, 39, 40], "Electric PE, then potential, then capacitors.")]},
  5:  {"cpa": Cp(["34.2"], "Define current and its unit."), "honors": [H(["34.1","34.2","34.3"], [59, 60], "Current needs a potential difference — what provides it?")]},
  6:  {"cpa": Cp(["34.5"], "State Ohm's law and rearrange it for I."), "honors": [H(["34.4","34.5","34.6"], [61, 67], "Resistance, Ohm's law, and why a shock is about current not voltage.")]},
  7:  {"cpa": Cp(["35.3"], "In a series circuit, what is the same at every point?"), "honors": [H(["35.1","35.2","35.3"], [48, 49], "Series: one path, current shared, voltages add.")]},
  8:  {"cpa": Cp(["35.4"], "In a parallel circuit, what is the same across every branch?"), "honors": [H(["35.4","35.7"], [51, 53], "Parallel: voltage shared, currents add — and why fuses exist.")]},
  9:  {"cpa": Cp(["35.6"], "How do you reduce a combination circuit step by step?"), "honors": [H(["35.5","35.6"], [54, 58], "Schematics, then compound circuits. Problem 58 derives the parallel rule.")]},
  11: {"cpa": Cp(["34.11"], "Write the electric power equation and its unit."), "honors": [H(["34.11"], [68, 69, 74], "P = IV, then the two other forms via Ohm's law.")]},
  12: {"cpa": Cp(["36.2"], "What is a magnetic field, and how do you see one?"), "honors": [H(["36.1","36.2","36.3","36.4","36.9"], [], "Poles, fields, domains — and Earth's field, which the magnetosphere day needs.")]},
  13: {"cpa": Cp(["36.5"], "What did Oersted discover?"), "honors": [H(["36.5","36.6","36.7"], [], "Currents make fields; fields push on moving charges and on wires.")]},
  14: {"cpa": Cp(["37.1"], "What has to CHANGE to induce a voltage?"), "honors": [H(["37.1","37.2"], [], "Faraday's law in words: more loops, faster change, bigger voltage.")]},
  15: {"cpa": Cp(["37.3"], "A motor and a generator are the same device run backward — how?"), "honors": [H(["36.8"], [], "Meters to motors."), H(["37.3","37.4"], [52, 53], "Generators, AC, and the motor/generator comparison.")]},
  16: {"cpa": None, "honors": [H(["36.9","36.6"], [], "Earth's field deflects moving charges — that is the magnetosphere.")]},
  17: {"cpa": None, "honors": [H(["37.5","37.6"], [59], "Transformers and power transmission — why the grid runs at high voltage.")]},
 },
}
