-- ============================================================================
-- 20260903_pp_w00_day1_hybrid.sql — Project Physics Week 0 · Day 1 hybrid lesson
-- The MVP Physics (program `projects`) Day 1 page carries the EN/ES "The Briefing"
-- deck (public/decks/unit-1-sei/) and the lesson-plan moments as SEI capture blocks:
-- Do Now → Briefing (read like an analyst) → Notice · Wonder (lobby-ready) → the
-- six question shapes (live poll) → Physics can / people decide (gated checkpoint)
-- → the year map → exit ticket → self-rating → tonight.
-- Also attaches each Unit 1 day's authored deck (src/data/lesson-decks.ts) as the
-- first block of that lesson so Present can open it (P-1).
-- Idempotent: strips any earlier d1-* / deck blocks before re-appending. Applied to
-- PhysicsAPP 2026-09-03 through the Supabase connector; kept here so the projects
-- generator migration (20260902_program_projects.sql) can be re-run without losing it —
-- re-run THIS file after it.
-- ============================================================================

update public.lessons set content_blocks = jsonb_set(content_blocks, '{blocks}',
  (select jsonb_agg(b) from jsonb_array_elements(content_blocks->'blocks') b where (b->>'id') not like 'd1-%')
  || $$[
  {"id":"d1-deck","type":"deck","src":"/decks/unit-1-sei/U1 Day 1 - The Briefing (SEI).html","title":"Day 1 — The Briefing (EN/ES)","slideMap":[{"slide":0,"section":0},{"slide":4,"section":1},{"slide":10,"section":2},{"slide":14,"section":3},{"slide":16,"section":4},{"slide":18,"section":5},{"slide":22,"section":5}],"note":"Slides come in EN/ES pairs. The map sends student devices to the section that matches the pair you are on (P-1/P-4)."},
  {"id":"d1-fiction","type":"callout","variant":"tip","title":"This is fiction. The physics is real. · Esto es ficción. La física es real.","markdown":"We have one year to figure it out. · Tenemos un año para resolverlo.\n\n**Day 1 · The Briefing · El Informe.** Today you walk in cold. A NASA briefing reports an object, **2026-XJ**, on a path toward Earth. · Hoy entras sin saber nada. Un informe de la NASA reporta un objeto, **2026-XJ**, en camino hacia la Tierra."},
  {"id":"d1-fig-approach","type":"figure","src":"/images/sei/2026-xj-approach.svg","alt":"Earth on the left, the object 2026-XJ upper right, a dashed arrow from the object toward Earth, labeled with distance about 1.2 × 10^8 km and velocity about 8,500 m/s; mass is marked as estimated and composition, rotation and hit-or-miss are marked as unknown.","caption":"Where 2026-XJ is right now — and what we do not know. · Dónde está 2026-XJ ahora — y lo que no sabemos.","align":"full"},
  {"id":"d1-donow","type":"sentence_frame","capture":true,"targetId":"pp.w00.predict-lock","xp":5,"frame":"If an object were heading toward Earth, I would want to know ___ first, because ___.","wordBank":["how fast · qué tan rápido","where · dónde","when · cuándo","how big · qué tan grande","what it is made of · de qué está hecho","can we stop it · podemos detenerlo"],"frames":[{"level":1,"text":"I would want to know [how fast / where / when / how big] first.","text_l1":{"es":"Querría saber primero [qué tan rápido / dónde / cuándo / qué tan grande]."}},{"level":2,"text":"I would want to know ___ first, because ___.","text_l1":{"es":"Querría saber ___ primero, porque ___."}},{"level":3,"text":"First, I would ask ___","text_l1":{"es":"Primero preguntaría ___"}}],"sei":{"prompt_l1":{"es":"PARA EMPEZAR · Si supieras que un objeto se dirige hacia la Tierra, ¿qué querrías saber primero? Escribe una pregunta. Guárdala — la vas a necesitar en diez minutos."},"talkFirst":true,"modes":["text"],"tier2Terms":["predict"]},"note":"DO NOW · as you sit down. Collect a few aloud — no wrong answers today. This primes the notice/wonder."},
  {"id":"d1-briefing","type":"prose","markdown":"## NASA Planetary Defense · Briefing 001 · Informe 001\n\n**SUBJECT · ASUNTO:** Near-Earth Object 2026-XJ — Initial Trajectory Assessment · Evaluación inicial de trayectoria\n\n1. **DISCOVERY · DESCUBRIMIENTO.** Object 2026-XJ was detected 11 days ago by the ATLAS survey. Three stations confirm an Earth-approaching trajectory. · Detectado hace 11 días; tres estaciones confirman una trayectoria de aproximación a la Tierra.\n2. **CURRENT BEST DATA · MEJORES DATOS.** Distance to Earth: **1.2 × 10⁸ km** (± 50,000 km). Velocity: approximately **8,500 m/s** (± 200 m/s), directed 15° off the Earth-line. Mass estimate: **3.5 × 10¹¹ kg**, inferred from brightness — *low confidence*. · Distancia 1.2 × 10⁸ km; velocidad ≈ 8,500 m/s; masa estimada 3.5 × 10¹¹ kg — *baja confianza*.\n3. **WHAT WE DO NOT KNOW · LO QUE NO SABEMOS.** Composition (rock, metal, or rubble). Rotation state. Whether solar gravity will bend its path. Whether it will hit at all. · Composición. Rotación. Si la gravedad solar desviará su trayectoria. Si llegará a impactar.\n4. **ASSESSMENT · EVALUACIÓN.** Impact risk **cannot yet be excluded**. Close approach approximately one year out. · El riesgo de impacto aún no puede descartarse. Máximo acercamiento en ≈ un año.\n5. **ACTION · ACCIÓN.** Analysis teams convene today. First position projection due in 22 days. · Los equipos de análisis se reúnen hoy. Primera proyección de posición en 22 días.\n\n*DIST: ANALYSIS TEAMS · FITCHBURG STATION — PDCO Watch Desk*\n\n> Read like an analyst: what is **stated**, what is **estimated**, what is **unknown**? · Lee como analista: ¿qué se **afirma**, qué se **estima**, qué se **desconoce**?"},
  {"id":"d1-anim","type":"animation_3d","animationSlug":"approach-geometry","caption":"Before any equations: watch where 2026-XJ actually is and what nine months of approach looks like. · Antes de cualquier ecuación: mira dónde está 2026-XJ y cómo se ven nueve meses de aproximación."},
  {"id":"d1-analyst","type":"observation","capture":true,"targetId":"pp.w00.predict-lock","xp":5,"patternPrompt":"Read like an analyst. Name one thing the briefing STATES as measured, and one thing it only ESTIMATES.","interpretPrompt":"Name one thing we DON'T know yet — and say why that matters for predicting where it goes.","patternFrame":"The briefing states ___. It only estimates ___.","comparatives":["distance · distancia","velocity · velocidad","mass · masa","composition · composición","rotation · rotación","± uncertainty · incertidumbre"],"sei":{"prompt_l1":{"es":"Lee como analista. Nombra una cosa que el informe AFIRMA (medida) y una que solo ESTIMA. Luego: una cosa que todavía NO sabemos, y por qué importa para predecir adónde va."},"frames":[{"level":1,"text":"The briefing states [distance / velocity]. It only estimates [mass].","text_l1":{"es":"El informe afirma [distancia / velocidad]. Solo estima [masa]."}},{"level":2,"text":"The briefing states ___. It only estimates ___ because ___.","text_l1":{"es":"El informe afirma ___. Solo estima ___ porque ___."}},{"level":3,"text":"Stated: ___ · Estimated: ___ · Unknown: ___","text_l1":{"es":"Afirmado: ___ · Estimado: ___ · Desconocido: ___"}}],"talkFirst":true,"modes":["text"],"tier2Terms":["estimate","uncertainty"]},"note":"3–10 min: hand out the paper briefing. Silent read 5 min. Then the reveal line."},
  {"id":"d1-groups","type":"callout","variant":"tip","title":"Groups of 3–4 · chart paper · 15 min · Grupos de 3–4 · rotafolio · 15 min","markdown":"**NOTICE × 3 · OBSERVO × 3** — facts you can point to in the briefing. No interpretation yet. · Hechos que puedes señalar. Todavía sin interpretar.\n\n**WONDER × 5+ · ME PREGUNTO × 5+** — questions the briefing raises. Big or small — write them all. · Preguntas que plantea el informe. Grandes o pequeñas — escríbelas todas.\n\n**Gallery walk · Recorrido de galería:** 01 Post your chart. · Pega tu rotafolio. 02 Star one wonder from another group you wish you had written. · Marca con una estrella una pregunta de otro grupo. 03 Come back ready to say what kind of questions this class is generating. · Regresa listo para decir qué tipo de preguntas genera esta clase.\n\n*These charts stay up all year. · Estos rotafolios se quedan todo el año.*"},
  {"id":"d1-fig-nw","type":"figure","src":"/images/sei/notice-wonder.svg","alt":"Two chart-paper columns: NOTICE times three with the frame I notice that blank, and WONDER times five with the frame I wonder whether blank, in English and Spanish.","caption":"Notice · Wonder · Observo · Me pregunto","align":"full"},
  {"id":"d1-nw","type":"observation","capture":true,"lobbyReady":true,"targetId":"pp.w00.timeline","xp":5,"patternPrompt":"NOTICE × 3 — three facts you can point to in the briefing.","interpretPrompt":"WONDER — your best two questions, plus the one you starred on another group's chart.","patternFrame":"I notice that ___.","comparatives":["I notice that ___ · Observo que ___","I wonder whether ___ · Me pregunto si ___","I wonder how ___ · Me pregunto cómo ___","distance · distancia","velocity · velocidad","mass · masa","uncertainty · incertidumbre"],"sei":{"prompt_l1":{"es":"OBSERVO × 3 — tres hechos que puedes señalar en el informe. ME PREGUNTO — tus dos mejores preguntas, más la que marcaste con estrella en el rotafolio de otro grupo."},"frames":[{"level":1,"text":"I notice that [the distance / the velocity / the mass] is ___. I wonder whether ___.","text_l1":{"es":"Observo que [la distancia / la velocidad / la masa] es ___. Me pregunto si ___."}},{"level":2,"text":"I notice that ___. I wonder whether ___, because ___.","text_l1":{"es":"Observo que ___. Me pregunto si ___, porque ___."}},{"level":3,"text":"Notice: ___ · Wonder: ___","text_l1":{"es":"Observo: ___ · Me pregunto: ___"}}],"talkFirst":true,"modes":["text","sketch"],"tier2Terms":["notice"]},"note":"10–25 min. SAVE the chart paper; you will point back to it in May. Watch for: is it visible already? do we know exactly what it is? — note, do not correct yet."},
  {"id":"d1-shape","type":"question","capture":true,"targetId":"pp.w00.predict-lock","xp":5,"question":{"prompt":"Your questions have a shape. Which shape does YOUR Do-Now question have?","options":[{"id":"fast","icon":"⏱","text":"How fast?","text_l1":{"es":"¿Qué tan rápido?"}},{"id":"where","icon":"📍","text":"Where?","text_l1":{"es":"¿Dónde?"}},{"id":"when","icon":"📅","text":"When?","text_l1":{"es":"¿Cuándo?"}},{"id":"big","icon":"📏","text":"How big?","text_l1":{"es":"¿Qué tan grande?"}},{"id":"made","icon":"🪨","text":"What is it made of?","text_l1":{"es":"¿De qué está hecho?"}},{"id":"stop","icon":"🛑","text":"Can we stop it?","text_l1":{"es":"¿Podemos detenerlo?"}}],"explain":"Write your question again, in its shape. · Escribe tu pregunta otra vez, en su forma."},"sei":{"prompt_l1":{"es":"Tus preguntas tienen forma. ¿Qué forma tiene TU pregunta de Para Empezar?"},"visual":{"src":"/images/sei/2026-xj-approach.svg","alt":"Earth and the approaching object 2026-XJ with distance and velocity labeled."},"frames":[{"level":1,"text":"My question is a [how fast / where / when] question.","text_l1":{"es":"Mi pregunta es de [qué tan rápido / dónde / cuándo]."}},{"level":2,"text":"My question asks ___, so it is a ___ question.","text_l1":{"es":"Mi pregunta pregunta ___, así que es una pregunta de ___."}}],"modes":["choice"]},"note":"25–40 min: full-class sort of the board into the six shapes. OPEN THIS AS A LIVE POLL — no right answer; the bars show what the room is asking. Each question becomes a mission phase."},
  {"id":"d1-fig-cancant","type":"figure","src":"/images/sei/physics-can-cant.svg","alt":"Two columns. Physics can: measure, model, predict — where will it be, how fast, how big a push, how sure. People decide: tell the public, who pays, is one-in-a-hundred worth it, whose cities. Test: can you measure it and apply a law to it?","caption":"Which questions can physics answer? · ¿Qué preguntas puede responder la física?","align":"full"},
  {"id":"d1-cancant","type":"question","capture":true,"gate":true,"targetId":"pp.w00.predict-lock","xp":5,"question":{"prompt":"“Where will it be in six months?” — which column does this question belong in?","options":[{"id":"can","icon":"📏","text":"PHYSICS CAN answer — measure, model, predict","text_l1":{"es":"LA FÍSICA PUEDE responder — medir, modelar, predecir"},"feedback":"Yes. Position is something you can measure, and a law of motion applies to it. · Sí: la posición se mide y una ley del movimiento se aplica."},{"id":"people","icon":"⚖","text":"PEOPLE DECIDE — physics is only the input","text_l1":{"es":"LO DECIDEN LAS PERSONAS — la física es solo el insumo"},"feedback":"Not this one. The test: can you measure it and apply a law to it? Here you can. · No. La prueba: ¿puedes medirlo y aplicarle una ley? Aquí sí."}],"correctOptionId":"can","explain":"Now write ONE question from the board that belongs in the OTHER column, and say why. · Ahora escribe UNA pregunta del pizarrón que pertenece a la OTRA columna y di por qué."},"sei":{"prompt_l1":{"es":"«¿Dónde estará en seis meses?» — ¿a qué columna pertenece esta pregunta?"},"frames":[{"level":1,"text":"___ is a people question because it is about [money / who is told / whether to act].","text_l1":{"es":"___ es una pregunta de personas porque trata de [dinero / a quién se informa / si actuar]."}},{"level":2,"text":"___ belongs in the other column because ___.","text_l1":{"es":"___ pertenece a la otra columna porque ___."}},{"level":3,"text":"Other column: ___ — because ___","text_l1":{"es":"Otra columna: ___ — porque ___"}}],"talkFirst":true,"modes":["choice"],"tier2Terms":["measure","decide"]},"note":"Sort again — two columns. Physics hands you the left column; the right one still needs you as a citizen. Keep both columns on chart paper. Gate: students must get the column right before moving on."},
  {"id":"d1-year","type":"prose","markdown":"## The year is the puzzle · El año es el rompecabezas\n\nEach shape of question becomes a mission phase. · Cada forma de pregunta se convierte en una fase de la misión.\n\n| Phase · Fase | Question · Pregunta | Mission job · Trabajo |\n|---|---|---|\n| **Track it · Rastrearlo** | How fast? Where? When? · ¿Qué tan rápido? ¿Dónde? ¿Cuándo? | Read its track and predict its position. · Leer su trayectoria y predecir su posición. |\n| **Move it · Moverlo** | How big a push? · ¿Cuánto empuje? | Forces, momentum, impulse. · Fuerzas, momento, impulso. |\n| **Sense it · Detectarlo** | What is it made of? · ¿De qué está hecho? | Waves, sound, light. · Ondas, sonido, luz. |\n| **Power it · Energizarlo** | Can we stop it? · ¿Podemos detenerlo? | Energy and the machines that deliver it. · Energía y las máquinas que la entregan. |\n\n### Phase 1's puzzle piece · La pieza de la Fase 1\n\n**How fast — and where — will it arrive?** · **¿Qué tan rápido — y dónde — va a llegar?**\n\nTo answer it, we need the language of motion: **position, velocity, acceleration**. We start building it next class. · Para responderla necesitamos el lenguaje del movimiento: **posición, velocidad, aceleración**. Empezamos la próxima clase.\n\n*22 days to the first projection. · 22 días para la primera proyección.*"},
  {"id":"d1-exit","type":"exit_ticket","capture":true,"targetId":"pp.w00.predict-lock","xp":5,"talkFirst":true,"prompt":"EXIT TICKET · Write ONE question about the asteroid you really want answered this year.","frame":"This year I want to know ___, because ___.","sei":{"prompt_l1":{"es":"BOLETO DE SALIDA · Escribe UNA pregunta sobre el asteroide que de verdad quieras que se responda este año."},"visual":{"src":"/images/sei/2026-xj-approach.svg","alt":"Earth and the approaching object 2026-XJ."},"frames":[{"level":1,"text":"This year I want to know [how fast / where / when / how big / if we can stop it].","text_l1":{"es":"Este año quiero saber [qué tan rápido / dónde / cuándo / qué tan grande / si podemos detenerlo]."}},{"level":2,"text":"This year I want to know ___, because ___.","text_l1":{"es":"Este año quiero saber ___, porque ___."}},{"level":3,"text":"My question: ___","text_l1":{"es":"Mi pregunta: ___"}}],"wordBank":["how fast · qué tan rápido","where · dónde","when · cuándo","how big · qué tan grande","stop it · detenerlo","because · porque"],"talkFirst":true,"modes":["text","sketch"],"tier2Terms":["predict"]},"note":"Read them tonight — physics vs social questions, note non-engagers, catch misconceptions."},
  {"id":"d1-rate","type":"marzano","capture":true,"targetId":"pp.w00.predict-lock","note":"RATE YOURSELF on today's target: can I say what we know, what we don't, and what tools we'd need? Opens after the exit ticket on lobby days (MC-6)."},
  {"id":"d1-tonight","type":"callout","variant":"tip","title":"Tonight · Esta noche","markdown":"Hewitt Chapter 2 (Motion) — introduction. The vocabulary starts next class. · Hewitt Capítulo 2 (Movimiento) — introducción. El vocabulario empieza la próxima clase."}
]$$::jsonb), updated_at = now()
where slug = 'pp-w00';

-- Unit 1 (program physics): the authored deck for each day, first in the document.
-- Day 1 is the "Something Is Coming" briefing deck (self-hosted from the design source),
-- not the older Inertia Anchor bundle (decided with Craig 2026-09-03).
with m(slug, src, title) as (values
 ('u1-d01', $$/decks/unit-1/U1 Day 1 - The Briefing.html$$, 'Day 1 — The Briefing: Something Is Coming'),
 ('u1-d02', $$/decks/unit-1/Day 2 - Motion Vocabulary.dc.html$$, 'Day 2 — Motion Vocabulary'),
 ('u1-d03', $$/decks/unit-1/Day 3 - Graphs as Claims.dc.html$$, 'Day 3 — Graphs as Claims'),
 ('u1-d04', $$/decks/unit-1/Day 4 - Velocity-Time and Vectors.dc.html$$, 'Day 4 — Velocity-Time and Vectors'),
 ('u1-d05', $$/decks/unit-1/Day 5 - Predicting Position.dc.html$$, 'Day 5 — Predicting Position'),
 ('u1-d06', $$/decks/unit-1/Day 6 - Vector Addition.dc.html$$, 'Day 6 — Vector Addition'),
 ('u1-d07', $$/decks/unit-1/Day 7 - Acceleration.dc.html$$, 'Day 7 — Acceleration'),
 ('u1-d08', $$/decks/unit-1/Day 8 - Equations of Motion.dc.html$$, 'Day 8 — Equations of Motion'),
 ('u1-d09', $$/decks/unit-1/Day 9 - Newton's 1st Law.dc.html$$, $$Day 9 — Newton's 1st Law$$),
 ('u1-d10', $$/decks/unit-1/Day 10 - Forces.dc.html$$, 'Day 10 — Forces'),
 ('u1-d11', $$/decks/unit-1/Day 11-12 - Derive F=ma.dc.html$$, 'Day 11–12 — Derive F=ma'),
 ('u1-d12', $$/decks/unit-1/Day 11-12 - Derive F=ma.dc.html$$, 'Day 11–12 — Derive F=ma'),
 ('u1-d13', $$/decks/unit-1/Day 13 - F=ma in Practice.dc.html$$, 'Day 13 — F=ma in Practice'),
 ('u1-d14', $$/decks/unit-1/Day 14 - Newton's 3rd Law.dc.html$$, $$Day 14 — Newton's 3rd Law$$),
 ('u1-d15', $$/decks/unit-1/Day 15 - Free Body Diagrams 1.dc.html$$, 'Day 15 — Free Body Diagrams 1'),
 ('u1-d16', $$/decks/unit-1/Day 16 - Free Body Diagrams 2.dc.html$$, 'Day 16 — Free Body Diagrams 2'),
 ('u1-d17', $$/decks/unit-1/Day 17 - Friction.dc.html$$, 'Day 17 — Friction'),
 ('u1-d18', $$/decks/unit-1/Day 18 - Equilibrium.dc.html$$, 'Day 18 — Equilibrium'),
 ('u1-d19', $$/decks/unit-1/Day 19 - Workshop.dc.html$$, 'Day 19 — Workshop'),
 ('u1-d20', $$/decks/unit-1/Day 20 - Synthesis.dc.html$$, 'Day 20 — Synthesis'),
 ('u1-d21', $$/decks/unit-1/Day 21-22 - Transfer Task.dc.html$$, 'Day 21–22 — Transfer Task'),
 ('u1-d22', $$/decks/unit-1/Day 21-22 - Transfer Task.dc.html$$, 'Day 21–22 — Transfer Task'))
update public.lessons l set content_blocks = jsonb_set(l.content_blocks, '{blocks}',
  jsonb_build_array(jsonb_build_object('id', 'deck-' || m.slug, 'type', 'deck', 'src', m.src, 'title', m.title, 'note', 'Authored deck for this day (src/data/lesson-decks.ts). No slideMap yet: follow mode maps slides to sections proportionally; add slideMap to pin it.'))
  || (select coalesce(jsonb_agg(b), '[]'::jsonb) from jsonb_array_elements(l.content_blocks->'blocks') b where b->>'type' <> 'deck'))
from m where l.slug = m.slug;

-- ----------------------------------------------------------------------------
-- u1-d02 (CPA + Honors) · Day 2 hybrid — reader carries the deck's teaching moments
-- (decided with Craig 2026-09-03: "follow what you did for MVP Day 1"). Applied to
-- PhysicsAPP the same day; idempotent (skips when d2-warmup already exists).
-- Order: deck · target · warm-up figure + predict-before-observe question ·
-- vocab prose/wall/diagram + vocabulary frame · walk-it callout/sim/track sketch ·
-- asteroid thread + direction figure + GATED checkpoint · Solve it (GEWA) ·
-- exit ticket · self-rating · tonight.
-- ----------------------------------------------------------------------------
update public.lessons set content_blocks = jsonb_set(content_blocks, '{blocks}', (
 with b as (select b, o from jsonb_array_elements(content_blocks->'blocks') with ordinality as x(b,o))
 select
   (select jsonb_build_array(b || '{"slideMap":[{"slide":0,"section":0},{"slide":3,"section":1},{"slide":4,"section":2},{"slide":5,"section":3},{"slide":6,"section":5},{"slide":7,"section":5}],"note":"Title/target/two-correct-answers → warm-up section; vocab board → vocabulary; walk-it sim → the track sketch; asteroid thread → the direction checkpoint; honors hinge + exit slide → exit ticket. Solve it (GEWA) is not on the deck — students reach it on their own."}'::jsonb) from b where b->>'id'='deck-u1-d02')
 || (select jsonb_build_array(b) from b where b->>'id'='b1')
 || $$[
 {"id":"d2-fig-warm","type":"figure","src":"/images/sei/door-desk-door.svg","alt":"A walk from the door to the desk and back: the yellow path there and back is the distance walked; the start and end are the same point, so the displacement is zero.","caption":"Warm-up: walk to your desk and back. · Camina a tu escritorio y regresa.","align":"full"},
 {"id":"d2-warmup","type":"question","capture":true,"targetId":"u1.vocab-position-distance-displacement","xp":5,"question":{"prompt":"WARM-UP · You walk from the door to your desk and back. How far did you go?","options":[{"id":"twice","icon":"👣","text":"Twice the door-to-desk distance","text_l1":{"es":"El doble de la distancia puerta–escritorio"},"feedback":"That is your DISTANCE — the total path you walked, a scalar. It is a correct answer to one of the two questions. · Esa es tu DISTANCIA — el camino total, un escalar."},{"id":"zero","icon":"📍","text":"Zero — I ended where I started","text_l1":{"es":"Cero — terminé donde empecé"},"feedback":"That is your DISPLACEMENT — your change in position, a vector. Also correct, to the other question. · Ese es tu DESPLAZAMIENTO — tu cambio de posición, un vector."},{"id":"both","icon":"⚖","text":"Both — they answer different questions","text_l1":{"es":"Las dos — responden preguntas diferentes"},"feedback":"Yes. Distance answers how much path; displacement answers where you ended up relative to where you started. That contradiction is today's engine. · Sí: la distancia dice cuánto camino; el desplazamiento dice dónde terminaste."}],"correctOptionId":"both","explain":"Which question does each answer answer? · ¿Qué pregunta responde cada respuesta?"},"sei":{"prompt_l1":{"es":"PARA EMPEZAR · Caminas de la puerta a tu escritorio y regresas. ¿Qué tan lejos fuiste?"},"frames":[{"level":1,"text":"“Twice” answers [how much path / where I ended]. “Zero” answers [how much path / where I ended].","text_l1":{"es":"«El doble» responde [cuánto camino / dónde terminé]. «Cero» responde [cuánto camino / dónde terminé]."}},{"level":2,"text":"“Twice” answers ___ and “zero” answers ___, so both are right.","text_l1":{"es":"«El doble» responde ___ y «cero» responde ___, así que las dos son correctas."}}],"talkFirst":true,"modes":["choice"]},"note":"Slide 3 · Two Correct Answers. Have a student actually walk it first. Collect both answers aloud before revealing. Wrong + sure here is the misconception flag for the day."}
 ]$$::jsonb
 || (select jsonb_agg(b order by o) from b where b->>'id' in ('b3','b4','bl1mm'))
 || $$[
 {"id":"d2-vocab","type":"sentence_frame","capture":true,"targetId":"u1.vocab-position-distance-displacement","xp":5,"frame":"Position is ___ (a point). Distance is ___ (a scalar). Displacement is ___ (a vector).","wordBank":["where an object is · dónde está","relative to an origin · respecto a un origen","total path length · longitud total del camino","change in position · cambio de posición","no direction · sin dirección","has direction · tiene dirección","posición","distancia","desplazamiento"],"frames":[{"level":1,"text":"Position = [where it is / how far it went]. Distance = [total path / change in position]. Displacement = [total path / change in position, with direction].","text_l1":{"es":"Posición = [dónde está / cuánto recorrió]. Distancia = [camino total / cambio de posición]. Desplazamiento = [camino total / cambio de posición, con dirección]."}},{"level":2,"text":"Position is ___. Distance is ___, so it is a scalar. Displacement is ___, so it is a vector.","text_l1":{"es":"La posición es ___. La distancia es ___, así que es un escalar. El desplazamiento es ___, así que es un vector."}},{"level":3,"text":"In my own words: position ___ · distance ___ · displacement ___","text_l1":{"es":"Con mis palabras: posición ___ · distancia ___ · desplazamiento ___"}}],"sei":{"prompt_l1":{"es":"VOCABULARIO · El lenguaje del movimiento. Completa: posición, distancia, desplazamiento — y di cuál es escalar y cuál es vector. Cognados: posición · distancia · desplazamiento."},"talkFirst":true,"modes":["text"],"tier2Terms":["relative","precise"]},"note":"Slide 4 · Vocabulary Board. Cognates front-loaded. Extension: is speed a scalar or a vector? Defend it."}
 ]$$::jsonb
 || (select jsonb_agg(b order by o) from b where b->>'id' in ('spd2','b5','b6'))
 || (select jsonb_build_array(b) from b where b->>'id'='b2')
 || $$[
 {"id":"d2-fig-thread","type":"figure","src":"/images/sei/same-million-km.svg","alt":"Earth in the center. One object moves one million kilometers toward Earth, another moves one million kilometers away. Same distance, opposite displacement.","caption":"Same million km — opposite outcomes. · Los mismos millones de km — resultados opuestos.","align":"full"},
 {"id":"d2-thread","type":"question","capture":true,"gate":true,"targetId":"u1.vocab-position-distance-displacement","xp":5,"question":{"prompt":"NASA reports 2026-XJ moved 1,000,000 km since yesterday. Does that tell you whether it is getting closer to Earth?","options":[{"id":"yes","icon":"📏","text":"Yes — a million km is a lot of motion","text_l1":{"es":"Sí — un millón de km es mucho movimiento"},"feedback":"Not yet. A million km toward Earth and a million km away are the same DISTANCE. You need the direction. · Todavía no: hacia o alejándose son la misma DISTANCIA. Necesitas la dirección."},{"id":"no","icon":"🧭","text":"No — I need the direction: that is displacement, not distance","text_l1":{"es":"No — necesito la dirección: eso es desplazamiento, no distancia"},"feedback":"Right. Position now plus displacement over time — with direction — is what predicts where it goes. · Correcto: posición más desplazamiento con dirección es lo que predice adónde va."},{"id":"speed","icon":"⏱","text":"Only if I also know its speed","text_l1":{"es":"Solo si también sé su rapidez"},"feedback":"Speed tells you how fast, not which way. You still need direction. · La rapidez dice qué tan rápido, no hacia dónde."}],"correctOptionId":"no","explain":"Say it in one sentence: why can't distance traveled alone tell us if it hits us? · ¿Por qué la distancia sola no dice si nos golpea?"},"sei":{"prompt_l1":{"es":"HILO DEL ASTEROIDE · La NASA reporta que 2026-XJ se movió 1,000,000 km desde ayer. ¿Eso te dice si se está acercando a la Tierra?"},"frames":[{"level":1,"text":"Distance alone cannot tell us because it has no [direction / size].","text_l1":{"es":"La distancia sola no nos dice porque no tiene [dirección / tamaño]."}},{"level":2,"text":"Distance alone cannot tell us because ___. We need displacement because ___.","text_l1":{"es":"La distancia sola no nos dice porque ___. Necesitamos el desplazamiento porque ___."}},{"level":3,"text":"We need displacement because ___","text_l1":{"es":"Necesitamos el desplazamiento porque ___"}}],"talkFirst":true,"modes":["choice"],"tier2Terms":["predict","direction"]},"note":"Slide 6 · Asteroid Thread. TALK MOVES: why can't distance traveled alone tell us if it hits us? Gate: the direction idea must land before Solve it."}
 ]$$::jsonb
 || (select jsonb_build_array(b) from b where b->>'id'='b7')
 || (select jsonb_agg(b order by o) from b where b->>'id' in ('b9','b8'))
 || $$[
 {"id":"d2-tonight","type":"callout","variant":"tip","title":"Tonight · Esta noche","markdown":"Hewitt Ch. 2 — Position, Velocity, and Vectors sections (~5 pages). Mark anything confusing. · Hewitt Cap. 2 — secciones de posición, velocidad y vectores. Marca lo que te confunda."}
 ]$$::jsonb
)), updated_at = now()
where slug='u1-d02' and not exists (select 1 from jsonb_array_elements(content_blocks->'blocks') b where b->>'id'='d2-warmup');

-- ----------------------------------------------------------------------------
-- u1-d03 (CPA + Honors) · Day 3 hybrid — Graphs as Claims. Same pattern as Day 2.
-- Order: deck · target · thread · honors framing · two-cars figure + Do Now
-- question · graph prose/wall/graph/callout/worked example · flat-section figure +
-- GATED slope checkpoint · investigation callout + data table · read & practice ·
-- Solve it · sketch · claim callout + exit ticket (CPA frame / honors JUSTIFY) ·
-- self-rating · tonight. Idempotent (skips when d3-donow exists).
-- ----------------------------------------------------------------------------
update public.lessons set content_blocks = jsonb_set(content_blocks, '{blocks}', (
 with b as (select b, o from jsonb_array_elements(content_blocks->'blocks') with ordinality as x(b,o))
 select
   (select jsonb_build_array(b || '{"slideMap":[{"slide":0,"section":0},{"slide":4,"section":1},{"slide":5,"section":2},{"slide":6,"section":1},{"slide":7,"section":6},{"slide":10,"section":7}],"note":"Title/Do Now/target/thread → Do Now section; velocity vocab + slope explorer → the slope checkpoint; match-the-graph sim → the investigation data table; claim / your turn / exit → exit ticket; rate yourself → self-rating. Read & practice, Solve it and the sketch are not on the deck."}'::jsonb) from b where b->>'id'='deck-u1-d03')
 || (select jsonb_agg(b order by o) from b where b->>'id' in ('b1','b2','h1','h2'))
 || $$[
 {"id":"d3-fig-cars","type":"figure","src":"/images/sei/two-cars.svg","alt":"Two cars drive from Fitchburg to Worcester along the same road. Car A takes one hour, Car B takes two hours. Same displacement — same velocity?","caption":"Do Now · Two cars, one road. · Dos autos, un camino.","align":"full"},
 {"id":"d3-donow","type":"question","capture":true,"targetId":"u1.capture-pt-graph","xp":5,"question":{"prompt":"DO NOW · Two cars drive Fitchburg → Worcester. One takes 1 hour, one takes 2. Are they moving the same way?","options":[{"id":"same","icon":"🟰","text":"Yes — same start, same end, same direction","text_l1":{"es":"Sí — mismo inicio, mismo final, misma dirección"},"feedback":"Same DISPLACEMENT, yes. But “moving the same way” also asks how fast. That is where velocity comes in. · Mismo DESPLAZAMIENTO, sí. Pero «moverse igual» también pregunta qué tan rápido."},{"id":"velocity","icon":"🧭","text":"Same direction, but not the same velocity — velocity is how fast AND which way","text_l1":{"es":"Misma dirección, pero no la misma velocidad — la velocidad es qué tan rápido Y hacia dónde"},"feedback":"Yes. Same displacement over different times means different velocities. Velocity = displacement ÷ time, with direction. · Sí: mismo desplazamiento en tiempos distintos → velocidades distintas."},{"id":"dir","icon":"↔","text":"No — they must be going different directions","text_l1":{"es":"No — deben ir en direcciones diferentes"},"feedback":"Look again: both go Fitchburg → Worcester. The direction is the same; the time is not. · Los dos van de Fitchburg a Worcester. La dirección es la misma; el tiempo no."}],"correctOptionId":"velocity","explain":"Defend your answer in one sentence. · Defiende tu respuesta en una oración."},"sei":{"prompt_l1":{"es":"PARA EMPEZAR · Dos autos van de Fitchburg a Worcester. Uno tarda 1 hora, el otro 2. ¿Se mueven de la misma manera?"},"frames":[{"level":1,"text":"They have the same [displacement / velocity] but a different [displacement / velocity].","text_l1":{"es":"Tienen el mismo [desplazamiento / velocidad] pero diferente [desplazamiento / velocidad]."}},{"level":2,"text":"They have the same ___ but different ___, because velocity is ___.","text_l1":{"es":"Tienen el mismo ___ pero diferente ___, porque la velocidad es ___."}}],"talkFirst":true,"modes":["choice"]},"note":"Slide 2 · Do Now, 5 min. Quick check distance vs displacement first, then collect both intuitions before naming velocity."}
 ]$$::jsonb
 || (select jsonb_agg(b order by o) from b where b->>'id' in ('b3','b4','bl2gpt','b9','b5'))
 || $$[
 {"id":"d3-fig-flat","type":"figure","src":"/images/sei/flat-section.svg","alt":"A position-time graph in three parts: a rising line labeled walking away, a flat section in the middle marked with a question, and a falling line labeled coming back. The slope is the velocity.","caption":"Ride the slope: what is the object doing in part ②? · ¿Qué hace el objeto en la parte ②?","align":"full"},
 {"id":"d3-slope","type":"question","capture":true,"gate":true,"targetId":"u1.capture-pt-graph","xp":5,"question":{"prompt":"On a POSITION-time graph, the line goes flat for a while (part ②). What is the object doing?","options":[{"id":"const","icon":"➡","text":"Moving at a constant speed","text_l1":{"es":"Moviéndose a rapidez constante"},"feedback":"That is the classic mix-up. Flat means the POSITION is not changing — the slope is zero, so the velocity is zero. Flat = stopped. · Plano significa que la POSICIÓN no cambia: pendiente cero, velocidad cero. Plano = detenido."},{"id":"stopped","icon":"🛑","text":"Stopped — its position is not changing","text_l1":{"es":"Detenido — su posición no cambia"},"feedback":"Right. Zero slope = zero velocity. The graph claims the object stayed put. · Correcto: pendiente cero = velocidad cero."},{"id":"back","icon":"↩","text":"Moving back toward the start","text_l1":{"es":"Regresando hacia el inicio"},"feedback":"Moving back would be a line sloping DOWN (part ③). Flat is neither up nor down. · Regresar sería una línea que baja (parte ③). Plano no sube ni baja."}],"correctOptionId":"stopped","explain":"Say why in one sentence, using the word slope. · Di por qué en una oración, usando la palabra pendiente."},"sei":{"prompt_l1":{"es":"En una gráfica de POSICIÓN contra tiempo, la línea se pone plana un rato (parte ②). ¿Qué está haciendo el objeto?"},"frames":[{"level":1,"text":"Flat means the slope is [zero / constant], so the object is [stopped / moving].","text_l1":{"es":"Plano significa que la pendiente es [cero / constante], así que el objeto está [detenido / en movimiento]."}},{"level":2,"text":"The slope is ___, so the velocity is ___. The object is ___.","text_l1":{"es":"La pendiente es ___, así que la velocidad es ___. El objeto está ___."}}],"talkFirst":true,"modes":["choice"],"tier2Terms":["slope","constant"]},"note":"Slide 7 · Slope Explorer. Park the tangent on the flat section live to break the 'flat means constant speed' misconception. Gate: must land before the investigation."}
 ]$$::jsonb
 || (select jsonb_agg(b order by o) from b where b->>'id' in ('spl2lab','b6','spd3read','bce04','b8','b10'))
 || $$[
 {"id":"d3-claim","type":"callout","variant":"tip","title":"A graph is a claim · Una gráfica es una afirmación","markdown":"Every position-time graph claims: **“the object moved like THIS.”** A claim can be tested. What motion would make this graph **wrong**? If you can name the motion that would falsify it, you understand the graph. · Toda gráfica de posición-tiempo afirma: «el objeto se movió ASÍ». Una afirmación se puede poner a prueba. ¿Qué movimiento haría que esta gráfica fuera **falsa**?\n\n**Your turn · Tu turno:** pick one graph from the investigation. 01 Tell its story — start, direction, speed. 02 Name ONE motion that would prove this graph false. · Elige una gráfica. 01 Cuenta su historia — inicio, dirección, rapidez. 02 Nombra UN movimiento que la haría falsa."},
 {"id":"d3-exit","type":"exit_ticket","capture":true,"targetId":"u1.capture-pt-graph","xp":5,"visibilityTrack":"cpa","talkFirst":true,"prompt":"EXIT TICKET · Pick one position-time graph from today. This graph claims the object ___. It would be WRONG if ___.","frame":"This position-time graph claims the object ___. It would be WRONG if ___.","sei":{"prompt_l1":{"es":"BOLETO DE SALIDA · Elige una gráfica de posición-tiempo de hoy. Esta gráfica afirma que el objeto ___. Sería FALSA si ___."},"visual":{"src":"/images/sei/flat-section.svg","alt":"A position-time graph with a rising, a flat and a falling section."},"frames":[{"level":1,"text":"This graph claims the object [moved away / stopped / came back]. It would be wrong if the object [moved away / stopped / came back].","text_l1":{"es":"Esta gráfica afirma que el objeto [se alejó / se detuvo / regresó]. Sería falsa si el objeto [se alejó / se detuvo / regresó]."}},{"level":2,"text":"This graph claims the object ___ because the slope is ___. It would be wrong if ___.","text_l1":{"es":"Esta gráfica afirma que el objeto ___ porque la pendiente es ___. Sería falsa si ___."}},{"level":3,"text":"Claim: ___ · Would be wrong if: ___","text_l1":{"es":"Afirmación: ___ · Sería falsa si: ___"}}],"wordBank":["moved away · se alejó","came back · regresó","stopped · se detuvo","steady · constante","faster · más rápido","slope · pendiente"],"talkFirst":true,"modes":["text","sketch"],"tier2Terms":["claim"]},"note":"Slide 10 · Exit Ticket (CPA frame). Honors students get h3 (JUSTIFY) in the same spot. Open response — write or sketch."}
 ]$$::jsonb
 || (select jsonb_build_array(b) from b where b->>'id'='h3')
 || (select jsonb_build_array(b || '{"targetId":"u1.capture-pt-graph"}'::jsonb) from b where b->>'id'='b11')
 || $$[
 {"id":"d3-tonight","type":"callout","variant":"tip","title":"Tonight · Esta noche","markdown":"Hewitt Ch. 2 — Velocity and Graphs sections (~3–4 pages). · Hewitt Cap. 2 — secciones de velocidad y gráficas.\n\n**Honors:** the falsification paragraph — what motion would prove your graph wrong?"}
 ]$$::jsonb
)), updated_at = now()
where slug='u1-d03' and not exists (select 1 from jsonb_array_elements(content_blocks->'blocks') b where b->>'id'='d3-donow');

-- ----------------------------------------------------------------------------
-- Unit 1 self-ratings pointed at target slugs that do not exist (u1.d1 … u1.d22,
-- l5-first-law), so MC-2 calibration could never join them. Re-point each marzano
-- at the day's real target (applied 2026-09-03).
-- ----------------------------------------------------------------------------
with m(bad, good) as (values
 ('u1.d1','u1.anchor-know-unknow'),('u1.d3','u1.capture-pt-graph'),('u1.d4','u1.read-vt-graph-components'),('u1.d5','u1.predict-position-uncertainty'),('u1.d6','u1.vectors-tip-to-tail'),('u1.d7','u1.acceleration-rate-of-change'),('u1.d8','u1.pick-equation-of-motion'),('l5-first-law','u1.newtons-first-law-inertia'),('u1.d10','u1.identify-forces'),('u1.d11','u1.lab-accel-vs-mass'),('u1.d12','u1.lab-accel-vs-force'),('u1.d13','u1.fma-solve-net-force'),('u1.d14','u1.third-law-pairs'),('u1.d15','u1.draw-fbd'),('u1.d16','u1.net-force-from-fbd'),('u1.d17','u1.friction-static-kinetic'),('u1.d18','u1.equilibrium-find-unknown'),('u1.d19-fbd','u1.draw-fbd'),('u1.d19-vectors','u1.vectors-tip-to-tail'),('u1.d19-fma','u1.fma-solve-net-force'),('u1.d19','u1.workshop-self-diagnose'),('u1.d20','u1.d20-locate-the-arc'),('u1.d21','u1.d08-kinematics-transfer'),('u1.d22','u1.d08-kinematics-transfer'))
update public.lessons l set content_blocks = jsonb_set(l.content_blocks, '{blocks}', (
  select jsonb_agg(case when b->>'type'='marzano' and exists (select 1 from m where m.bad = b->>'targetId') then b || jsonb_build_object('targetId', (select good from m where m.bad = b->>'targetId')) else b end order by o)
  from jsonb_array_elements(l.content_blocks->'blocks') with ordinality as x(b,o)))
where l.unit_id='unit-1' and exists (select 1 from jsonb_array_elements(l.content_blocks->'blocks') b join m on m.bad = b->>'targetId' where b->>'type'='marzano');

-- ----------------------------------------------------------------------------
-- u1-d01 (CPA + Honors) · Day 1 hybrid — The Briefing. Reader carries the deck's
-- moments: Do Now · briefing memo + analyst read · Notice·Wonder (lobby-ready) ·
-- six-shape live poll · GATED can/can't · the year · exit ticket · self-rating ·
-- tonight. Idempotent (skips when d1c-donow exists).
-- ----------------------------------------------------------------------------
update public.lessons set content_blocks = jsonb_set(content_blocks, '{blocks}', (
 with b as (select b, o from jsonb_array_elements(content_blocks->'blocks') with ordinality as x(b,o))
 select
   (select jsonb_build_array(b || '{"slideMap":[{"slide":0,"section":0},{"slide":3,"section":1},{"slide":5,"section":2},{"slide":7,"section":3},{"slide":8,"section":4},{"slide":9,"section":5},{"slide":11,"section":5}]}'::jsonb) from b where b->>'id'='deck-u1-d01')
 || (select jsonb_agg(b order by o) from b where b->>'id' in ('b1','b2'))
 || $$[
 {"id":"d1c-fiction","type":"callout","variant":"tip","title":"This is fiction. The physics is real.","markdown":"We have one year to figure it out. Today you walk in cold: a NASA briefing reports an object, **2026-XJ**, on a path toward Earth."},
 {"id":"d1c-fig","type":"figure","src":"/images/sei/2026-xj-approach.svg","alt":"Earth on the left, the object 2026-XJ upper right, a dashed arrow from the object toward Earth labeled with distance about 1.2 × 10^8 km and velocity about 8,500 m/s; mass marked as estimated; composition, rotation and hit-or-miss marked unknown.","caption":"Where 2026-XJ is right now — and what we do not know.","align":"full"},
 {"id":"d1c-donow","type":"sentence_frame","capture":true,"targetId":"u1.anchor-know-unknow","xp":5,"frame":"If an object were heading toward Earth, I would want to know ___ first, because ___.","wordBank":["how fast","where","when","how big","what it is made of","can we stop it"],"frames":[{"level":1,"text":"I would want to know [how fast / where / when / how big] first.","text_l1":{"es":"Querría saber primero [qué tan rápido / dónde / cuándo / qué tan grande]."}},{"level":2,"text":"I would want to know ___ first, because ___.","text_l1":{"es":"Querría saber ___ primero, porque ___."}},{"level":3,"text":"First, I would ask ___","text_l1":{"es":"Primero preguntaría ___"}}],"sei":{"prompt_l1":{"es":"PARA EMPEZAR · Si supieras que un objeto se dirige hacia la Tierra, ¿qué querrías saber primero? Escribe una pregunta y guárdala."},"talkFirst":true,"modes":["text"]},"note":"DO NOW · as you sit down. Collect a few aloud — no wrong answers today."}
 ]$$::jsonb
 || $$[
 {"id":"d1c-briefing","type":"prose","markdown":"## NASA Planetary Defense · Briefing 001\n\n**SUBJECT:** Near-Earth Object 2026-XJ — Initial Trajectory Assessment\n\n1. **DISCOVERY.** Object 2026-XJ was detected 11 days ago by the ATLAS survey. Follow-up observations from three stations confirm it is on an Earth-approaching trajectory.\n2. **CURRENT BEST DATA.** Distance to Earth: **1.2 × 10⁸ km** (± 50,000 km). Velocity: approximately **8,500 m/s** (± 200 m/s), directed 15° off the Earth-line. Mass estimate: **3.5 × 10¹¹ kg**, inferred from brightness — *low confidence*.\n3. **WHAT WE DO NOT KNOW.** Composition (rock, metal, or rubble). Rotation state. Whether its path will be significantly bent by solar gravity before arrival. Whether it will hit at all.\n4. **ASSESSMENT.** Impact risk **cannot yet be excluded**. Preliminary models place the close-approach window approximately one year out.\n5. **ACTION.** Analysis teams convene today. First position projection due in 22 days. Teams should develop tools for describing motion, predicting position, and quantifying uncertainty.\n\n*DIST: ANALYSIS TEAMS · FITCHBURG STATION — PDCO Watch Desk*\n\n> Read like an analyst: what is **stated**, what is **estimated**, what is **unknown**?"}
 ]$$::jsonb
 || (select jsonb_agg(b order by o) from b where b->>'id' in ('anim-d1-approach'))
 || $$[
 {"id":"d1c-analyst","type":"observation","capture":true,"targetId":"u1.anchor-know-unknow","xp":5,"patternPrompt":"Read like an analyst. Name one thing the briefing STATES as measured, and one thing it only ESTIMATES.","interpretPrompt":"Name one thing we DON'T know yet — and say why that matters for predicting where it goes.","patternFrame":"The briefing states ___. It only estimates ___.","comparatives":["distance","velocity","mass","composition","rotation","± uncertainty"],"sei":{"prompt_l1":{"es":"Lee como analista. Una cosa que el informe AFIRMA (medida), una que solo ESTIMA, y una que NO sabemos — y por qué importa."},"frames":[{"level":1,"text":"The briefing states [distance / velocity]. It only estimates [mass].","text_l1":{"es":"El informe afirma [distancia / velocidad]. Solo estima [masa]."}},{"level":2,"text":"The briefing states ___. It only estimates ___ because ___.","text_l1":{"es":"El informe afirma ___. Solo estima ___ porque ___."}}],"talkFirst":true,"modes":["text"]},"note":"3–10 min: hand out the paper briefing. Silent read 5 min. Then the reveal line: this is fiction — the physics is real."},
 {"id":"d1c-groups","type":"callout","variant":"tip","title":"Groups of 3–4 · chart paper · 15 min","markdown":"**NOTICE × 3** — facts you can point to in the briefing. No interpretation yet.\n\n**WONDER × 5+** — questions the briefing raises. Big or small — write them all.\n\n**Gallery walk:** 01 Post your chart. 02 Star one wonder from another group you wish you had written. 03 Come back ready to say what kind of questions this class is generating.\n\n*These charts stay up all year.*"},
 {"id":"d1c-fig-nw","type":"figure","src":"/images/sei/notice-wonder.svg","alt":"Two chart-paper columns: NOTICE times three with the frame I notice that blank, and WONDER times five with the frame I wonder whether blank.","caption":"Notice · Wonder","align":"full"},
 {"id":"d1c-nw","type":"observation","capture":true,"lobbyReady":true,"targetId":"u1.anchor-know-unknow","xp":5,"patternPrompt":"NOTICE × 3 — three facts you can point to in the briefing.","interpretPrompt":"WONDER — your best two questions, plus the one you starred on another group's chart.","patternFrame":"I notice that ___.","comparatives":["I notice that ___","I wonder whether ___","I wonder how ___","distance","velocity","mass","uncertainty"],"sei":{"prompt_l1":{"es":"OBSERVO × 3 — tres hechos del informe. ME PREGUNTO — tus dos mejores preguntas, más la que marcaste con estrella."},"frames":[{"level":1,"text":"I notice that [the distance / the velocity / the mass] is ___. I wonder whether ___.","text_l1":{"es":"Observo que [la distancia / la velocidad / la masa] es ___. Me pregunto si ___."}},{"level":2,"text":"I notice that ___. I wonder whether ___, because ___.","text_l1":{"es":"Observo que ___. Me pregunto si ___, porque ___."}}],"talkFirst":true,"modes":["text","sketch"]},"note":"10–25 min. SAVE the chart paper; you will point back to it in May. Misconceptions to note, not correct: is it visible already? do we know exactly what it is?"},
 {"id":"d1c-shape","type":"question","capture":true,"targetId":"u1.anchor-know-unknow","xp":5,"question":{"prompt":"Your questions have a shape. Which shape does YOUR Do-Now question have?","options":[{"id":"fast","icon":"⏱","text":"How fast?","text_l1":{"es":"¿Qué tan rápido?"}},{"id":"where","icon":"📍","text":"Where?","text_l1":{"es":"¿Dónde?"}},{"id":"when","icon":"📅","text":"When?","text_l1":{"es":"¿Cuándo?"}},{"id":"big","icon":"📏","text":"How big?","text_l1":{"es":"¿Qué tan grande?"}},{"id":"made","icon":"🪨","text":"What is it made of?","text_l1":{"es":"¿De qué está hecho?"}},{"id":"stop","icon":"🛑","text":"Can we stop it?","text_l1":{"es":"¿Podemos detenerlo?"}}],"explain":"Write your question again, in its shape."},"sei":{"prompt_l1":{"es":"Tus preguntas tienen forma. ¿Qué forma tiene TU pregunta?"},"visual":{"src":"/images/sei/2026-xj-approach.svg","alt":"Earth and the approaching object 2026-XJ."},"modes":["choice"]},"note":"25–40 min: sort the board into the six shapes. OPEN AS A LIVE POLL — no right answer; the bars show what the room is asking. Each question becomes a unit."},
 {"id":"d1c-fig-cc","type":"figure","src":"/images/sei/physics-can-cant.svg","alt":"Two columns. Physics can: measure, model, predict. People decide: tell the public, who pays, is one-in-a-hundred worth it, whose cities. Test: can you measure it and apply a law to it?","caption":"Which questions can physics answer?","align":"full"},
 {"id":"d1c-cancant","type":"question","capture":true,"gate":true,"targetId":"u1.anchor-know-unknow","xp":5,"question":{"prompt":"“Where will it be in six months?” — which column does this question belong in?","options":[{"id":"can","icon":"📏","text":"PHYSICS CAN answer — measure, model, predict","text_l1":{"es":"LA FÍSICA PUEDE responder"},"feedback":"Yes. Position is something you can measure, and a law of motion applies to it."},{"id":"people","icon":"⚖","text":"PEOPLE DECIDE — physics is only the input","text_l1":{"es":"LO DECIDEN LAS PERSONAS"},"feedback":"Not this one. The test: can you measure it and apply a law to it? Here you can."}],"correctOptionId":"can","explain":"Now write ONE question from the board that belongs in the OTHER column, and say why."},"sei":{"prompt_l1":{"es":"«¿Dónde estará en seis meses?» — ¿a qué columna pertenece?"},"frames":[{"level":1,"text":"___ is a people question because it is about [money / who is told / whether to act].","text_l1":{"es":"___ es una pregunta de personas porque trata de [dinero / a quién se informa / si actuar]."}},{"level":2,"text":"___ belongs in the other column because ___.","text_l1":{"es":"___ pertenece a la otra columna porque ___."}}],"talkFirst":true,"modes":["choice"]},"note":"Sort again — two columns. Physics hands you the left column; the right one still needs you as a citizen. Keep both on chart paper."},
 {"id":"d1c-year","type":"prose","markdown":"## The year is the puzzle\n\nEach shape of question becomes a unit: **U1** Motion & Forces · **U2** Gravitation & Fields · **U3** Momentum & Collisions · **U4** Energy & Work · **U5** Thermal Physics · **U6** Waves, Sound & Light · **U7** Electricity & Magnetism · **U8** The Car Project.\n\n### Unit 1's puzzle piece\n\n**How fast — and where — will it arrive?** To answer it, we need the language of motion: **position, velocity, acceleration**. We start building it tomorrow. *22 days to the first projection.*"}
 ]$$::jsonb
 || (select jsonb_agg(b order by o) from b where b->>'id' in ('b3','sp1'))
 || (select jsonb_build_array(b || '{"talkFirst":true,"xp":5,"prompt":"EXIT TICKET · Write ONE question about the asteroid you really want answered this year — and say whether it is a question physics can answer, or one people must decide.","frame":"This year I want to know ___. That is a [physics / people] question because ___.","sei":{"prompt_l1":{"es":"BOLETO DE SALIDA · Escribe UNA pregunta sobre el asteroide que de verdad quieras que se responda este año — y di si es una pregunta de física o una que deciden las personas."},"visual":{"src":"/images/sei/2026-xj-approach.svg","alt":"Earth and the approaching object 2026-XJ."},"frames":[{"level":1,"text":"This year I want to know [how fast / where / when / how big / if we can stop it]. That is a [physics / people] question.","text_l1":{"es":"Este año quiero saber [qué tan rápido / dónde / cuándo / qué tan grande / si podemos detenerlo]. Es una pregunta de [física / personas]."}},{"level":2,"text":"This year I want to know ___. That is a ___ question because ___.","text_l1":{"es":"Este año quiero saber ___. Es una pregunta de ___ porque ___."}}],"talkFirst":true,"modes":["text","sketch"]}}'::jsonb) from b where b->>'id'='b9')
 || (select jsonb_build_array(b) from b where b->>'id'='b11')
 || $$[
 {"id":"d1c-tonight","type":"callout","variant":"tip","title":"Tonight","markdown":"Hewitt Chapter 2 (Motion) — introduction. The vocabulary starts tomorrow."}
 ]$$::jsonb
)), updated_at = now()
where slug='u1-d01' and not exists (select 1 from jsonb_array_elements(content_blocks->'blocks') b where b->>'id'='d1c-donow');
