-- ============================================================================
-- 20260903_pp_w00_day1_hybrid.sql — Project Physics Week 0 · Day 1 hybrid lesson
-- The MVP Physics (program `projects`) Day 1 page carries the EN/ES "The Briefing"
-- deck (public/decks/unit-1-sei/) and the lesson-plan moments as SEI capture blocks:
-- Do Now → Briefing (read like an analyst) → Notice · Wonder (lobby-ready) → the
-- six question shapes (live poll) → Physics can / people decide (gated checkpoint)
-- → the year map → exit ticket → self-rating → tonight.
-- Also attaches each Unit 1 day's authored deck (src/data/lesson-decks.ts) as the
-- first block of that lesson so Present can open it (P-1).
-- Idempotent: strips any earlier d1-* / deck blocks before re-appending. Applied to
-- PhysicsAPP 2026-09-03 through the Supabase connector; kept here so the projects
-- generator migration (20260902_program_projects.sql) can be re-run without losing it —
-- re-run THIS file after it.
-- ============================================================================

update public.lessons set content_blocks = jsonb_set(content_blocks, '{blocks}',
  (select jsonb_agg(b) from jsonb_array_elements(content_blocks->'blocks') b where (b->>'id') not like 'd1-%')
  || $$[
  {"id":"d1-deck","type":"deck","src":"/decks/unit-1-sei/U1 Day 1 - The Briefing (SEI).html","title":"Day 1 — The Briefing (EN/ES)","slideMap":[{"slide":0,"section":0},{"slide":4,"section":1},{"slide":10,"section":2},{"slide":14,"section":3},{"slide":16,"section":4},{"slide":18,"section":5},{"slide":22,"section":5}],"note":"Slides come in EN/ES pairs. The map sends student devices to the section that matches the pair you are on (P-1/P-4)."},
  {"id":"d1-fiction","type":"callout","variant":"tip","title":"This is fiction. The physics is real. · Esto es ficción. La física es real.","markdown":"We have one year to figure it out. · Tenemos un año para resolverlo.\n\n**Day 1 · The Briefing · El Informe.** Today you walk in cold. A NASA briefing reports an object, **2026-XJ**, on a path toward Earth. · Hoy entras sin saber nada. Un informe de la NASA reporta un objeto, **2026-XJ**, en camino hacia la Tierra."},
  {"id":"d1-fig-approach","type":"figure","src":"/images/sei/2026-xj-approach.svg","alt":"Earth on the left, the object 2026-XJ upper right, a dashed arrow from the object toward Earth, labeled with distance about 1.2 × 10^8 km and velocity about 8,500 m/s; mass is marked as estimated and composition, rotation and hit-or-miss are marked as unknown.","caption":"Where 2026-XJ is right now — and what we do not know. · Dónde está 2026-XJ ahora — y lo que no sabemos.","align":"full"},
  {"id":"d1-donow","type":"sentence_frame","capture":true,"targetId":"pp.w00.predict-lock","xp":5,"frame":"If an object were heading toward Earth, I would want to know ___ first, because ___.","wordBank":["how fast · qué tan rápido","where · dónde","when · cuándo","how big · qué tan grande","what it is made of · de qué está hecho","can we stop it · podemos detenerlo"],"frames":[{"level":1,"text":"I would want to know [how fast / where / when / how big] first.","text_l1":{"es":"Querría saber primero [qué tan rápido / dónde / cuándo / qué tan grande]."}},{"level":2,"text":"I would want to know ___ first, because ___.","text_l1":{"es":"Querría saber ___ primero, porque ___."}},{"level":3,"text":"First, I would ask ___","text_l1":{"es":"Primero preguntaría ___"}}],"sei":{"prompt_l1":{"es":"PARA EMPEZAR · Si supieras que un objeto se dirige hacia la Tierra, ¿qué querrías saber primero? Escribe una pregunta. Guárdala — la vas a necesitar en diez minutos."},"talkFirst":true,"modes":["text"],"tier2Terms":["predict"]},"note":"DO NOW · as you sit down. Collect a few aloud — no wrong answers today. This primes the notice/wonder."},
  {"id":"d1-briefing","type":"prose","markdown":"## NASA Planetary Defense · Briefing 001 · Informe 001\n\n**SUBJECT · ASUNTO:** Near-Earth Object 2026-XJ — Initial Trajectory Assessment · Evaluación inicial de trayectoria\n\n1. **DISCOVERY · DESCUBRIMIENTO.** Object 2026-XJ was detected 11 days ago by the ATLAS survey. Three stations confirm an Earth-approaching trajectory. · Detectado hace 11 días; tres estaciones confirman una trayectoria de aproximación a la Tierra.\n2. **CURRENT BEST DATA · MEJORES DATOS.** Distance to Earth: **1.2 × 10⁸ km** (± 50,000 km). Velocity: approximately **8,500 m/s** (± 200 m/s), directed 15° off the Earth-line. Mass estimate: **3.5 × 10¹¹ kg**, inferred from brightness — *low confidence*. · Distancia 1.2 × 10⁸ km; velocidad ≈ 8,500 m/s; masa estimada 3.5 × 10¹¹ kg — *baja confianza*.\n3. **WHAT WE DO NOT KNOW · LO QUE NO SABEMOS.** Composition (rock, metal, or rubble). Rotation state. Whether solar gravity will bend its path. Whether it will hit at all. · Composición. Rotación. Si la gravedad solar desviará su trayectoria. Si llegará a impactar.\n4. **ASSESSMENT · EVALUACIÓN.** Impact risk **cannot yet be excluded**. Close approach approximately one year out. · El riesgo de impacto aún no puede descartarse. Máximo acercamiento en ≈ un año.\n5. **ACTION · ACCIÓN.** Analysis teams convene today. First position projection due in 22 days. · Los equipos de análisis se reúnen hoy. Primera proyección de posición en 22 días.\n\n*DIST: ANALYSIS TEAMS · FITCHBURG STATION — PDCO Watch Desk*\n\n> Read like an analyst: what is **stated**, what is **estimated**, what is **unknown**? · Lee como analista: ¿qué se **afirma**, qué se **estima**, qué se **desconoce**?"},
  {"id":"d1-anim","type":"animation_3d","animationSlug":"approach-geometry","caption":"Before any equations: watch where 2026-XJ actually is and what nine months of approach looks like. · Antes de cualquier ecuación: mira dónde está 2026-XJ y cómo se ven nueve meses de aproximación."},
  {"id":"d1-analyst","type":"observation","capture":true,"targetId":"pp.w00.predict-lock","xp":5,"patternPrompt":"Read like an analyst. Name one thing the briefing STATES as measured, and one thing it only ESTIMATES.","interpretPrompt":"Name one thing we DON'T know yet — and say why that matters for predicting where it goes.","patternFrame":"The briefing states ___. It only estimates ___.","comparatives":["distance · distancia","velocity · velocidad","mass · masa","composition · composición","rotation · rotación","± uncertainty · incertidumbre"],"sei":{"prompt_l1":{"es":"Lee como analista. Nombra una cosa que el informe AFIRMA (medida) y una que solo ESTIMA. Luego: una cosa que todavía NO sabemos, y por qué importa para predecir adónde va."},"frames":[{"level":1,"text":"The briefing states [distance / velocity]. It only estimates [mass].","text_l1":{"es":"El informe afirma [distancia / velocidad]. Solo estima [masa]."}},{"level":2,"text":"The briefing states ___. It only estimates ___ because ___.","text_l1":{"es":"El informe afirma ___. Solo estima ___ porque ___."}},{"level":3,"text":"Stated: ___ · Estimated: ___ · Unknown: ___","text_l1":{"es":"Afirmado: ___ · Estimado: ___ · Desconocido: ___"}}],"talkFirst":true,"modes":["text"],"tier2Terms":["estimate","uncertainty"]},"note":"3–10 min: hand out the paper briefing. Silent read 5 min. Then the reveal line."},
  {"id":"d1-groups","type":"callout","variant":"tip","title":"Groups of 3–4 · chart paper · 15 min · Grupos de 3–4 · rotafolio · 15 min","markdown":"**NOTICE × 3 · OBSERVO × 3** — facts you can point to in the briefing. No interpretation yet. · Hechos que puedes señalar. Todavía sin interpretar.\n\n**WONDER × 5+ · ME PREGUNTO × 5+** — questions the briefing raises. Big or small — write them all. · Preguntas que plantea el informe. Grandes o pequeñas — escríbelas todas.\n\n**Gallery walk · Recorrido de galería:** 01 Post your chart. · Pega tu rotafolio. 02 Star one wonder from another group you wish you had written. · Marca con una estrella una pregunta de otro grupo. 03 Come back ready to say what kind of questions this class is generating. · Regresa listo para decir qué tipo de preguntas genera esta clase.\n\n*These charts stay up all year. · Estos rotafolios se quedan todo el año.*"},
  {"id":"d1-fig-nw","type":"figure","src":"/images/sei/notice-wonder.svg","alt":"Two chart-paper columns: NOTICE times three with the frame I notice that blank, and WONDER times five with the frame I wonder whether blank, in English and Spanish.","caption":"Notice · Wonder · Observo · Me pregunto","align":"full"},
  {"id":"d1-nw","type":"observation","capture":true,"lobbyReady":true,"targetId":"pp.w00.timeline","xp":5,"patternPrompt":"NOTICE × 3 — three facts you can point to in the briefing.","interpretPrompt":"WONDER — your best two questions, plus the one you starred on another group's chart.","patternFrame":"I notice that ___.","comparatives":["I notice that ___ · Observo que ___","I wonder whether ___ · Me pregunto si ___","I wonder how ___ · Me pregunto cómo ___","distance · distancia","velocity · velocidad","mass · masa","uncertainty · incertidumbre"],"sei":{"prompt_l1":{"es":"OBSERVO × 3 — tres hechos que puedes señalar en el informe. ME PREGUNTO — tus dos mejores preguntas, más la que marcaste con estrella en el rotafolio de otro grupo."},"frames":[{"level":1,"text":"I notice that [the distance / the velocity / the mass] is ___. I wonder whether ___.","text_l1":{"es":"Observo que [la distancia / la velocidad / la masa] es ___. Me pregunto si ___."}},{"level":2,"text":"I notice that ___. I wonder whether ___, because ___.","text_l1":{"es":"Observo que ___. Me pregunto si ___, porque ___."}},{"level":3,"text":"Notice: ___ · Wonder: ___","text_l1":{"es":"Observo: ___ · Me pregunto: ___"}}],"talkFirst":true,"modes":["text","sketch"],"tier2Terms":["notice"]},"note":"10–25 min. SAVE the chart paper; you will point back to it in May. Watch for: is it visible already? do we know exactly what it is? — note, do not correct yet."},
  {"id":"d1-shape","type":"question","capture":true,"targetId":"pp.w00.predict-lock","xp":5,"question":{"prompt":"Your questions have a shape. Which shape does YOUR Do-Now question have?","options":[{"id":"fast","icon":"⏱","text":"How fast?","text_l1":{"es":"¿Qué tan rápido?"}},{"id":"where","icon":"📍","text":"Where?","text_l1":{"es":"¿Dónde?"}},{"id":"when","icon":"📅","text":"When?","text_l1":{"es":"¿Cuándo?"}},{"id":"big","icon":"📏","text":"How big?","text_l1":{"es":"¿Qué tan grande?"}},{"id":"made","icon":"🪨","text":"What is it made of?","text_l1":{"es":"¿De qué está hecho?"}},{"id":"stop","icon":"🛑","text":"Can we stop it?","text_l1":{"es":"¿Podemos detenerlo?"}}],"explain":"Write your question again, in its shape. · Escribe tu pregunta otra vez, en su forma."},"sei":{"prompt_l1":{"es":"Tus preguntas tienen forma. ¿Qué forma tiene TU pregunta de Para Empezar?"},"visual":{"src":"/images/sei/2026-xj-approach.svg","alt":"Earth and the approaching object 2026-XJ with distance and velocity labeled."},"frames":[{"level":1,"text":"My question is a [how fast / where / when] question.","text_l1":{"es":"Mi pregunta es de [qué tan rápido / dónde / cuándo]."}},{"level":2,"text":"My question asks ___, so it is a ___ question.","text_l1":{"es":"Mi pregunta pregunta ___, así que es una pregunta de ___."}}],"modes":["choice"]},"note":"25–40 min: full-class sort of the board into the six shapes. OPEN THIS AS A LIVE POLL — no right answer; the bars show what the room is asking. Each question becomes a mission phase."},
  {"id":"d1-fig-cancant","type":"figure","src":"/images/sei/physics-can-cant.svg","alt":"Two columns. Physics can: measure, model, predict — where will it be, how fast, how big a push, how sure. People decide: tell the public, who pays, is one-in-a-hundred worth it, whose cities. Test: can you measure it and apply a law to it?","caption":"Which questions can physics answer? · ¿Qué preguntas puede responder la física?","align":"full"},
  {"id":"d1-cancant","type":"question","capture":true,"gate":true,"targetId":"pp.w00.predict-lock","xp":5,"question":{"prompt":"“Where will it be in six months?” — which column does this question belong in?","options":[{"id":"can","icon":"📏","text":"PHYSICS CAN answer — measure, model, predict","text_l1":{"es":"LA FÍSICA PUEDE responder — medir, modelar, predecir"},"feedback":"Yes. Position is something you can measure, and a law of motion applies to it. · Sí: la posición se mide y una ley del movimiento se aplica."},{"id":"people","icon":"⚖","text":"PEOPLE DECIDE — physics is only the input","text_l1":{"es":"LO DECIDEN LAS PERSONAS — la física es solo el insumo"},"feedback":"Not this one. The test: can you measure it and apply a law to it? Here you can. · No. La prueba: ¿puedes medirlo y aplicarle una ley? Aquí sí."}],"correctOptionId":"can","explain":"Now write ONE question from the board that belongs in the OTHER column, and say why. · Ahora escribe UNA pregunta del pizarrón que pertenece a la OTRA columna y di por qué."},"sei":{"prompt_l1":{"es":"«¿Dónde estará en seis meses?» — ¿a qué columna pertenece esta pregunta?"},"frames":[{"level":1,"text":"___ is a people question because it is about [money / who is told / whether to act].","text_l1":{"es":"___ es una pregunta de personas porque trata de [dinero / a quién se informa / si actuar]."}},{"level":2,"text":"___ belongs in the other column because ___.","text_l1":{"es":"___ pertenece a la otra columna porque ___."}},{"level":3,"text":"Other column: ___ — because ___","text_l1":{"es":"Otra columna: ___ — porque ___"}}],"talkFirst":true,"modes":["choice"],"tier2Terms":["measure","decide"]},"note":"Sort again — two columns. Physics hands you the left column; the right one still needs you as a citizen. Keep both columns on chart paper. Gate: students must get the column right before moving on."},
  {"id":"d1-year","type":"prose","markdown":"## The year is the puzzle · El año es el rompecabezas\n\nEach shape of question becomes a mission phase. · Cada forma de pregunta se convierte en una fase de la misión.\n\n| Phase · Fase | Question · Pregunta | Mission job · Trabajo |\n|---|---|---|\n| **Track it · Rastrearlo** | How fast? Where? When? · ¿Qué tan rápido? ¿Dónde? ¿Cuándo? | Read its track and predict its position. · Leer su trayectoria y predecir su posición. |\n| **Move it · Moverlo** | How big a push? · ¿Cuánto empuje? | Forces, momentum, impulse. · Fuerzas, momento, impulso. |\n| **Sense it · Detectarlo** | What is it made of? · ¿De qué está hecho? | Waves, sound, light. · Ondas, sonido, luz. |\n| **Power it · Energizarlo** | Can we stop it? · ¿Podemos detenerlo? | Energy and the machines that deliver it. · Energía y las máquinas que la entregan. |\n\n### Phase 1's puzzle piece · La pieza de la Fase 1\n\n**How fast — and where — will it arrive?** · **¿Qué tan rápido — y dónde — va a llegar?**\n\nTo answer it, we need the language of motion: **position, velocity, acceleration**. We start building it next class. · Para responderla necesitamos el lenguaje del movimiento: **posición, velocidad, aceleración**. Empezamos la próxima clase.\n\n*22 days to the first projection. · 22 días para la primera proyección.*"},
  {"id":"d1-exit","type":"exit_ticket","capture":true,"targetId":"pp.w00.predict-lock","xp":5,"talkFirst":true,"prompt":"EXIT TICKET · Write ONE question about the asteroid you really want answered this year.","frame":"This year I want to know ___, because ___.","sei":{"prompt_l1":{"es":"BOLETO DE SALIDA · Escribe UNA pregunta sobre el asteroide que de verdad quieras que se responda este año."},"visual":{"src":"/images/sei/2026-xj-approach.svg","alt":"Earth and the approaching object 2026-XJ."},"frames":[{"level":1,"text":"This year I want to know [how fast / where / when / how big / if we can stop it].","text_l1":{"es":"Este año quiero saber [qué tan rápido / dónde / cuándo / qué tan grande / si podemos detenerlo]."}},{"level":2,"text":"This year I want to know ___, because ___.","text_l1":{"es":"Este año quiero saber ___, porque ___."}},{"level":3,"text":"My question: ___","text_l1":{"es":"Mi pregunta: ___"}}],"wordBank":["how fast · qué tan rápido","where · dónde","when · cuándo","how big · qué tan grande","stop it · detenerlo","because · porque"],"talkFirst":true,"modes":["text","sketch"],"tier2Terms":["predict"]},"note":"Read them tonight — physics vs social questions, note non-engagers, catch misconceptions."},
  {"id":"d1-rate","type":"marzano","capture":true,"targetId":"pp.w00.predict-lock","note":"RATE YOURSELF on today's target: can I say what we know, what we don't, and what tools we'd need? Opens after the exit ticket on lobby days (MC-6)."},
  {"id":"d1-tonight","type":"callout","variant":"tip","title":"Tonight · Esta noche","markdown":"Hewitt Chapter 2 (Motion) — introduction. The vocabulary starts next class. · Hewitt Capítulo 2 (Movimiento) — introducción. El vocabulario empieza la próxima clase."}
]$$::jsonb), updated_at = now()
where slug = 'pp-w00';

-- Unit 1 (program physics): the authored deck for each day, first in the document.
-- Day 1 is the "Something Is Coming" briefing deck (self-hosted from the design source),
-- not the older Inertia Anchor bundle (decided with Craig 2026-09-03).
with m(slug, src, title) as (values
 ('u1-d01', $$/decks/unit-1/U1 Day 1 - The Briefing.html$$, 'Day 1 — The Briefing: Something Is Coming'),
 ('u1-d02', $$/decks/unit-1/Day 2 - Motion Vocabulary.dc.html$$, 'Day 2 — Motion Vocabulary'),
 ('u1-d03', $$/decks/unit-1/Day 3 - Graphs as Claims.dc.html$$, 'Day 3 — Graphs as Claims'),
 ('u1-d04', $$/decks/unit-1/Day 4 - Velocity-Time and Vectors.dc.html$$, 'Day 4 — Velocity-Time and Vectors'),
 ('u1-d05', $$/decks/unit-1/Day 5 - Predicting Position.dc.html$$, 'Day 5 — Predicting Position'),
 ('u1-d06', $$/decks/unit-1/Day 6 - Vector Addition.dc.html$$, 'Day 6 — Vector Addition'),
 ('u1-d07', $$/decks/unit-1/Day 7 - Acceleration.dc.html$$, 'Day 7 — Acceleration'),
 ('u1-d08', $$/decks/unit-1/Day 8 - Equations of Motion.dc.html$$, 'Day 8 — Equations of Motion'),
 ('u1-d09', $$/decks/unit-1/Day 9 - Newton's 1st Law.dc.html$$, $$Day 9 — Newton's 1st Law$$),
 ('u1-d10', $$/decks/unit-1/Day 10 - Forces.dc.html$$, 'Day 10 — Forces'),
 ('u1-d11', $$/decks/unit-1/Day 11-12 - Derive F=ma.dc.html$$, 'Day 11–12 — Derive F=ma'),
 ('u1-d12', $$/decks/unit-1/Day 11-12 - Derive F=ma.dc.html$$, 'Day 11–12 — Derive F=ma'),
 ('u1-d13', $$/decks/unit-1/Day 13 - F=ma in Practice.dc.html$$, 'Day 13 — F=ma in Practice'),
 ('u1-d14', $$/decks/unit-1/Day 14 - Newton's 3rd Law.dc.html$$, $$Day 14 — Newton's 3rd Law$$),
 ('u1-d15', $$/decks/unit-1/Day 15 - Free Body Diagrams 1.dc.html$$, 'Day 15 — Free Body Diagrams 1'),
 ('u1-d16', $$/decks/unit-1/Day 16 - Free Body Diagrams 2.dc.html$$, 'Day 16 — Free Body Diagrams 2'),
 ('u1-d17', $$/decks/unit-1/Day 17 - Friction.dc.html$$, 'Day 17 — Friction'),
 ('u1-d18', $$/decks/unit-1/Day 18 - Equilibrium.dc.html$$, 'Day 18 — Equilibrium'),
 ('u1-d19', $$/decks/unit-1/Day 19 - Workshop.dc.html$$, 'Day 19 — Workshop'),
 ('u1-d20', $$/decks/unit-1/Day 20 - Synthesis.dc.html$$, 'Day 20 — Synthesis'),
 ('u1-d21', $$/decks/unit-1/Day 21-22 - Transfer Task.dc.html$$, 'Day 21–22 — Transfer Task'),
 ('u1-d22', $$/decks/unit-1/Day 21-22 - Transfer Task.dc.html$$, 'Day 21–22 — Transfer Task'))
update public.lessons l set content_blocks = jsonb_set(l.content_blocks, '{blocks}',
  jsonb_build_array(jsonb_build_object('id', 'deck-' || m.slug, 'type', 'deck', 'src', m.src, 'title', m.title, 'note', 'Authored deck for this day (src/data/lesson-decks.ts). No slideMap yet: follow mode maps slides to sections proportionally; add slideMap to pin it.'))
  || (select coalesce(jsonb_agg(b), '[]'::jsonb) from jsonb_array_elements(l.content_blocks->'blocks') b where b->>'type' <> 'deck'))
from m where l.slug = m.slug;
