-- Math fluency translations.
--   math_spiral_items.translations: per-question translations of the prompt,
--     generated by AI at question-creation time, keyed by language code
--     (es / fr / pt / ht). Defaults to an empty object.
--   courses.math_translation_enabled: a per-section teacher toggle. When false
--     (the default), students in that section never see the Translate option, so
--     translation only appears where a teacher deliberately allows it.

alter table public.math_spiral_items
  add column if not exists translations jsonb not null default '{}'::jsonb;

alter table public.courses
  add column if not exists math_translation_enabled boolean not null default false;
