with m(slug, intro, rev, oi) as (values
  ('tr.u1.read-rule', 'trades-1', '2,3,4,5,6', 1),
  ('tr.u1.check-inst', 'trades-1', '2,3,4,5,6', 2),
  ('tr.u1.choose-inst', 'trades-1', '3,4,6', 3),
  ('tr.u1.repeat', 'trades-1', '2,3,5', 4),
  ('tr.u1.tolerance', 'trades-1', '2,3,4,6', 5),
  ('tr.u1.nominal', 'trades-1', '3,4,6', 6),
  ('tr.u1.vocab', 'trades-1', '2', 7),
  ('tr.u1.fits', 'trades-1', '3,4', 8),
  ('tr.u1.gauge', 'trades-1', '6', 9),
  ('tr.u1.datum', 'trades-1', '2,3', 10),
  ('tr.u1.cumul', 'trades-1', '2', 11),
  ('tr.u1.sixteen', 'trades-1', '3', 12),
  ('tr.u1.sketch', 'trades-1', '2,3,4,5,6', 13),
  ('tr.u1.dimension', 'trades-1', '2,3,4,5,6', 14),
  ('tr.u1.scale', 'trades-1', '2,3,5', 15),
  ('tr.u1.views', 'trades-1', '3,5', 16),
  ('tr.u1.asbuilt', 'trades-1', '2,3,4,5,6', 17),
  ('tr.u1.the-walk', 'trades-1', '2,3,4,5,6', 18),
  ('tr.u2.plumb-level', 'trades-2', '3,4', 1),
  ('tr.u2.level-check', 'trades-2', '', 2),
  ('tr.u2.square-check', 'trades-2', '3', 3),
  ('tr.u2.slope-set', 'trades-2', '4', 4),
  ('tr.u2.gravity-ref', 'trades-2', '3', 5),
  ('tr.u2.bubble', 'trades-2', '', 6),
  ('tr.u2.racking', 'trades-2', '3', 7),
  ('tr.u2.slope-why', 'trades-2', '4', 8),
  ('tr.u2.stair-why', 'trades-2', '', 9),
  ('tr.u2.345', 'trades-2', '', 10),
  ('tr.u2.rise-run', 'trades-2', '3,4,5', 11),
  ('tr.u2.fall-total', 'trades-2', '4', 12),
  ('tr.u2.plan-slope', 'trades-2', '4', 13),
  ('tr.u2.bay-conflict', 'trades-2', '3,4,5,6', 14),
  ('tr.u2.stair-sect', 'trades-2', '3,4', 15),
  ('tr.u3.force-def', 'trades-3', '4', 1),
  ('tr.u3.measure-force', 'trades-3', '', 2),
  ('tr.u3.load-path', 'trades-3', '5', 3),
  ('tr.u3.depth-cubed', 'trades-3', '', 4),
  ('tr.u3.notch-bore', 'trades-3', '', 5),
  ('tr.u3.bearing', 'trades-3', '4', 6),
  ('tr.u3.torque', 'trades-3', '5,6', 7),
  ('tr.u3.section', 'trades-3', '5', 8),
  ('tr.u3.live-dead', 'trades-3', '5', 9),
  ('tr.u3.forces-four', 'trades-3', '6', 10),
  ('tr.u3.machine-eff', 'trades-3', '', 11),
  ('tr.u4.pressure-def', 'trades-4', '5', 1),
  ('tr.u4.read-gauge', 'trades-4', '5', 2),
  ('tr.u4.flow-model', 'trades-4', '5,6', 3),
  ('tr.u4.pipe-size', 'trades-4', '6', 4),
  ('tr.u4.hammer', 'trades-4', '', 5),
  ('tr.u4.trap-vent', 'trades-4', '', 6),
  ('tr.u4.backdraft', 'trades-4', '5', 7),
  ('tr.u4.iso', 'trades-4', '', 8),
  ('tr.u4.open-closed', 'trades-4', '5', 9),
  ('tr.u4.hyd-pneu', 'trades-4', '', 10),
  ('tr.u4.pascal', 'trades-4', '', 11),
  ('tr.u5.heat-def', 'trades-5', '6', 1),
  ('tr.u5.temp-rate', 'trades-5', '', 2),
  ('tr.u5.r-series', 'trades-5', '', 3),
  ('tr.u5.bridging', 'trades-5', '', 4),
  ('tr.u5.pipe-side', 'trades-5', '', 5),
  ('tr.u5.hot-joint', 'trades-5', '6', 6),
  ('tr.u5.heat-modes', 'trades-5', '6', 7),
  ('tr.u5.wall-sect', 'trades-5', '6', 8),
  ('tr.u6.meter-set', 'trades-6', '', 1),
  ('tr.u6.meter-use', 'trades-6', '', 2),
  ('tr.u6.vdrop', 'trades-6', '', 3),
  ('tr.u6.gauge-r', 'trades-6', '', 4),
  ('tr.u6.series-par', 'trades-6', '', 5),
  ('tr.u6.bonding', 'trades-6', '', 6),
  ('tr.u6.oneline', 'trades-6', '', 7)
)
insert into public.target_focus (target_id, unit_id, role, order_index)
select lt.id, f.unit_id, f.role, f.oi from (
  select slug, intro as unit_id, 'introduce' as role, oi from m
  union all
  select m.slug, 'trades-' || u, 'revisit', m.oi * 100 + u::int
    from m, unnest(string_to_array(nullif(m.rev,''), ',')) as u
) f join public.learning_targets lt on lt.slug = f.slug
on conflict (target_id, unit_id) do update
  set role = excluded.role, order_index = excluded.order_index;
