-- Seed the Trades Physics content layer (program = 'trades').
-- Generated from src/data/trades-curriculum.ts. Idempotent: upsert by key.
-- Equivalent to: npx tsx scripts/seed-trades-curriculum.ts --commit

insert into public.units (id, name, description, order_index, program) values
  ('trades-1', 'Unit 1: Length & Tolerance — The Fieldhouse Wall', 'Measure it. Draw it. What the number on the material actually means.', 1, 'trades'),
  ('trades-2', 'Unit 2: Plumb, Level, Square, Slope', 'Gravity gives you one reference line free. Square you have to build.', 2, 'trades'),
  ('trades-3', 'Unit 3: Load', 'Live load, dead load, and where a hole does least harm.', 3, 'trades'),
  ('trades-4', 'Unit 4: Pressure', 'Flow = difference divided by resistance. Open systems and closed ones.', 4, 'trades'),
  ('trades-5', 'Unit 5: Heat', 'R-value, thermal bridging, and which side of the insulation a pipe goes on.', 5, 'trades'),
  ('trades-6', 'Unit 6: Electrical', 'Voltage drop, bonding, and why the wire gets fatter as the run gets longer.', 6, 'trades')
on conflict (id) do update set name = excluded.name, description = excluded.description, order_index = excluded.order_index, program = excluded.program;

insert into public.learning_targets (slug, statement, domain, unit_id, content_strand, standard_refs, exclude_from_growth, order_index, program) values
  ('tr.u1.read-rule', 'Read a tape or rule to 1/16 and 1/32 and write it correctly.', 'skill', 'trades-1', 'metrology', null, false, 1, 'trades'),
  ('tr.u1.check-inst', 'Check an instrument before trusting it — zero it, test it, inspect it.', 'skill', 'trades-1', 'metrology', null, false, 2, 'trades'),
  ('tr.u1.choose-inst', 'Choose the instrument the job''s precision actually needs.', 'skill', 'trades-1', 'metrology', null, false, 3, 'trades'),
  ('tr.u1.repeat', 'Measure repeatedly, describe the spread, separate the tool from yourself.', 'reasoning', 'trades-1', 'metrology', array['HS-ETS1-6(MA)']::text[], false, 4, 'trades'),
  ('tr.u1.tolerance', 'Compare a measurement to a spec, decide in or out, say by how much.', 'reasoning', 'trades-1', 'metrology', array['HS-ETS1-6(MA)']::text[], false, 5, 'trades'),
  ('tr.u1.nominal', 'State the actual size of a 2×4, a 1/2" pipe, a 12-gauge wire.', 'knowledge', 'trades-1', 'trade-math', array['HS-ETS2-4(MA)']::text[], false, 6, 'trades'),
  ('tr.u1.vocab', 'Use nominal, actual, tolerance and deviation correctly.', 'knowledge', 'trades-1', 'metrology', null, false, 7, 'trades'),
  ('tr.u1.fits', 'Work out whether a nominal material fits a nominal space.', 'reasoning', 'trades-1', 'trade-math', array['HS-ETS1-3']::text[], false, 8, 'trades'),
  ('tr.u1.gauge', 'Bigger gauge number = thinner wire. Three steps double the area.', 'reasoning', 'trades-1', 'trade-math', array['HS-ETS2-4(MA)']::text[], false, 9, 'trades'),
  ('tr.u1.datum', 'Lay out a repeated spacing from one datum and land the last mark.', 'skill', 'trades-1', 'metrology', null, false, 10, 'trades'),
  ('tr.u1.cumul', 'Why measuring from the last mark piles error up and a datum does not.', 'reasoning', 'trades-1', 'trade-math', null, false, 11, 'trades'),
  ('tr.u1.sixteen', 'Why framing is 16 on center, and why it is measured to centers.', 'reasoning', 'trades-1', 'physics-model', null, false, 12, 'trades'),
  ('tr.u1.sketch', 'Make a freehand field sketch with the proportions right.', 'skill', 'trades-1', 'plan-reading', null, false, 13, 'trades'),
  ('tr.u1.dimension', 'Dimension a drawing to convention — outside the object, once each.', 'skill', 'trades-1', 'plan-reading', array['HS-ETS1-5(MA)']::text[], false, 14, 'trades'),
  ('tr.u1.scale', 'Draw to a stated scale, and check somebody else''s with a rule.', 'skill', 'trades-1', 'plan-reading', array['HS-ETS1-5(MA)']::text[], false, 15, 'trades'),
  ('tr.u1.views', 'Produce three orthographic views that line up.', 'skill', 'trades-1', 'plan-reading', array['HS-ETS1-5(MA)']::text[], false, 16, 'trades'),
  ('tr.u1.asbuilt', 'Draw what is actually there, not what the print said.', 'skill', 'trades-1', 'plan-reading', array['HS-ETS1-6(MA)']::text[], false, 17, 'trades'),
  ('tr.u1.the-walk', 'Walk a job before you price it — write what it has to do, what you are stuck with, and what code already decided.', 'skill', 'trades-1', 'plan-reading', array['HS-ETS1-1','HS-ETS1-3']::text[], false, 18, 'trades'),
  ('tr.u2.plumb-level', 'Establish plumb and level with a bob, a spirit level and a water level.', 'skill', 'trades-2', 'metrology', null, false, 1, 'trades'),
  ('tr.u2.level-check', 'Check a level for calibration by reversing it end for end.', 'skill', 'trades-2', 'metrology', null, false, 2, 'trades'),
  ('tr.u2.square-check', 'Check a rectangle for square by measuring both diagonals.', 'skill', 'trades-2', 'metrology', null, false, 3, 'trades'),
  ('tr.u2.slope-set', 'Set and check a slope in inches per foot.', 'skill', 'trades-2', 'metrology', null, false, 4, 'trades'),
  ('tr.u2.gravity-ref', 'Name the one reference line gravity gives you free, and the instrument for each form of it.', 'knowledge', 'trades-2', 'physics-model', null, false, 5, 'trades'),
  ('tr.u2.bubble', 'Why a bubble finds level — and why a laser can be wrong when a plumb bob cannot.', 'reasoning', 'trades-2', 'physics-model', null, false, 6, 'trades'),
  ('tr.u2.racking', 'Why a rectangle racks and a triangle does not.', 'reasoning', 'trades-2', 'physics-model', array['HS-ETS3-4(MA)']::text[], false, 7, 'trades'),
  ('tr.u2.slope-why', 'Why drain slope has a minimum and a maximum, and what fails at each end.', 'reasoning', 'trades-2', 'physics-model', array['HS-ETS1-3']::text[], false, 8, 'trades'),
  ('tr.u2.stair-why', 'Why the first and last riser are the ones that end up wrong.', 'reasoning', 'trades-2', 'physics-model', null, false, 9, 'trades'),
  ('tr.u2.345', 'Use 3-4-5 to lay out a right angle, and explain why it works.', 'reasoning', 'trades-2', 'trade-math', null, false, 10, 'trades'),
  ('tr.u2.rise-run', 'Read one ratio four ways — in/ft, roof pitch, percent grade, 1-in-12 — and convert between them.', 'reasoning', 'trades-2', 'trade-math', null, false, 11, 'trades'),
  ('tr.u2.fall-total', 'Work out total fall over a run, and what it costs you in depth.', 'reasoning', 'trades-2', 'trade-math', array['HS-ETS1-2']::text[], false, 12, 'trades'),
  ('tr.u2.plan-slope', 'Draw a plan with the fall called out correctly.', 'skill', 'trades-2', 'plan-reading', null, false, 13, 'trades'),
  ('tr.u2.bay-conflict', 'Read a bay section, find the conflict, and say which service has to move and why.', 'reasoning', 'trades-2', 'physics-model', array['HS-ETS1-2','HS-ETS1-3']::text[], false, 14, 'trades'),
  ('tr.u2.stair-sect', 'Draw a sloped run in section with both end elevations called out.', 'skill', 'trades-2', 'plan-reading', array['HS-ETS1-5(MA)']::text[], false, 15, 'trades'),
  ('tr.u3.force-def', 'Define force, load and bearing, with units.', 'knowledge', 'trades-3', 'physics-model', array['HS-ETS3-3(MA)']::text[], false, 1, 'trades'),
  ('tr.u3.measure-force', 'Measure a force with a scale or a spring gauge.', 'skill', 'trades-3', 'metrology', null, false, 2, 'trades'),
  ('tr.u3.load-path', 'Trace a load path from the top of a wall to the ground.', 'reasoning', 'trades-3', 'physics-model', array['HS-ETS3-1(MA)','HS-ETS3-3(MA)']::text[], false, 3, 'trades'),
  ('tr.u3.depth-cubed', 'Why doubling a joist''s depth stiffens it far more than doubling its width.', 'reasoning', 'trades-3', 'trade-math', null, false, 4, 'trades'),
  ('tr.u3.notch-bore', 'Why a hole through the middle is safer than a notch at the bottom.', 'reasoning', 'trades-3', 'physics-model', array['HS-ETS3-4(MA)']::text[], false, 5, 'trades'),
  ('tr.u3.bearing', 'Use P = F ÷ A to explain why a footing is wider than the wall.', 'reasoning', 'trades-3', 'physics-model', null, false, 6, 'trades'),
  ('tr.u3.torque', 'Why a terminal gets torqued to a spec instead of tight.', 'reasoning', 'trades-3', 'physics-model', array['HS-ETS3-4(MA)','HS-ETS4-5']::text[], false, 7, 'trades'),
  ('tr.u3.section', 'Draw a section with load arrows on it.', 'skill', 'trades-3', 'plan-reading', array['HS-ETS1-5(MA)']::text[], false, 8, 'trades'),
  ('tr.u3.live-dead', 'Tell a dead load from a live load, and add them to get a total.', 'knowledge', 'trades-3', 'physics-model', array['HS-ETS3-3(MA)']::text[], false, 9, 'trades'),
  ('tr.u3.forces-four', 'Name tension, compression, shear and torsion in a real assembly, and pick a material for each.', 'reasoning', 'trades-3', 'physics-model', array['HS-ETS3-4(MA)']::text[], false, 10, 'trades'),
  ('tr.u3.machine-eff', 'Work out what a machine gives you and what it costs — and measure how much you lose.', 'reasoning', 'trades-3', 'trade-math', array['HS-ETS4-5']::text[], false, 11, 'trades'),
  ('tr.u4.pressure-def', 'Define pressure and head, and convert psi to feet of head.', 'knowledge', 'trades-4', 'physics-model', null, false, 1, 'trades'),
  ('tr.u4.read-gauge', 'Read a pressure gauge and a manometer.', 'skill', 'trades-4', 'metrology', null, false, 2, 'trades'),
  ('tr.u4.flow-model', 'Flow = difference ÷ resistance, and where it holds.', 'reasoning', 'trades-4', 'physics-model', array['HS-ETS3-1(MA)','HS-ETS4-1(MA)','HS-ETS4-2(MA)']::text[], false, 3, 'trades'),
  ('tr.u4.pipe-size', 'Why pipe size does more for flow than pressure does.', 'reasoning', 'trades-4', 'trade-math', null, false, 4, 'trades'),
  ('tr.u4.hammer', 'Water hammer as moving water being stopped.', 'reasoning', 'trades-4', 'physics-model', null, false, 5, 'trades'),
  ('tr.u4.trap-vent', 'Why a trap needs a vent.', 'reasoning', 'trades-4', 'physics-model', array['HS-ETS4-2(MA)']::text[], false, 6, 'trades'),
  ('tr.u4.backdraft', 'How air sealing a house can backdraft a water heater.', 'reasoning', 'trades-4', 'physics-model', array['HS-ETS3-1(MA)']::text[], false, 7, 'trades'),
  ('tr.u4.iso', 'Draw a simple piping isometric or riser.', 'skill', 'trades-4', 'plan-reading', array['HS-ETS1-5(MA)']::text[], false, 8, 'trades'),
  ('tr.u4.open-closed', 'Tell an open fluid system from a closed one, and say when each is the right choice.', 'reasoning', 'trades-4', 'physics-model', array['HS-ETS4-2(MA)']::text[], false, 9, 'trades'),
  ('tr.u4.hyd-pneu', 'Say why some tools run on air and some on oil, and what that costs each way.', 'reasoning', 'trades-4', 'physics-model', array['HS-ETS4-3(MA)']::text[], false, 10, 'trades'),
  ('tr.u4.pascal', 'Use the ratio of piston areas to work out what a jack multiplies — and what it gives up.', 'reasoning', 'trades-4', 'trade-math', array['HS-ETS4-4(MA)']::text[], false, 11, 'trades'),
  ('tr.u5.heat-def', 'Define temperature, heat and R-value.', 'knowledge', 'trades-5', 'physics-model', array['HS-ETS4-1(MA)']::text[], false, 1, 'trades'),
  ('tr.u5.temp-rate', 'Measure a temperature difference and a rate of change.', 'skill', 'trades-5', 'metrology', null, false, 2, 'trades'),
  ('tr.u5.r-series', 'Add R-values in series across a real assembly.', 'reasoning', 'trades-5', 'trade-math', array['HS-ETS3-5(MA)']::text[], false, 3, 'trades'),
  ('tr.u5.bridging', 'Thermal bridging — why studs show up on a thermal image.', 'reasoning', 'trades-5', 'physics-model', array['HS-ETS3-5(MA)']::text[], false, 4, 'trades'),
  ('tr.u5.pipe-side', 'Which side of the insulation a cold pipe goes on, and why.', 'reasoning', 'trades-5', 'physics-model', array['HS-ETS3-5(MA)']::text[], false, 5, 'trades'),
  ('tr.u5.hot-joint', 'Why a loose electrical connection is a heat problem.', 'reasoning', 'trades-5', 'physics-model', null, false, 6, 'trades'),
  ('tr.u5.heat-modes', 'Name conduction, convection and radiation in a real building, and say which one a material is chosen against.', 'knowledge', 'trades-5', 'physics-model', array['HS-ETS3-5(MA)']::text[], false, 7, 'trades'),
  ('tr.u5.wall-sect', 'Draw a wall section showing insulation and services.', 'skill', 'trades-5', 'plan-reading', array['HS-ETS3-5(MA)']::text[], false, 8, 'trades'),
  ('tr.u6.meter-set', 'Name what a multimeter measures and which setting to use.', 'knowledge', 'trades-6', 'metrology', array['HS-ETS4-1(MA)']::text[], false, 1, 'trades'),
  ('tr.u6.meter-use', 'Measure volts, amps and ohms safely on a low-voltage circuit.', 'skill', 'trades-6', 'metrology', null, false, 2, 'trades'),
  ('tr.u6.vdrop', 'Voltage drop, and why the wire gets fatter as the run gets longer.', 'reasoning', 'trades-6', 'physics-model', null, false, 3, 'trades'),
  ('tr.u6.gauge-r', 'Use the gauge/area rule to predict resistance.', 'reasoning', 'trades-6', 'trade-math', null, false, 4, 'trades'),
  ('tr.u6.series-par', 'Series and parallel, explained with the water model.', 'reasoning', 'trades-6', 'physics-model', array['HS-ETS3-1(MA)']::text[], false, 5, 'trades'),
  ('tr.u6.bonding', 'What bonding does, and what breaks it.', 'reasoning', 'trades-6', 'physics-model', null, false, 6, 'trades'),
  ('tr.u6.oneline', 'Read and draw a simple one-line diagram.', 'skill', 'trades-6', 'plan-reading', null, false, 7, 'trades')
on conflict (slug) do update set statement = excluded.statement, domain = excluded.domain, unit_id = excluded.unit_id, content_strand = excluded.content_strand, standard_refs = excluded.standard_refs, order_index = excluded.order_index, program = excluded.program;

insert into public.mastery_tasks (slug, unit_id, prompt, rubric, program) values
  ('tr.u1.mastery-as-built', 'trades-1', 'You are handed a drawing of one bay of the fieldhouse wall and the services on it. Walk it first and write the scope. Then verify the drawing, decide what is in and what is out, write an inspection another tradesman could act on, and produce an as-built of the bay as it really is.', '{"science": {"description": "Measurements correct, instrument suited to the precision required, recorded to the right fraction. Nominal and actual sizes handled correctly."}, "reasoning": {"description": "In-and-out calls follow from the numbers actually taken. Uncertainty is stated as a number, not a feeling."}, "communication": {"description": "Another tradesman could build from the as-built without asking a single question. Scale stated, nominal materials named in a note."}, "transfer": {"description": "Holds up on a real job. Planted errors caught; the consequence of being out of tolerance is named."}}'::jsonb, 'trades'),
  ('tr.u2.mastery-route-the-fall', 'trades-2', 'You are given a bay section, a fixture, and the point where the drain has to connect. Walk a real bay first and write the scope. Then route it, prove the fall, and show what it costs the framing — or prove that it cannot be done as drawn and state exactly what has to change and by how much.', '{"science": {"description": "The fall arithmetic is right and the depths used are actual sizes, not nominal ones."}, "reasoning": {"description": "The resolution follows from the student''s own numbers, and the easy wrong answer (reduce the fall) is rejected for a stated reason."}, "communication": {"description": "A tradesman could build from the plan and section without asking anything: fall called out, both end elevations dimensioned, bore located, scale stated."}, "transfer": {"description": "The student names what their decision costs another trade. ''It cannot be done as drawn'' is fully correct when proved."}}'::jsonb, 'trades')
on conflict (slug) do update set unit_id = excluded.unit_id, prompt = excluded.prompt, rubric = excluded.rubric, program = excluded.program;
