'use client'
import TeachingSeiSupports from './TeachingSeiSupports'
import MathMarkdown from '@/components/MathMarkdown'
import { lessonLocation, lessonNumber } from '@/components/lessons/LessonVisualIdentity'
import { answerGuide } from '@/components/lessons/lesson-answer-guide'
import type { InlineQuestion, ContentBlock } from '@/data/content-blocks'
import type { LiveCommandState } from '@/lib/classroom-command'
import { PULSE_OPTIONS, type Pulse } from '@/lib/presentation-tools'
import { TeachingStage, FitTeachingContent } from './TeachingStage'

export default function TeachingActivity({ lesson, live, pulse, question, discussion, origin, referenceBlocks = [], seiEnabled = false }: { seiEnabled?: boolean; referenceBlocks?: ContentBlock[]; lesson: string; live: LiveCommandState; pulse: Pulse | null; question: InlineQuestion | null; discussion: boolean; origin: string }) {
  const block = referenceBlocks.find(b => b.id === live.session.poll_block_id)
  const location = !pulse && !live.lobby ? lessonLocation(block?.id, referenceBlocks) : null
  const lobby = live.lobby
  const revealed = live.session.poll_revealed
  const options = pulse ? PULSE_OPTIONS[pulse.kind].map((text, i) => ({ id: String(i), text })) : question?.options ?? []
  const mode = lobby ? 'Together' : pulse ? 'Pulse check' : revealed ? 'The class perspective' : discussion ? 'Turn & talk' : 'Make your call'
  const prompt = pulse ? pulse.kind === 'readiness' ? 'How ready are you to move on?' : 'How confident do you feel?' : question?.prompt ?? ''
  const footer = lobby ? 'Connect with your group. Build an explanation together.' : pulse ? 'Respond on your lesson screen' : revealed ? 'Compare the responses. Explain your reasoning.' : live.session.poll_locked ? 'Pause. Compare your reasoning.' : 'Choose an answer on your lesson screen.'
  return <TeachingStage location={location} lesson={lesson} mode={mode} footer={footer}><FitTeachingContent>
    {lobby ? <div className="teach-join"><div className="teach-focus lesson-chapter" style={{ minHeight: 640 }}><p className="teach-eyebrow">Join the activity</p><h1 className="teach-headline">Better thinking.<br />Together.</h1><div className="teach-code">{lobby.code}</div><p className="teach-join-url">{origin.replace(/^https?:\/\//, '')}/lobby</p></div><div className="teach-join-steps">{[['01','Open the lobby on your device.'],['02','Enter the code on this screen.'],['03',lobby.status === 'open' ? 'Work with your group on your device.' : lobby.status === 'grouped' ? 'Find your group on your device.' : 'Get ready to join your group.']].map(([n,text]) => <div className="teach-join-step" key={n}><strong>{n}</strong><span>{text}</span></div>)}</div></div> : <div className="teach-split"><div className="teach-focus lesson-chapter"><p className="teach-eyebrow">{location?.response ? `Your response ${lessonNumber(location.response)} · ` : ''}{mode}</p>{location && <span className="lesson-chapter-number" aria-hidden="true">{lessonNumber(location.step)}</span>}<div role="heading" aria-level={1} className="teach-headline"><MathMarkdown content={prompt} /></div><p className="teach-subtitle">{pulse ? pulse.anonymous ? 'Anonymous totals · every response helps.' : 'Your teacher can offer help.' : discussion ? 'Discuss with a partner. Explain your reasoning before the fresh vote.' : revealed ? 'Compare the responses. Be ready to explain your reasoning.' : 'Choose the response that best matches your thinking.'}</p>{!pulse && block && <p className="teach-subtitle" style={{ marginTop: 18 }}>{answerGuide(block).parts.join(' · ')}</p>}{!pulse && <TeachingSeiSupports block={block} enabled={seiEnabled} />}{!pulse && <div className="teach-participation"><strong>{live.saved}</strong> of {live.enrolled} responses <div style={{ fontSize: 21, marginTop: 8 }}>{revealed ? 'Results revealed' : live.session.poll_locked ? 'Responses locked' : 'Respond on your device'}</div></div>}</div><div className="teach-options" style={options.length > 4 ? { gridTemplateColumns: '1fr 1fr', gap: 12 } : undefined}>{options.map((option,i) => { const count = live.tally[option.id] ?? 0; const percent = live.saved > 0 ? Math.round(count / live.saved * 100) : 0; return <div key={option.id} className="teach-option"><span className="teach-option-letter">{pulse ? i + 1 : String.fromCharCode(65 + i)}</span><div className="teach-option-text"><MathMarkdown content={option.text} /></div>{!pulse && revealed && <><div className="teach-response"><span>{count} {count === 1 ? 'response' : 'responses'}</span><strong>{percent}%</strong></div><div className="teach-bar" aria-label={`${percent}% of responses`}><span style={{ width: `${Math.min(100,percent)}%` }} /></div></>}</div> })}</div></div>}
  </FitTeachingContent></TeachingStage>
}
