/** Parameterized, deterministic task families. Answer keys remain on the server. */
import type {CompetencyCode} from './catalog'
import type {Answer, Field, Task} from './types'
const num=(id:string,label:string,unit?:string):Field=>({id,label,kind:'number',unit})
const pick=(id:string,label:string,options:string[]):Field=>({id,label,kind:'select',options:options.map(value=>({value,label:value}))})
const text=(id:string,label:string):Field=>({id,label,kind:'text'})
const round=(n:number)=>Math.round(n*1e6)/1e6
export function rng(seed:number){let s=seed|0;return()=>{s|=0;s=s+0x6D2B79F5|0;let t=Math.imul(s^s>>>15,1|s);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
export function makeTask(code:CompetencyCode,seed:number,index:number,level=1,variant=index):Task{
 const random=rng(seed+index*7919),int=(a:number,b:number)=>a+Math.floor(random()*(b-a+1));
 const base={id:`v1:${code}:${seed}:${index}:${level}`,code,errorRules:[],explanation:'Explain the relationship you used.'};
 switch(code){
 case 'NS1':{const hundredths=int(21,89),sign=level>1&&variant%2?-1:1,value=sign*hundredths/100,other=sign*(Math.floor(hundredths/10)+1)/10;
 return {...base,board:'numberline',title:'Land between the landmarks',prompt:`Land the rover at ${value}. Name the value of its hundredths digit, then compare it with ${other}.`,data:{min:sign<0?-1:0,max:sign<0?0:1,target:value,other},fields:[{...num('position','Rover position'),min:sign<0?-1:0,max:sign<0?0:1,step:.01},num('digit','Value of the hundredths digit'),pick('comparison',`${value} is … ${other}`,['less than','equal to','greater than'])],expected:{position:String(value),digit:String(round((hundredths%10)/100)),comparison:value<other?'less than':'greater than'},hint:'Tenths are groups of ten hundredths. Moving right always means a larger value, including below zero.',worked:[`${Math.floor(hundredths/10)} tenths and ${hundredths%10} hundredths locate the magnitude.`,`The hundredths digit contributes ${(hundredths%10)/100} to that magnitude.`,`${value} ${value<other?'<':'>'} ${other}.`],explanation:'Place value and position must agree.',errorRules:[{field:'digit',value:String(hundredths%10),code:'digit-versus-place',feedback:'That is the digit. Its place is hundredths: divide the digit by 100.'}]};}
 case 'NS2':{const denominators=[4,5,8,10,20],d=denominators[int(0,4)],n=int(1,d-1),v=n/d;return {...base,board:'numberline',title:'One landing, three names',prompt:`Deliver ${n}/${d} of a full charge. Land the rover and label that same amount as a decimal and a percentage.`,data:{min:0,max:1,numerator:n,denominator:d,target:v},fields:[{...num('position','Rover position'),min:0,max:1,step:.005},num('decimal','Decimal label'),num('percent','Percentage label','%')],expected:{position:String(v),decimal:String(v),percent:String(v*100)},hint:'Divide numerator by denominator to get the decimal. Percent counts hundredths: multiply the decimal by 100.',worked:[`${n} ÷ ${d} = ${v}.`,`${v} × 100 = ${v*100}%.`,'All three labels must identify the same point.'],explanation:'Equivalent labels preserve the amount.',errorRules:[{field:'percent',value:String(v),code:'percent-scale',feedback:'That is the decimal. A percentage counts hundredths, so multiply it by 100.'}]};}
 case 'PR1':{const a=int(2,6),b=int(3,8),factor=int(2,level>1?7:4),target=b*factor;return {...base,board:'reactor',title:'Mix a stable batch',prompt:`The reactor needs ${a} parts A for every ${b} parts B. Tune A to match a delivery of ${target} parts B.`,data:{a,b,target,power:1},fields:[{...num('input','Parts A'),min:0,max:a*factor*2,step:1},num('factor','Scale factor')],expected:{input:String(a*factor),factor:String(factor)},hint:'Find one multiplicative factor from the original B to the target B. Apply it to both quantities.',worked:[`${target} ÷ ${b} = ${factor}.`,`${a} × ${factor} = ${a*factor} parts A.`],explanation:'Both parts must be multiplied by the same factor.',errorRules:[{field:'input',value:String(a+target-b),code:'additive-scaling',feedback:'Adding the same amount changes the ratio. Multiply both quantities by the same factor.'}]};}
 case 'PR2':{const powers=[1,2,3,-1,-2],p=powers[(variant+seed%5)%5],k=level>1&&variant%2?.5:[2,3,4][int(0,2)],relation=p===1?'y ∝ x':p===2?'y ∝ x²':p===3?'y ∝ x³':p===-1?'y ∝ 1/x':'y ∝ 1/x²',scale=k**p;return {...base,board:'reactor',title:'Predict the reactor response',prompt:`The model is ${relation}. Change x by a factor of ${k}. Select the relationship and set the output factor before running the reactor.`,data:{power:p,factor:k,relation},fields:[pick('model','Relationship',['direct','square','cube','inverse','inverse-square']),{...num('output','Output factor'),min:0,max:Math.max(16,scale*2),step:.001}],expected:{model:p===1?'direct':p===2?'square':p===3?'cube':p===-1?'inverse':'inverse-square',output:String(scale)},hint:`Apply the exponent ${p} to the input factor. A negative exponent means take the reciprocal.`,worked:[`Output factor = (${k})^(${p}).`,`The result is ${round(scale)}.`,p<0?'Increasing x reduces y; reducing x increases y.':'Apply the factor once for each positive power.'],explanation:'The relationship determines how the input factor changes the output.',errorRules:[{field:'output',value:String(k*p),code:'exponent-as-multiplier',feedback:`An exponent is not a multiplier. Calculate ${k} to the power ${p}.`}]};}
 case 'QE1':{const a=int(2,8),e=int(level>1?-5:2,6),b=level>1?int(2,4):1,f=level>1?int(-3,3):0,raw=a*b,shift=raw>=10?1:0,m=raw/10**shift,exp=e+f+shift;return {...base,board:'courier',title:'Pack a power of ten',prompt:level>1?`Ship (${a} × 10^${e}) × (${b} × 10^${f}) in normalized scientific notation.`:`Ship ${a*10**e} in normalized scientific notation.`,data:{a,e,b,f,scientific:1},fields:[num('mantissa','Coefficient (at least 1, below 10)'),{...num('exponent','Power of ten'),min:-12,max:12,step:1}],expected:{mantissa:String(m),exponent:String(exp)},hint:'Multiply coefficients and add exponents. If the coefficient reaches 10, shift it one place and increase the exponent.',worked:[`${a} × ${b} = ${raw}; the exponents add to ${e+f}.`,`${raw} × 10^${e+f} = ${m} × 10^${exp}.`],explanation:'Changing notation must preserve the value.',errorRules:[{field:'exponent',value:String(e*f),code:'multiply-exponents',feedback:'When multiplying powers with the same base, add the exponents.'}]};}
 case 'QE2':{const speed=variant%2===0,value=speed?int(2,12)*18:int(2,12),factor=speed?1/3.6:10000;return {...base,board:'courier',title:speed?'Deliver a speed':'Deliver an area',prompt:speed?`Convert ${value} km/h into m/s. Build a route whose unwanted units cancel.`:`Convert ${value} m² into cm². Remember that both dimensions change.`,data:{value,from:speed?'km/h':'m²',to:speed?'m/s':'cm²',speed:speed?1:0},fields:speed?[pick('bridge1','Distance bridge',['1000 m / 1 km','1 km / 1000 m']),pick('bridge2','Time bridge',['1 h / 3600 s','3600 s / 1 h']),num('result','Delivered value','m/s')]:[pick('bridge1','Area bridge',['(100 cm / 1 m)²','100 cm / 1 m','(1 m / 100 cm)²']),num('result','Delivered value','cm²')],expected:speed?{bridge1:'1000 m / 1 km',bridge2:'1 h / 3600 s',result:String(round(value*factor))}:{bridge1:'(100 cm / 1 m)²',result:String(value*factor)},hint:speed?'Put km below m to cancel km. Put h above s to cancel the original denominator h.':'Area has two length dimensions. Square the whole conversion factor.',worked:speed?[`${value} km/h × (1000 m/km) × (1 h/3600 s).`,`km and h cancel. The value is ${round(value/3.6)} m/s.`]:[`${value} m² × (100 cm/m)².`,`100² = 10000, so the result is ${value*10000} cm².`],explanation:'The route must preserve the quantity and end with the requested units.',errorRules:speed?[{field:'bridge2',value:'3600 s / 1 h',code:'inverted-conversion',feedback:'The original h is already in the denominator. Put h in the numerator of the factor.'}]:[{field:'result',value:String(value*100),code:'unsquared-unit-factor',feedback:'You converted only one dimension. For square metres, multiply by 100 twice.'}]};}
 case 'QE3':{const length=int(15,35),width=int(8,18);return {...base,board:'precision',title:'Plan an observation',prompt:`A hall is about ${length} m by ${width} m. Estimate how many people could stand inside. Choose a usable area and space per person; show your assumptions and a plausible range. This is an estimate, not a safe occupancy limit.`,data:{length,width,estimation:1},fields:[num('area','Usable area','m²'),num('space','Space per person','m²/person'),num('estimate','Estimated people'),num('low','Lower plausible estimate'),num('high','Upper plausible estimate'),text('reason','Explain your assumptions and what would change your range')],expected:{},review:true,hint:'Start with floor area. Reduce it for obstructions. Divide usable area by assumed area per person. Try different assumptions for a range.',worked:[`Total floor area is approximately ${length*width} m².`,`One possible usable area is ${Math.round(length*width*.8)} m²; justify yours.`,`People ≈ usable area ÷ area per person. Different defensible assumptions give different answers.`],explanation:'Your teacher reviews whether the assumptions and range are defensible.'};}
 case 'QE4':{const measurement=round(int(80,180)/10),other=round(int(110,290)/100),adding=variant%2===0,answer=adding?(measurement+other).toFixed(1):(measurement*other).toPrecision(3);return {...base,board:'precision',title:'Publish an honest measurement',prompt:adding?`The instrument reads ${measurement.toFixed(1)} cm to the nearest 0.1 cm. Add a measured ${other.toFixed(2)} cm. Report the sum with appropriate precision.`:`The instrument reads ${measurement.toFixed(1)} cm. Multiply by an exact scale factor of ${other.toFixed(2)}. Report the result with the same significant figures as the measurement.`,data:{measurement,other,adding:adding?1:0,min:Math.floor(measurement)-1,max:Math.ceil(measurement)+1},fields:[num('reading','Instrument reading','cm'),text('result','Reported result in cm (include meaningful trailing zeros)'),pick('rule','Reporting rule',['least precise decimal place','fewest significant figures','all calculator digits'])],expected:{reading:String(measurement),result:adding?answer:(measurement*other).toPrecision(measurement.toFixed(1).replace('.','').replace(/^0+/,'').length),rule:adding?'least precise decimal place':'fewest significant figures'},hint:adding?'For addition, report to the least precise decimal place. Keep extra digits until the last step.':'An exact scale factor does not limit precision. Preserve the significant figures in the measurement.',worked:[`Calculate first: ${measurement} ${adding?'+':'×'} ${other} = ${round(adding?measurement+other:measurement*other)}.`,adding?'Round the final sum to tenths of a centimetre.':`The measurement ${measurement.toFixed(1)} has ${measurement.toFixed(1).replace('.','').replace(/^0+/,'').length} significant figures.`],explanation:'Reported precision should reflect the information in the data.',errorRules:[{field:'rule',value:'all calculator digits',code:'calculator-precision',feedback:'A calculator can show digits that the measurements do not support.'}]};}
 case 'SM1':{const vars=[['a','u','v','t'],['m','f','F','a'],['P','E0','E','t']][(variant+seed%3)%3], [a,b,c,x]=vars;return {...base,board:'balance',title:'Repair the equation',prompt:`Isolate ${x} in ${c} = ${b} + ${a}·${x}. Use operations on both sides, then write the resulting expression for ${x}.`,data:{a,b,c,x},fields:[text('formula',`${x} =`)],expected:{formula:`(${c}-${b})/${a}`},hint:`Undo addition of ${b} and multiplication by ${a}. Whatever you do, apply it to the whole of both sides.`,worked:[`Subtract ${b} from both sides: ${c} − ${b} = ${a}·${x}.`,`Divide both sides by ${a}: (${c} − ${b})/${a} = ${x}.`,`Alternatively divide both sides first, then subtract ${b}/${a}.`],explanation:'Equivalent rearrangements preserve equality.',errorRules:[{field:'formula',value:`${c}-${b}/${a}`,code:'partial-division',feedback:`Parentheses matter: the whole difference (${c} − ${b}) must be divided by ${a}.`}]};}
 case 'SM2':{const u=int(-8,8),a=int(1,5)*(level>1?-1:1),t=int(2,6),v=u+a*t;return {...base,board:'balance',title:'Test the repaired machine',prompt:`Use v = u + at with u = ${u} m/s, a = ${a} m/s², and t = ${t} s. Build the substituted expression and calculate the signed velocity.`,data:{u,a,t,substitution:1},fields:[text('expression','Substituted expression'),num('result','Velocity'),pick('unit','Velocity unit',['m/s','m/s²','m','s'])],expected:{expression:`(${u})+(${a})*(${t})`,result:String(v),unit:'m/s'},hint:'Put signed values in parentheses. Multiply acceleration by time before adding initial velocity; (m/s²) × s = m/s.',worked:[`v = (${u}) + (${a}) × (${t}).`,`v = ${u} + (${a*t}) = ${v} m/s.`],explanation:'Substitution must preserve signs, grouping and units.',errorRules:[{field:'result',value:String((u+a)*t),code:'order-of-operations',feedback:'Multiply acceleration by time first. The initial velocity is not multiplied by time.'},{field:'unit',value:'m/s²',code:'result-dimensions',feedback:'Acceleration times time has units m/s. You are finding velocity.'}]};}
 case 'GV1':{if(variant%2){const start=int(-8,8),duration=int(2,6),velocity=int(1,5)*(level>1?-1:1),end=start+velocity*duration;return {...base,board:'motion',title:'Read the robot’s rate',prompt:'Read the position-time graph. Determine the signed slope, give its units, and identify what it means physically.',data:{slopeTask:1,start,end,duration},fields:[num('velocity','Graph slope'),pick('unit','Slope unit',['m/s','m/s²','m','s']),pick('meaning','Physical meaning',['velocity','acceleration','distance travelled','starting position'])],expected:{velocity:String(velocity),unit:'m/s',meaning:'velocity'},hint:'Slope is change in vertical quantity divided by change in horizontal quantity. Use the axis labels to identify the rate.',worked:[`Change in position: ${end} − (${start}) = ${end-start} m.`,`Change in time: ${duration} s.`,`Slope = ${end-start}/${duration} = ${velocity} m/s. It represents velocity.`],explanation:'Slope on a position-time graph represents signed velocity.',errorRules:[{field:'velocity',value:String(end),code:'height-versus-slope',feedback:'That is a position. Calculate the change in position divided by the elapsed time.'}]};}const v=int(2,6),duration=int(2,4),returnTime=int(2,4),target=-v*duration/returnTime;return {...base,board:'motion',title:'Bring the robot home',prompt:`The robot moves at ${v} m/s for ${duration} s. Set its velocity for the next ${returnTime} s so it returns home. Then report total displacement and total distance.`,data:{v,duration,returnTime},fields:[{...num('returnVelocity','Return velocity','m/s'),min:-15,max:15,step:.01},num('displacement','Total displacement','m'),num('distance','Total distance','m')],expected:{returnVelocity:String(round(target)),displacement:'0',distance:String(2*v*duration)},hint:'Signed area under a velocity-time graph is displacement. Areas above and below zero cancel; distances add their magnitudes.',worked:[`First displacement: ${v} × ${duration} = ${v*duration} m.`,`Return velocity must be −${v*duration} ÷ ${returnTime} = ${round(target)} m/s.`,`Net displacement is 0 m; distance is ${2*v*duration} m.`],explanation:'Slope and area have different meanings; this velocity-time task uses signed area.',errorRules:[{field:'distance',value:'0',code:'distance-displacement',feedback:'Returning home gives zero displacement, but the robot travelled both legs. Add their lengths.'}]};}
 case 'GV2':{const power=variant%2===0?2:-1,m=int(2,5),b=level>1?int(1,4):0,xs=power===2?[1,2,3,4]:[1,2,4,8],transformed=xs.map(x=>x**power),residual=[transformed[1]-transformed[2],transformed[2]-transformed[0],transformed[0]-transformed[1],0],ys=xs.map((x,i)=>round(m*x**power+b+(level>1?residual[i]*.02:0)));return {...base,board:'motion',title:'Reveal the relationship',prompt:`A sensor records y in metres and x in seconds. Choose a horizontal axis that makes the data linear, then find the fitted slope and intercept. Use the fit tool for imperfect data.`,data:{xs,ys,power,fit:1},fields:[pick('axis','Horizontal axis',['x','x²','1/x']),num('slope','Fitted slope'),num('intercept','Vertical intercept','m'),pick('unit','Slope units',['m/s','m/s²','m·s']),pick('proportional','Is y proportional to the transformed horizontal variable?',['yes','no'])],expected:{axis:power===2?'x²':'1/x',slope:String(m),intercept:String(b),unit:power===2?'m/s²':'m·s',proportional:b===0?'yes':'no'},hint:'Transform each horizontal value, then compare rise over run. A straight line is proportional only if its intercept is zero.',worked:[`Use ${power===2?'x²':'1/x'} on the horizontal axis.`,`The fitted relationship is y = ${m}·(${power===2?'x²':'1/x'}) + ${b}.`,`Slope units are ${power===2?'m/s²':'m·s'}; the intercept is ${b} m.`],explanation:'Axes, rate units and intercept all describe the model.',errorRules:[{field:'proportional',value:'yes',code:'linear-versus-proportional',feedback:b?'A nonzero intercept means the relationship is linear but not proportional.':'Check the selected axes and the rate units.'}]};}
 case 'GV3':{const speed=int(2,4)*5,angle=[37,53,127,217,307][level>1?int(0,4):int(0,1)],reference=variant%2?'positive y':'positive x',rad=(reference==='positive y'?90-angle:angle)*Math.PI/180,vx=speed*Math.cos(rad),vy=speed*Math.sin(rad),wind=int(-5,5),rx=vx+wind,mag=Math.hypot(rx,vy);return {...base,board:'vector',title:'Navigate the rescue',prompt:`Thrust is ${speed} m/s at ${angle}° ${reference==='positive y'?'clockwise from positive y':'counterclockwise from positive x'}. Wind is (${wind}, 0) m/s. Set the thrust components, then add wind. Round to two decimal places.`,data:{speed,angle,reference,wind},fields:[num('x','Thrust x component','m/s'),num('y','Thrust y component','m/s'),num('rx','Resultant x component','m/s'),num('ry','Resultant y component','m/s'),num('magnitude','Resultant magnitude','m/s'),num('direction','Resultant direction counterclockwise from +x','°')],expected:{x:vx.toFixed(2),y:vy.toFixed(2),rx:rx.toFixed(2),ry:vy.toFixed(2),magnitude:mag.toFixed(2),direction:((Math.atan2(vy,rx)*180/Math.PI+360)%360).toFixed(2)},hint:'Identify the reference axis before choosing sine or cosine. Determine signs from the quadrant. Add corresponding components, then reconstruct the resultant.',worked:[`Thrust components ≈ (${vx.toFixed(2)}, ${vy.toFixed(2)}) m/s.`,`Add wind: (${rx.toFixed(2)}, ${vy.toFixed(2)}) m/s.`,`Magnitude ≈ ${mag.toFixed(2)} m/s. Use both signs to choose the direction.`],explanation:'Direction and component signs must agree.'};}
 }
}
// Restricted arithmetic parser. No eval, functions, assignments, or property access.
export function arithmetic(raw:string,variables:Record<string,number>={}):number|null{
 const normalized=raw.replaceAll('−','-').replaceAll('×','*').replaceAll('÷','/').replace(/\s/g,'');
 const tokens=normalized.match(/(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?|[A-Za-z][A-Za-z0-9]*|[()+*/^-]/g)||[];
 if(tokens.join('')!==normalized||tokens.length>100)return null;let i=0;
 const atom=():number=>{const t=tokens[i++];if(t==='('){const v=sum();if(tokens[i++]!==')')throw Error();return v;}if(t in variables)return variables[t];if(!t||!/^\d|^\./.test(t))throw Error();return Number(t)};
 const power=():number=>{const a=atom();if(tokens[i]==='^'){i++;return a**unary()}return a};
 const unary=():number=>{if(tokens[i]==='-'){i++;return -unary()}if(tokens[i]==='+'){i++;return unary()}return power()};
 const product=():number=>{let a=unary();while(tokens[i]==='*'||tokens[i]==='/'){const op=tokens[i++],b=unary();a=op==='*'?a*b:a/b}return a};
 const sum=():number=>{let a=product();while(tokens[i]==='+'||tokens[i]==='-'){const op=tokens[i++],b=product();a=op==='+'?a+b:a-b}return a};
 try{const v=sum();return i===tokens.length&&Number.isFinite(v)?v:null}catch{return null}
}
export function gradeTask(task:Task,answer:Answer){
 const missing=task.fields.find(f=>!answer[f.id]?.trim());if(missing)return {correct:false,review:false,error:'incomplete',message:`Complete ${missing.label.toLowerCase()} before checking.`};
 if(task.code==='QE3'){
 const area=Number(answer.area),space=Number(answer.space),estimate=Number(answer.estimate),low=Number(answer.low),high=Number(answer.high),total=Number(task.data.length)*Number(task.data.width);
 const consistent=[area,space,estimate,low,high].every(Number.isFinite)&&area>0&&area<=total&&space>0&&estimate>0&&Math.abs(estimate-area/space)<=Math.max(1,estimate*.1)&&low>0&&low<=estimate&&high>=estimate&&high>low&&answer.reason.trim().length>=20;
 return {correct:consistent,review:true,error:consistent?'':'estimate-structure',message:consistent?'Your calculation and range are consistent. Your teacher will review the assumptions; there is no single magic estimate.':'Check that usable area fits inside the hall, people ≈ area ÷ space per person, and your range brackets your estimate. Explain your assumptions.'};
 }
 let failed='';
 for(const f of task.fields){const actual=answer[f.id].trim(),expected=task.expected[f.id];let ok=false;
 if(task.code==='SM1'&&f.id==='formula'){
 const {a,b,c,x}=task.data;const expr=actual.replace(new RegExp('^'+x+'\\s*=\\s*'),'');
 ok=[{[a as string]:3,[b as string]:5,[c as string]:17},{[a as string]:7,[b as string]:-2,[c as string]:11},{[a as string]:2,[b as string]:9,[c as string]:-5}].every(values=>{const v=arithmetic(expr,values);return v!==null&&Math.abs(v-(values[c as string]-values[b as string])/values[a as string])<1e-8});
 }else if(task.code==='SM2'&&f.id==='expression'){const v=arithmetic(actual);ok=v!==null&&Math.abs(v-Number(task.expected.result))<1e-6&&/[+*×]/.test(actual);}
 else if(f.kind==='number'){const n=arithmetic(actual),target=Number(expected);const difference=task.code==='GV3'&&f.id==='direction'&&n!==null?Math.abs(((n-target+540)%360+360)%360-180):n===null?Infinity:Math.abs(n-target);ok=n!==null&&difference<=Math.max(task.code==='GV3'?.06:.005,Math.abs(target)*1e-6);}
 else if(task.code==='QE4'&&f.id==='result'){ok=actual===expected;}
 else ok=actual===expected;
 if(!ok){failed=f.id;break;}
 }
 if(!failed)return {correct:true,review:false,error:'',message:task.explanation};
 const rule=task.errorRules.find(r=>r.field===failed&&answer[r.field].replaceAll(' ','')===r.value.replaceAll(' ',''));
 return {correct:false,review:false,error:rule?.code||`${task.code.toLowerCase()}-${failed}`,message:rule?.feedback||`Revisit ${task.fields.find(f=>f.id===failed)!.label.toLowerCase()}. ${task.hint}`};
}
